Repository microsoft/fluent-ui-react, pull requests merged in 2018-08, with the labels that each got.

#99 fix: typings in dist
  CHANGELOG.md
  build/gulp/plugins/gulp-use-relative-import-paths.ts
  build/gulp/tasks/dist.ts
  package.json
  src/components/Provider/ProviderConsumer.tsx
  yarn.lock
Labels: ready for review

#111 feat(menu): Remove Children API examples
  CHANGELOG.md
  docs/src/examples/components/Menu/Types/MenuExample.shorthand.tsx
  docs/src/examples/components/Menu/Types/MenuExample.tsx
  docs/src/examples/components/Menu/Types/MenuExamplePrimary.shorthand.tsx
  docs/src/examples/components/Menu/Types/MenuExamplePrimary.tsx
  docs/src/examples/components/Menu/Types/MenuExampleVertical.shorthand.tsx
  docs/src/examples/components/Menu/Types/MenuExampleVertical.tsx
  docs/src/examples/components/Menu/Types/index.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePills.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePills.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimary.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimaryVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimaryVertical.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsVertical.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointing.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointing.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingPrimary.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlined.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlined.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlinedPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlinedPrimary.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVerticalFluid.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVerticalFluid.tsx
  docs/src/examples/components/Menu/Variations/index.tsx
Labels: ready for review

#105 fix: component generator
  CHANGELOG.md
  build/gulp/tasks/generate/index.ts
Labels: ready for review

#104 fix(tests): reactivate tests for Text
  CHANGELOG.md
  src/components/Text/Text.tsx
  test/specs/components/Text/Text-test.ts
Labels: ready for review

#93 feat(grid): base implementation
  CHANGELOG.md
  docs/src/examples/components/Grid/Types/GridExample.shorthand.tsx
  docs/src/examples/components/Grid/Types/GridExample.tsx
  docs/src/examples/components/Grid/Types/index.tsx
  docs/src/examples/components/Grid/Variations/GridExampleColumns.shorthand.tsx
  docs/src/examples/components/Grid/Variations/GridExampleColumns.tsx
  docs/src/examples/components/Grid/Variations/GridExampleColumnsAndRows.shorthand.tsx
  docs/src/examples/components/Grid/Variations/GridExampleColumnsAndRows.tsx
  docs/src/examples/components/Grid/Variations/GridExampleRows.shorthand.tsx
  docs/src/examples/components/Grid/Variations/GridExampleRows.tsx
  docs/src/examples/components/Grid/Variations/index.tsx
  docs/src/examples/components/Grid/index.tsx
  src/components/Grid/Grid.tsx
  src/components/Grid/index.tsx
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Grid/gridStyles.ts
  src/themes/teams/components/Grid/gridVariables.ts
  test/specs/components/Grid/Grid-test.tsx
Labels: ready for review

#102 fix: Button icon part color
  CHANGELOG.md
  docs/src/examples/components/Button/States/ButtonExampleDisabled.tsx
  docs/src/examples/components/Button/Types/ButtonExampleContentAndIcon.tsx
  docs/src/examples/components/Button/Types/ButtonExampleIcon.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleEmphasisCircular.tsx
  docs/src/examples/components/Label/Variations/LabelExampleIcon.tsx
  docs/src/examples/components/Label/Variations/LabelExampleIconPosition.tsx
  src/components/Button/Button.tsx
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/iconVariables.ts
Labels: ready for review

#103 feat(Segment): base implementation
  CHANGELOG.md
  docs/src/examples/components/Segment/Types/SegmentExample.shorthand.tsx
  docs/src/examples/components/Segment/Types/SegmentExample.tsx
  docs/src/examples/components/Segment/Types/index.tsx
  docs/src/examples/components/Segment/index.tsx
  src/components/Segment/Segment.tsx
  src/components/Segment/index.ts
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/components/Segment/segmentStyles.ts
  test/specs/components/Segment/Segment-test.ts
Labels: ready for review

#37 feat(Input): adding variation for clearable input
  CHANGELOG.md
  docs/src/examples/components/Input/Types/InputExample.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleClearable.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleFluid.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleIcon.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleIconClearable.shorthand.tsx
  docs/src/examples/components/Input/Variations/index.tsx
  src/components/Input/Input.tsx
  test/specs/components/Input/Input-test.ts
  test/specs/components/Input/Input-test.tsx
Labels: ready for merge

#112 feat(test): add shorthand property conformance tests
  CHANGELOG.md
  src/components/Button/Button.tsx
  test/specs/commonTests/implementsShorthandProp-SUI.tsx
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Button/Button-test.tsx
Labels: ready for merge

#100 feat(Radio): radio button base implementation
  CHANGELOG.md
  docs/src/examples/components/Radio/Types/RadioExample.shorthand.tsx
  docs/src/examples/components/Radio/Types/index.tsx
  docs/src/examples/components/Radio/index.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/index.ts
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Radio/radioStyles.ts
  src/themes/teams/components/Radio/radioVariables.ts
  test/specs/components/Radio/Radio-tests.ts
Labels: ready for review

#114 feat(menu): Replace shape prop with pills, pointing and underlined props
  CHANGELOG.md
  docs/src/examples/components/Menu/Variations/MenuExamplePills.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimaryVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointing.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlined.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlinedPrimary.shorthand.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
Labels: ready for merge

#124 fix(docs): regexp for component examples selection
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExamples.tsx
Labels: fix, ready for merge

#78 feat(Header): add descriptionColor variable
  CHANGELOG.md
  src/components/Header/Header.tsx
  src/lib/renderComponent.tsx
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Header/headerDescriptionVariables.ts
  src/themes/teams/components/Header/headerVariables.ts
Labels: ready for review

#33 feat(Accordion): add props interface
  src/components/Accordion/Accordion.tsx
  src/lib/NotStrictProps.ts
Labels: ready for review

#129 feat(Avatar): add props interface
  src/components/Accordion/Accordion.tsx
  src/components/Avatar/Avatar.tsx
  src/lib/Extendable.ts
  src/lib/NotStrictProps.ts
  src/lib/index.ts
Labels: ready for review

#131 feat(Chat): add props interface
  docs/src/examples/components/Chat/Types/index.tsx
  src/components/Chat/Chat.tsx
Labels: ready for merge

#74 feat(accessibility): Editing/adding behaviors and adding accessibility description for components
  CHANGELOG.md
  src/components/Button/Button.tsx
  src/components/Header/Header.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/Input/Input.tsx
  src/lib/accessibility/Behaviors/Button/ButtonBehavior.ts
  src/lib/accessibility/Behaviors/Button/ToggleButtonBehavior.ts
  src/lib/accessibility/Behaviors/Icon/IconBehavior.ts
  src/lib/accessibility/Behaviors/Image/ImageBehavior.ts
  src/lib/accessibility/index.ts
  test/specs/commonTests/handlesAccessibility.tsx
  test/specs/commonTests/index.ts
  test/specs/components/Button/Button-test.tsx
  test/specs/components/Icon/Icon-test.ts
  test/specs/components/Icon/Icon-test.tsx
  test/specs/components/Image/Image-test.js
  test/specs/components/Image/Image-test.ts
  test/specs/components/Image/Image-test.tsx
Labels: ready for merge

#132 feat(Divider): add props interface
  src/components/Divider/Divider.tsx
  src/themes/teams/components/Divider/dividerStyles.ts
Labels: ready for merge

#133 feat(Grid): add props interface
  src/components/Grid/Grid.tsx
  src/themes/teams/components/Grid/gridStyles.ts
  types/utils.d.ts
Labels: needs author feedback, ready for merge

#108 feat(tsc): add strict null check for TS compiler options
  CHANGELOG.md
  build/gulp/plugins/gulp-component-menu.ts
  build/gulp/plugins/util/findExportedComponentDefinitions.ts
  build/gulp/plugins/util/parseDocSection.ts
  build/tsconfig.common.json
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/SourceCodeManager.ts
  docs/src/components/ComponentDoc/ComponentExamples.tsx
  docs/src/components/Editor/Editor.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/index.tsx
  docs/src/utils/evalTypeScript.ts
  src/components/Accordion/Accordion.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Divider/Divider.tsx
  src/components/Input/Input.tsx
  src/lib/AutoControlledComponent.tsx
  src/lib/doesNodeContainClick.tsx
  src/lib/factories.tsx
  src/lib/felaSanitizeCssPlugin.ts
  src/lib/fontSizeUtility.ts
  src/lib/leven.tsx
  src/lib/mergeThemes.ts
  src/lib/renderComponent.tsx
  src/lib/toCompactArray.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Grid/gridStyles.ts
  src/themes/teams/components/Grid/gridVariables.ts
  src/themes/teams/components/Icon/iconVariables.ts
  src/themes/teams/components/Menu/menuVariables.ts
  types/theme.d.ts
Labels: ready for review

#137 feat(Icon): add props interface
  src/components/Icon/Icon.tsx
  types/utils.d.ts
Labels: ready for review

#130 feat(Props Interfaces): add props interface to Button, AccordionTitle, AccordionContent and refactoring the types definitions
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Chat/Chat.tsx
  src/components/Divider/Divider.tsx
  src/components/Grid/Grid.tsx
  src/lib/Extendable.ts
  src/lib/index.ts
  src/themes/teams/components/Avatar/avatarStyles.ts
Labels: ready for review

#139 feat(Header): add props interface
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Button/Button.tsx
  src/components/Chat/Chat.tsx
  src/components/Divider/Divider.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  types/utils.d.ts
Labels: ready for review

#143 feat(Layout): add props interface
  src/components/Layout/Layout.tsx
Labels: ready for merge

#140 feat(Input): add props interface
  src/components/Input/Input.tsx
Labels: ready for merge

#122 fix(doc): Maximize link points to children or shorthand example
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsMaximize.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: fix, ready for merge

#145 docs: add quick start page
  CHANGELOG.md
  build/tsconfig.common.json
  docs/src/components/CodeSnippet.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/DocPage/DocPage.tsx
  docs/src/components/DocPage/index.tsx
  docs/src/components/Editor/Editor.tsx
  docs/src/components/Editor/index.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/index.ejs
  docs/src/routes.tsx
  docs/src/views/Introduction.tsx
  docs/src/views/QuickStart.tsx
  src/index.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Icon/fontAwesomeIconStyles.ts
Labels: ready for review

#157 fix(tsc): disable strictNullChecks
  build/tsconfig.common.json
Labels: fix

#123 feat(menu): Vertical Pointing Menu
  CHANGELOG.md
  docs/src/examples/components/Menu/Variations/MenuExamplePointingStart.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingStartPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVerticalPointing.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVerticalPointingEnd.shorthand.tsx
  docs/src/examples/components/Menu/Variations/index.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
Labels: needs author feedback, ready for review

#155 feat(Menu): add prop interfaces
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
Labels: ready for review

#146 fix(typings): introduce specific types instead of 'any'
  src/components/Accordion/Accordion.tsx
  src/components/Button/Button.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Icon/Icon.tsx
  src/components/Layout/Layout.tsx
  src/themes/teams/components/Chat/chatMessageStyles.ts
  types/utils.d.ts
Labels: ready for merge

#127 fix(Input): adjust styling of Input component
  CHANGELOG.md
  src/components/Input/Input.tsx
  src/themes/teams/components/Input/inputStyles.ts
  src/themes/teams/components/Input/inputVariables.ts
  test/specs/components/Input/Input-test.tsx
Labels: fix, ready for merge

#153 feat(List): add props interface
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/themes/teams/components/List/listItemStyles.ts
  src/themes/teams/components/List/listStyles.ts
Labels: ready for review

#110 fix: correct teams theme siteVariables
  CHANGELOG.md
  src/themes/teams/components/Menu/menuVariables.ts
  src/themes/teams/siteVariables.ts
Labels: ready for merge

#135 fix(Button): icon colors and layout
  CHANGELOG.md
  src/components/Button/Button.tsx
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
Labels: fix, ready for review

#154 feat(Text): add prop interfaces
  src/components/Text/Text.tsx
  src/themes/teams/components/Text/textStyles.ts
Labels: ready for review
