Repository microsoft/fluent-ui-react, pull requests merged in 2018-10, with the labels that each got.

#189 docs: update contributing guides
  .github/CONTRIBUTING.md
  .github/add-a-feature.md
  .github/document-a-feature.md
  .github/setup-local-development.md
  .github/test-a-feature.md
  CHANGELOG.md
  README.md
  build/gulp/tasks/docs.ts
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/routes.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/Glossary.tsx
  docs/src/views/QuickStart.tsx
Labels: ready for merge

#286 feat(menu): add menu item focus styles
  CHANGELOG.md
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyPrimaryInverted.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyVerticalPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleToolbar.shorthand.tsx
  docs/src/examples/components/Menu/Variations/index.tsx
  src/components/Button/Button.tsx
  src/components/Menu/MenuItem.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/lib/index.ts
  src/lib/isFromKeyboard.ts
  src/lib/typescriptUtils.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuVariables.ts
  src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
Labels: ready for review

#272 docs: hiding children props in doc site
  docs/src/components/ComponentDoc/ComponentTable/ComponentTableRow.tsx
  docs/src/index.ejs
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Label/Label.tsx
  src/components/List/List.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/components/Portal/Portal.tsx
  src/components/Portal/PortalInner.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Ref/Ref.tsx
Labels: ready for merge

#259 chore: Publish all master builds to npm with @next tag
  .circleci/config.yml
Labels: ready for merge

#297 chore: Enable noUnusedLocals in tsconfig
  build/tsconfig.common.json
Labels: needs author feedback, ready for review

#305 fix(Accordion): generate key for the Accordion.Content
  CHANGELOG.md
  docs/src/examples/components/Accordion/Variations/AccordionExampleList.shorthand.tsx
  src/components/Accordion/Accordion.tsx
Labels: ready for merge

#280 feat(docs): adding theme switcher
  CHANGELOG.md
  build/tsconfig.docs.json
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/context/theme-context.tsx
  docs/src/index.tsx
  src/themes/index.ts
  src/themes/teams-dark/componentVariables.ts
  src/themes/teams-dark/components/Button/buttonVariables.ts
  src/themes/teams-dark/index.ts
  src/themes/teams-dark/siteVariables.ts
  src/themes/teams-high-contrast/index.ts
  src/themes/teams-high-contrast/siteVariables.ts
  src/themes/teams/components/Input/inputVariables.ts
  src/themes/teams/siteVariables.ts
  src/themes/teams/staticStyles/globalStyles.ts
Labels: ready for review

#303 docs(accessibility): Accessibility contributing guide
  .github/CONTRIBUTING.md
  CHANGELOG.md
Labels: ready for merge

#235 docs(chat-pane): chat-pane prototype
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/chatPane/chatPaneContent.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/chatPane/chatPaneLayout.tsx
  docs/src/prototypes/chatPane/composeMessage.tsx
  docs/src/prototypes/chatPane/index.tsx
  docs/src/prototypes/chatPane/services/dataMock.ts
  docs/src/prototypes/chatPane/services/dateUtils.ts
  docs/src/prototypes/chatPane/services/index.ts
  docs/src/prototypes/chatPane/services/interfaces.ts
  docs/src/prototypes/chatPane/services/messageFactoryMock.ts
  docs/src/routes.tsx
  package.json
  src/components/Chat/index.ts
  src/components/Divider/index.ts
  src/components/Segment/Segment.tsx
  src/components/Status/index.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Icon/svg/icons/call.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideo.tsx
  src/themes/teams/components/Icon/svg/icons/teamCreate.tsx
  yarn.lock
Labels: ready for review

#302 fix(Popup): render element as body children
  CHANGELOG.md
  src/components/Popup/Popup.tsx
Labels: ready for merge

#304 fix(Popup): keypress toggle logic
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupExample.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  src/lib/accessibility/Behaviors/Popup/PopupBehavior.ts
Labels: ready for merge

#287 fix(radio-group): replaced label with content
  CHANGELOG.md
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExampleChecked.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExampleDisabled.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupVerticalExample.shorthand.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
Labels: ready for review

#309 fix(docs): fix className to receive string
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: ready for review

#316 feat: give component examples a theme specific background
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  src/themes/teams-dark/siteVariables.ts
  src/themes/teams-high-contrast/siteVariables.ts
  src/themes/teams/siteVariables.ts
Labels: wip

#310 fix(Input): remove duplcated 'onChange' handling
  CHANGELOG.md
  src/components/Input/Input.tsx
Labels: fix, ready for review

#292 fix: make theme variables and styles extensible
  CHANGELOG.md
  src/themes/teams/components/Menu/menuItemStyles.ts
  types/theme.d.ts
Labels: ready for merge

#247 feat(Accessibility): Improve accessibility behaviors, make them reusable
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Button/buttonBehavior.ts
  src/lib/accessibility/Behaviors/Button/buttonGroupBehavior.ts
  src/lib/accessibility/Behaviors/Button/toggleButtonBehavior.ts
  src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  src/lib/accessibility/Behaviors/Chat/chatEnterEscBehavior.ts
  src/lib/accessibility/Behaviors/Chat/chatMessageBehavior.ts
  src/lib/accessibility/Behaviors/Chat/chatMessageEnterEscBehavior.ts
  src/lib/accessibility/Behaviors/DefaultBehavior.ts
  src/lib/accessibility/Behaviors/Icon/iconBehavior.ts
  src/lib/accessibility/Behaviors/Image/imageBehavior.ts
  src/lib/accessibility/Behaviors/Input/inputBehavior.ts
  src/lib/accessibility/Behaviors/List/ListItemBehavior.ts
  src/lib/accessibility/Behaviors/List/basicListBehavior.ts
  src/lib/accessibility/Behaviors/List/basicListItemBehavior.ts
  src/lib/accessibility/Behaviors/List/listBehavior.ts
  src/lib/accessibility/Behaviors/List/listItemBehavior.ts
  src/lib/accessibility/Behaviors/List/selectableListBehavior.ts
  src/lib/accessibility/Behaviors/List/selectableListItemBehavior.ts
  src/lib/accessibility/Behaviors/Menu/menuBehavior.ts
  src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  src/lib/accessibility/Behaviors/Radio/radioGroupBehavior.ts
  src/lib/accessibility/Behaviors/Radio/radioGroupItemBehavior.ts
  src/lib/accessibility/Behaviors/Tab/tabBehavior.ts
  src/lib/accessibility/Behaviors/Tab/tabListBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/toolbarBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/toolbarButtonBehavior.ts
  src/lib/accessibility/Behaviors/defaultBehavior.ts
  src/lib/accessibility/index.ts
  src/lib/accessibility/interfaces.ts
  src/lib/renderComponent.tsx
  test/specs/commonTests/handlesAccessibility.tsx
  test/specs/components/Button/Button-test.tsx
  test/specs/components/Button/ButtonGroup-test.tsx
  test/specs/components/Chat/Chat-test.ts
  test/specs/components/Chat/ChatMessage-test.tsx
  test/specs/components/Menu/Menu-test.tsx
  test/specs/components/Menu/MenuItem-test.tsx
Labels: RFC, ready for review

#319 feat(Popup): autocontrolled mode
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupControlledExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupControlledExample.tsx
  docs/src/examples/components/Popup/Types/PopupExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupExample.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  src/components/Popup/Popup.tsx
  src/lib/AutoControlledComponent.tsx
Labels: ready for merge

#329 docs(ComponentExample): remove cruft prop `suiVersion`
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleTitle.tsx
Labels: ready for review

#245 feat(test): add accessibility behavior tests
  package.json
  src/lib/accessibility/Behaviors/Image/imageBehavior.ts
  src/lib/accessibility/Behaviors/List/listBehavior.ts
  src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  src/lib/accessibility/index.ts
  test/specs/behaviors/behavior-test.tsx
  test/specs/behaviors/listBehavior-test.tsx
  test/specs/behaviors/listItemBehavior-test.tsx
  test/specs/behaviors/testDefinitions.ts
  test/specs/behaviors/testHelper.tsx
Labels: ready for review

#322 feat(Popup): make 'content' prop to be a shorthand
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupContentWrapperExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupContentWrapperExample.tsx
  docs/src/examples/components/Popup/Types/PopupControlledExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupControlledExample.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.shorthand.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
Labels: ready for review

#335 [RFC] feat(slot): create generic slot component
  CHANGELOG.md
  docs/src/examples/components/Slot/index.tsx
  src/components/Button/Button.tsx
  src/components/Slot/Slot.tsx
  src/components/Slot/index.ts
  test/specs/commonTests/isConformant.tsx
  test/specs/commonTests/isExportedAtTopLevel.tsx
  test/specs/components/Slot/Slot-test.ts
Labels: RFC, ready for review

#342 fix(FocusZone): with defaultTabbableElement prop set tabindexes are not updated accordingly
  CHANGELOG.md
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
Labels: ready for review

#331 feat(proto): Meeting options page
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsFooter.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsHeader.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsLink.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsLogo.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsMeetingOptions.tsx
  docs/src/prototypes/meetingOptions/components/TransparentDivider.tsx
  docs/src/prototypes/meetingOptions/index.tsx
  docs/src/prototypes/meetingOptions/styles.ts
  docs/src/routes.tsx
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/iconVariables.ts
  src/themes/teams/components/Icon/svg/icons/index.ts
  src/themes/teams/components/Icon/svg/icons/teams.tsx
Labels: ready for merge

#317 feat(Text): Redlining text component for Teams dark & contrast themes
  src/themes/teams-dark/componentVariables.ts
  src/themes/teams-dark/components/Text/textVariables.ts
  src/themes/teams-dark/siteVariables.ts
  src/themes/teams-high-contrast/componentVariables.ts
  src/themes/teams-high-contrast/components/Text/textVariables.ts
  src/themes/teams-high-contrast/siteVariables.ts
  src/themes/teams/components/Text/textStyles.ts
  src/themes/teams/components/Text/textVariables.ts
Labels: ready for merge

#315 feat(proto): Avatar showing employee card
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/employeeCard/AvatarEmployeeCard.tsx
  docs/src/prototypes/employeeCard/EmployeeCard.tsx
  docs/src/prototypes/employeeCard/Text.tsx
  docs/src/prototypes/employeeCard/index.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsLogo.tsx
  docs/src/routes.tsx
Labels: ready for merge

#348 feat(Chat): add content and renderContent props
  CHANGELOG.md
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: ready for review

#343 chore: use eval-source-map
  config.ts
Labels: ready for merge

#360 fix(menu): fix for cropped rounded corners
  CHANGELOG.md
  src/themes/teams/components/Menu/menuStyles.ts
Labels: ready for merge

#356 feat(Popup): add 'target' prop
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupCustomTargetExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupCustomTargetExample.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  src/components/Popup/Popup.tsx
  src/components/Ref/Ref.tsx
Labels: ready for merge

#336 BREAKING: Button - implement dark theme and match redlines
  CHANGELOG.md
  docs/src/examples/components/Button/Usage/ButtonUsageExample.shorthand.tsx
  docs/src/examples/components/Button/Usage/index.tsx
  docs/src/examples/components/Button/index.tsx
  docs/src/views/ThemingExamples.tsx
  src/themes/teams-dark/components/Button/buttonVariables.ts
  src/themes/teams-dark/siteVariables.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
  src/themes/teams/siteVariables.ts
Labels: ready for merge

#362 fix: grays in Teams dark theme siteVariables
  src/themes/teams-dark/siteVariables.ts
Labels: ready for merge

#366 feat(docs): Removing ugly default value
  docs/src/components/ComponentDoc/ComponentProp/ComponentPropDefaultValue.tsx
Labels: ready for merge

#367 fix: remove 'skipLibCheck' flag requirement from client's projects
  CHANGELOG.md
  build/gulp/plugins/gulp-use-relative-import-paths.ts
  build/gulp/tasks/dist.ts
  build/gulp/tasks/test-projects.tsx
  package.json
  src/lib/factories.tsx
  types/theme.d.ts
  yarn.lock
Labels: fix, ready for review

#368 style: high contrast theme - adding Cyan color for selected state
  src/themes/teams-high-contrast/siteVariables.ts
Labels: ready for merge, styling issue

#326 feat(input): new Input component with 'input' slot
  CHANGELOG.md
  docs/src/examples/components/Input/Variations/InputExampleClearable.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleFluid.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleInlineIconClearable.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleInputSlot.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleTargeting.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleWrapperSlot.shorthand.tsx
  docs/src/examples/components/Input/Variations/index.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupVerticalExample.shorthand.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/chatPane/composeMessage.tsx
  package.json
  src/components/Input/Input.tsx
  src/components/Slot/Slot.tsx
  src/index.ts
  src/lib/customPropTypes.tsx
  src/lib/factories.tsx
  src/themes/teams/components/Input/inputStyles.ts
  src/themes/teams/components/Input/inputVariables.ts
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/commonTests/implementsWrapperProp.tsx
  test/specs/commonTests/index.ts
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Input/Input-test.tsx
  test/specs/components/Slot/Slot-test.ts
  yarn.lock
Labels: RFC, ready for merge

#353 feat(Form): base implementation
  CHANGELOG.md
  docs/src/examples/components/Form/Types/FormExample.shorthand.tsx
  docs/src/examples/components/Form/Types/FormExample.tsx
  docs/src/examples/components/Form/Types/FormExampleInline.shorthand.tsx
  docs/src/examples/components/Form/Types/FormExampleInline.tsx
  docs/src/examples/components/Form/Types/index.tsx
  docs/src/examples/components/Form/index.tsx
  src/components/Form/Form.tsx
  src/components/Form/FormField.tsx
  src/components/Form/index.ts
  src/components/Input/Input.tsx
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/components/Form/formFieldStyles.ts
  src/themes/teams/components/Form/formStyles.ts
  test/specs/components/Form/Form-test.tsx
  test/specs/components/Form/FormField-test.tsx
  types/theme.d.ts
Labels: RFC, ready for review

#380 fix(chore): address build issue
  webpack.config.ts
Labels: fix, ready for review

#369 docs(readme): add "How can I help" and remove specs
  README.md
  specifications/component-api.md
  specifications/creating-components.md
  specifications/css-in-js.md
  specifications/event-stack.md
  specifications/html-font-size.md
  specifications/parent-child-coupling.md
  specifications/shorthand-api.md
  specifications/sizing.md
  specifications/theming.md
Labels: docs, ready for merge

#285 feat: export mergeThemes and add examples
  CHANGELOG.md
  docs/src/examples/components/Provider/Types/ProviderExample.shorthand.tsx
  docs/src/examples/components/Provider/Types/index.tsx
  docs/src/examples/components/Provider/index.tsx
  src/components/Provider/Provider.tsx
  src/index.ts
  test/specs/components/Provider/Provider-test.tsx
  test/specs/components/Provider/ProviderConsumer-test.tsx
Labels: ready for merge, ready for review

#239 [RFC] feat(Accessibility): Add focus trap zone
  CHANGELOG.md
  docs/src/examples/components/Portal/Types/PortalExample.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExample.tsx
  docs/src/examples/components/Portal/Types/PortalExampleControlled.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExampleControlled.tsx
  docs/src/examples/components/Portal/Types/PortalExampleFocusTrapped.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExampleFocusTrapped.tsx
  docs/src/examples/components/Portal/Types/index.tsx
  src/components/Portal/Portal.tsx
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/focusUtilities.ts
  src/lib/accessibility/FocusZone/index.ts
  src/lib/accessibility/types.ts
  src/lib/eventStack/EventTarget.tsx
  src/lib/eventStack/eventStack.tsx
  test/specs/lib/FocusTrapZone-test.tsx
Labels: RFC, ready for merge

#392 fix(accessibility): remove 'aria-haspopup' from Popup behavior
  src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
Labels: fix, ready for merge

#393 fix(FocusZone): Remove redundant 'handledProps'
  src/lib/accessibility/FocusZone/FocusZone.tsx
Labels: ready for merge

#378 fix(provider): fix for rendering components outside provider
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentDocLinks.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ContributionPrompt.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/constants.ts
  docs/src/utils/constants.ts
  docs/src/utils/index.tsx
  src/lib/constants.ts
  src/lib/index.ts
  src/lib/providerMissingHandler.ts
  src/lib/renderComponent.tsx
  test/specs/commonTests/handlesAccessibility.tsx
  test/specs/commonTests/htmlIsAccessibilityCompliant.ts
  test/specs/commonTests/implementsCollectionShorthandProp.tsx
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/commonTests/implementsWrapperProp.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/commonTests/stylesFunction-test.tsx
  test/specs/components/Button/Button-test.tsx
  test/specs/components/Chat/ChatMessage-test.tsx
  test/specs/components/Form/FormField-test.tsx
  test/specs/components/Icon/Icon-test.tsx
  test/specs/components/Image/Image-test.tsx
  test/specs/components/Input/Input-test.tsx
  test/specs/components/Label/Label-test.tsx
  test/specs/components/Menu/Menu-test.tsx
  test/specs/components/Menu/MenuItem-test.tsx
  test/specs/components/Portal/Portal-test.tsx
  test/specs/components/Slot/Slot-test.ts
  test/utils/index.ts
  test/utils/testingComponents.tsx
  test/utils/withProvider.tsx
Labels: ready for merge

#377 feat(Input): expose Input's <input> element by inputRef
  CHANGELOG.md
  src/components/Input/Input.tsx
Labels: ready for merge

#397 fix(FocusZone) Remove unused prop 'componentRef'
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/FocusZone.types.ts
Labels: fix, ready for merge

#384 fix(Icon): Color & docs update for Teams theme
  CHANGELOG.md
  docs/src/examples/components/Icon/States/IconExampleDisabled.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleColor.shorthand.tsx
  docs/src/examples/components/Icon/Variations/index.tsx
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/iconVariables.ts
Labels: ready for merge, redlines

#387 docs: simplify and update accessibility headings
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  docs/src/components/ComponentDoc/ComponentDocTag.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Chat/Chat.tsx
  src/components/Divider/Divider.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Icon/Icon.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/Text/Text.tsx
Labels: ready for merge, ready for review

#402 fix(Attachment): do not render progress value
  CHANGELOG.md
  src/components/Attachment/Attachment.tsx
Labels: ready for merge, ready for review

#351 test: Adding/consolidating unit tests/description
  src/lib/accessibility/Behaviors/Button/buttonBehavior.ts
  src/lib/accessibility/Behaviors/Button/toggleButtonBehavior.ts
  src/lib/accessibility/Behaviors/Input/inputBehavior.ts
  src/lib/accessibility/Behaviors/Menu/menuBehavior.ts
  src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  src/lib/accessibility/Behaviors/Radio/radioGroupItemBehavior.ts
  src/lib/accessibility/Behaviors/Tab/tabBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/toolbarButtonBehavior.ts
  test/specs/behaviors/behavior-test.tsx
  test/specs/behaviors/testDefinitions.ts
Labels: ready for review

#407 docs: add transparent button to examples
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsMaximize.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowTransparent.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: docs, ready for merge, ready for review

#408 fix(Segment): add background color
  CHANGELOG.md
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Segment/segmentStyles.ts
  src/themes/teams/components/Segment/segmentVariables.ts
Labels: ready for merge, ready for review

#391 fix(eventStack): make subscription logic to be always async
  CHANGELOG.md
  src/lib/eventStack/eventStack.tsx
  test/specs/components/Portal/Portal-test.tsx
  test/specs/lib/eventStack/eventStack-test.ts
  test/utils/index.ts
  test/utils/nextFrame.ts
Labels: fix, ready for merge

#390 fix(button): removed dotted outline in firefox
  CHANGELOG.md
  docs/src/Style.ts
Labels: ready for merge

#278 fix: (ListItem) - Fix endMedia to not be removed from DOM on mouseleave for ListItem
  CHANGELOG.md
  docs/src/examples/components/List/Content/ListExampleEndMedia.shorthand.tsx
  docs/src/examples/components/List/Content/ListExampleEndMedia.tsx
  docs/src/examples/components/List/Variations/ListExampleTruncate.shorthand.tsx
  src/components/List/ListItem.tsx
  src/themes/teams/components/List/listItemStyles.ts
  src/themes/teams/components/List/listItemVariables.ts
Labels: ready for review

#373 fix(Avatar): Adding dark and contrast theme files for Avatar and Status Indicator.
  CHANGELOG.md
  docs/src/examples/components/Avatar/Usage/AvatarUsageExample.shorthand.tsx
  docs/src/examples/components/Avatar/Usage/index.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleStatusCustomization.shorthand.tsx
  docs/src/examples/components/Avatar/index.tsx
  src/components/Status/Status.tsx
  src/themes/teams-dark/components/Button/buttonVariables.ts
  src/themes/teams-dark/components/Divider/dividerVariables.ts
  src/themes/teams-dark/components/Text/textVariables.ts
  src/themes/teams-high-contrast/componentVariables.ts
  src/themes/teams-high-contrast/components/Avatar/avatarVariables.ts
  src/themes/teams-high-contrast/components/Divider/dividerVariables.ts
  src/themes/teams-high-contrast/components/Text/textVariables.ts
  src/themes/teams-high-contrast/siteVariables.ts
  src/themes/teams/components/Avatar/avatarVariables.ts
  src/themes/teams/components/Divider/dividerVariables.ts
  types/utils.d.ts
Labels: ready for merge, redlines
