Repository microsoft/fluent-ui-react, pull requests merged in 2018-09, with the labels that each got.

#174 feat(Radio): add props interface
  src/components/Radio/Radio.tsx
  src/themes/teams/components/Radio/radioStyles.ts
Labels: ready for merge

#175 feat(Segment): add props interface
  src/components/Chat/ChatMessage.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Segment/Segment.tsx
Labels: ready for merge

#173 feat(renderComponent): merged state and props for styles and accessibility
  CHANGELOG.md
  src/lib/renderComponent.tsx
  test/specs/commonTests/stylesFunction-test.tsx
  types/theme.d.ts
Labels: ready for merge

#119 feat(docs): adding 'behaviors' section to menu
  .gitignore
  CHANGELOG.md
  build/gulp/plugins/gulp-component-menu-behaviors.ts
  build/gulp/tasks/docs.ts
  docs/src/components/DocsBehaviorRoot.tsx
  docs/src/components/DocsRoot.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/utils/constants.ts
  package.json
  yarn.lock
Labels: ready for merge

#182 feat(Button): add iconOnly prop
  CHANGELOG.md
  docs/src/examples/components/Button/Types/ButtonExampleIconOnly.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExampleIconOnly.tsx
  docs/src/examples/components/Button/Types/index.tsx
  src/components/Button/Button.tsx
  src/themes/teams/components/Button/buttonStyles.ts
Labels: RFC, ready for review

#83 feat(accessibility): add behaviours for tabs, tablists and toolbars
  docs/src/examples/components/Menu/Variations/MenuExampleTabList.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleToolbar.shorthand.tsx
  docs/src/examples/components/Menu/Variations/index.tsx
  src/components/Menu/MenuItem.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Menu/MenuItemBehavior.ts
  src/lib/accessibility/Behaviors/Tab/TabBehavior.ts
  src/lib/accessibility/Behaviors/Tab/TabListBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/ToolbarBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/ToolbarButtonBehavior.ts
  src/lib/accessibility/index.ts
  src/lib/accessibility/interfaces.ts
  src/lib/renderComponent.tsx
  test/specs/components/Menu/Menu-test.tsx
  test/specs/components/Menu/MenuItem-test.tsx
Labels: ready for merge

#55 feat(Label): added image and imagePosition props
  CHANGELOG.md
  docs/src/examples/components/Label/Content/LabelExample.shorthand.tsx
  docs/src/examples/components/Label/Content/LabelExample.tsx
  docs/src/examples/components/Label/Content/LabelExampleContentCustomization.shorthand.tsx
  docs/src/examples/components/Label/Content/LabelExampleIcon.shorthand.tsx
  docs/src/examples/components/Label/Content/LabelExampleIconPosition.shorthand.tsx
  docs/src/examples/components/Label/Content/LabelExampleImage.shorthand.tsx
  docs/src/examples/components/Label/Content/LabelExampleImagePosition.shorthand.tsx
  docs/src/examples/components/Label/Content/index.tsx
  docs/src/examples/components/Label/Types/index.tsx
  docs/src/examples/components/Label/Variations/LabelExampleIcon.tsx
  docs/src/examples/components/Label/Variations/LabelExampleIconPosition.shorthand.tsx
  docs/src/examples/components/Label/Variations/LabelExampleIconPosition.tsx
  docs/src/examples/components/Label/Variations/LabelExampleIconProps.shorthand.tsx
  docs/src/examples/components/Label/Variations/index.tsx
  docs/src/examples/components/Label/index.tsx
  src/components/Image/Image.tsx
  src/components/Label/Label.tsx
  src/themes/teams/components/Label/labelStyles.ts
  src/themes/teams/components/Label/labelVariables.ts
  src/themes/teams/components/Layout/layoutStyles.ts
  test/specs/components/Label/Label-test.tsx
Labels: ready for review

#185 chore: Enable noImplicitReturns TS check
  build/tsconfig.common.json
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  src/lib/customPropTypes.tsx
  src/lib/factories.tsx
Labels: ready for merge

#156 feat(accessibility): add HTML accessibility rules validation tests
  package.json
  test/specs/commonTests/htmlIsAccessibilityCompliant.ts
  test/specs/commonTests/index.ts
  test/specs/components/Button/Button-test.tsx
  yarn.lock
Labels: ready for review

#179 feat(Button): added ButtonGroup component
  CHANGELOG.md
  build/gulp/plugins/util/getComponentInfo.ts
  docs/src/examples/components/Button/Groups/ButtonGroupCircularExample.shorthand.tsx
  docs/src/examples/components/Button/Groups/ButtonGroupExample.shorthand.tsx
  docs/src/examples/components/Button/Groups/index.tsx
  docs/src/examples/components/Button/index.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Button/index.ts
  src/components/List/List.tsx
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Button/buttonGroupStyles.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
  test/specs/commonTests/implementsCollectionShorthandProp.tsx
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/components/Button/ButtonGroup-test.tsx
  test/specs/components/List/List-test.ts
  test/specs/components/Menu/Menu-test.tsx
Labels: RFC, ready for merge

#200 fix(Divider, Menu): replacing the gray12 from variables to gray08
  CHANGELOG.md
  src/themes/teams/components/Divider/dividerVariables.ts
  src/themes/teams/components/Menu/menuVariables.ts
Labels: fix, ready for merge

#177 feat(Button): add text variant
  CHANGELOG.md
  docs/src/examples/components/Button/Groups/ButtonGroupCircularExample.shorthand.tsx
  docs/src/examples/components/Button/Groups/ButtonGroupExample.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleText.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleText.tsx
  docs/src/examples/components/Button/Variations/index.tsx
  src/components/Button/Button.tsx
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
Labels: RFC, ready for merge

#169 feat(Text): Adding timestamp hover treatment for the Teams theme
  docs/src/examples/components/Text/Variations/TextExampleTimestamp.tsx
  src/themes/teams/components/Text/textStyles.ts
  src/themes/teams/components/Text/textVariables.ts
Labels: ready for merge

#151 feat(Text): Updating text component to match redlines
  codecov.yml
  docs/src/examples/components/Text/States/TextExampleTemporary.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleTemporary.tsx
  docs/src/examples/components/Text/States/index.tsx
  src/components/Text/Text.tsx
  src/themes/teams/components/Input/inputVariables.ts
  src/themes/teams/components/List/listItemVariables.ts
  src/themes/teams/components/Text/textStyles.ts
  src/themes/teams/components/Text/textVariables.ts
  src/themes/teams/siteVariables.ts
  src/themes/teams/staticStyles/globalStyles.ts
  test/specs/components/Text/Text-test.ts
  test/specs/components/Text/Text-test.tsx
Labels: ready for merge

#121 [RFC]Feat(Accessibility): Add keyboard action handlers
  CHANGELOG.md
  src/components/Menu/MenuItem.tsx
  src/lib/UIComponent.tsx
  src/lib/accessibility/Behaviors/Menu/MenuItemBehavior.ts
  src/lib/accessibility/interfaces.ts
  src/lib/getKeyDownHandlers.ts
  src/lib/keyboardHandlerFilter.ts
  src/lib/renderComponent.tsx
  test/specs/lib/getKeyDownHandlers-test.ts
  test/specs/lib/keyboardHandlerFilter-test.ts
Labels: RFC, ready for review

#204 fix: teams theme font sizes
  CHANGELOG.md
  docs/src/index.tsx
  src/themes/teams/siteVariables.ts
Labels: ready for merge

#205 fix: text component docs
  CHANGELOG.md
  docs/src/examples/components/Text/States/TextExampleDisabled.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleError.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleSuccess.shorthand.tsx
  docs/src/examples/components/Text/Types/TextSizesExample.shorthand.tsx
  docs/src/examples/components/Text/Types/TextSizesExample.tsx
  docs/src/examples/components/Text/Types/TextWeightsExample.shorthand.tsx
  docs/src/examples/components/Text/Types/TextWeightsExample.tsx
  docs/src/examples/components/Text/Variations/TextExampleAtMention.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleTimestamp.shorthand.tsx
  src/components/Text/Text.tsx
Labels: ready for merge

#209 fix(chore): add git tags verification logic
  build/gulp/tasks/git/index.ts
  build/gulp/tasks/git/prepush.ts
  gulpfile.ts
  package.json
Labels: fix, ready for review

#213 feat(accessibility): add logic to differentiate mouse focus from keyboard focus
  package.json
  src/components/Button/Button.tsx
  src/themes/teams/components/Button/buttonStyles.ts
  test/specs/components/Button/Button-test.tsx
  yarn.lock
Labels: ready for merge

#150 feat(popup): base implementation
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  docs/src/examples/components/Popup/Variations/PopupExampleBasic.shorthand.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.shorthand.tsx
  docs/src/examples/components/Popup/Variations/index.tsx
  docs/src/examples/components/Popup/index.tsx
  package.json
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/components/Popup/index.ts
  src/components/Popup/positioningHelper.ts
  src/index.ts
  src/lib/renderComponent.tsx
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Popup/popupContentStyles.ts
  src/themes/teams/components/Popup/popupContentVariables.ts
  test/specs/components/Popup/Popup-test.tsx
  test/specs/components/Popup/PopupContent-test.ts
  yarn.lock
Labels: needs changes

#120 feat(Input): inline text - adding inline prop for Input component
  CHANGELOG.md
  docs/src/examples/components/Input/Types/InputExample.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleClearable.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleFluid.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleIcon.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleIconClearable.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleInline.shorthand.tsx
  docs/src/examples/components/Input/Variations/index.tsx
  src/components/Input/Input.tsx
  src/themes/teams/components/Input/inputStyles.ts
Labels: ready for review

#208 feat: Add Status as a separate component
  CHANGELOG.md
  docs/src/examples/components/Avatar/Variations/AvatarExampleExcludedInitials.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleGetInitials.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleName.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExamplePresenceIndicatorCustomization.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleSize.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleStatus.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleStatusCustomization.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/index.tsx
  docs/src/examples/components/Chat/Variations/ChatExampleAvatar.shorthand.tsx
  docs/src/examples/components/Segment/Types/SegmentExample.shorthand.tsx
  docs/src/examples/components/Status/Types/StatusExample.shorthand.tsx
  docs/src/examples/components/Status/Types/StatusTypeExample.shorthand.tsx
  docs/src/examples/components/Status/Types/index.tsx
  docs/src/examples/components/Status/Variations/StatusColorExample.shorthand.tsx
  docs/src/examples/components/Status/Variations/StatusCustomExample.shorthand.tsx
  docs/src/examples/components/Status/Variations/StatusIconExample.shorthand.tsx
  docs/src/examples/components/Status/Variations/index.tsx
  docs/src/examples/components/Status/index.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Status/Status.tsx
  src/components/Status/index.ts
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Avatar/avatarStyles.ts
  src/themes/teams/components/Avatar/avatarVariables.ts
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Status/statusStyles.ts
  src/themes/teams/components/Status/statusVariables.ts
  src/themes/teams/siteVariables.ts
  test/specs/components/Status/Status-test.tsx
Labels: ready for merge

#116 feat(FocusZone): Implement FocusZone into renderComponent
  CHANGELOG.md
  src/lib/accessibility/Behaviors/Menu/MenuBehavior.ts
  src/lib/accessibility/Behaviors/Menu/MenuItemBehavior.ts
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/FocusZone.types.ts
  src/lib/accessibility/FocusZone/focusUtilities.ts
  src/lib/accessibility/FocusZone/index.ts
  src/lib/accessibility/interfaces.ts
  src/lib/customPropTypes.tsx
  src/lib/renderComponent.tsx
  test/specs/commonTests/handlesAccessibility.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Button/Button-test.tsx
  test/specs/components/Icon/Icon-test.tsx
  test/specs/components/Image/Image-test.tsx
  test/specs/components/Menu/Menu-test.tsx
  test/specs/lib/FocusZone-test.tsx
Labels: ready for merge

#181 feat(docs): adding accessibility description for behaviors
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDocTag.tsx
  docs/src/components/DocsBehaviorRoot.tsx
  src/components/Button/Button.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/lib/accessibility/Behaviors/Button/ButtonBehavior.ts
  src/lib/accessibility/Behaviors/Button/ToggleButtonBehavior.ts
  src/lib/accessibility/Behaviors/Icon/IconBehavior.ts
  src/lib/accessibility/Behaviors/Image/ImageBehavior.ts
  src/lib/accessibility/Behaviors/Input/InputBehavior.ts
  src/lib/accessibility/Behaviors/List/BasicListBehavior.ts
  src/lib/accessibility/Behaviors/List/BasicListItemBehavior.ts
  src/lib/accessibility/Behaviors/List/ListBehavior.ts
  src/lib/accessibility/Behaviors/List/ListItemBehavior.ts
  src/lib/accessibility/Behaviors/List/SelectableListBehavior.ts
  src/lib/accessibility/Behaviors/List/SelectableListItemBehavior.ts
  src/lib/accessibility/Behaviors/Menu/MenuBehavior.ts
  src/lib/accessibility/Behaviors/Menu/MenuItemBehavior.ts
  src/lib/accessibility/Behaviors/Tree/GroupBehavior.ts
  src/lib/accessibility/Behaviors/Tree/TreeBehavior.ts
  src/lib/accessibility/Behaviors/Tree/TreeItemBehavior.ts
  src/lib/accessibility/index.ts
Labels: ready for merge

#207 feat: ensure variables and styles are passed to component parts
  src/components/Button/Button.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Input/Input.tsx
  src/components/Label/Label.tsx
  src/lib/mergeThemes.ts
  src/lib/renderComponent.tsx
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Label/labelVariables.ts
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/lib/mergeThemes/mergeComponentVariables-test.ts
  types/theme.d.ts
Labels: ready for review

#206 feat(Radio): added value, disabled, name, checked, defaultChecked and onChange props
  CHANGELOG.md
  docs/src/examples/components/Radio/States/RadioExampleChecked.shorthand.tsx
  docs/src/examples/components/Radio/States/RadioExampleDisabled.shorthand.tsx
  docs/src/examples/components/Radio/States/index.tsx
  docs/src/examples/components/Radio/Types/RadioExample.shorthand.tsx
  docs/src/examples/components/Radio/index.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Radio/Radio.tsx
  src/themes/teams/components/Radio/radioStyles.ts
  src/themes/teams/components/Radio/radioVariables.ts
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Radio/Radio-test.ts
Labels: ready for merge

#222 fix(Popup): wrong import
  src/components/Popup/Popup.tsx
Labels: fix, ready for review

#224 perf: enable tree shaking for Webpack
  CHANGELOG.md
  package.json
Labels: ready for review

#221 fix(docs): font size issue
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: fix, ready for review

#187 Chore: Fix gulp watch on Windows
  build/gulp/tasks/docs.ts
  config.ts
Labels: fix, ready for merge

#234 fix(Divider): misusage of the variables for the default and secondary type
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Divider/dividerVariables.ts
Labels: fix, ready for review

#232 fix(docs): Children API tab styles
  docs/src/Style.ts
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleSrc.shorthand.tsx
  docs/src/index.tsx
Labels: fix, ready for review

#216 feat: Updating buttons to be in line with new styles
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
Labels: ready for merge

#167 docs: add accessibility guide
  docs/src/components/CodeSnippet.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/index.ejs
  docs/src/routes.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/QuickStart.tsx
Labels: ready for merge

#223 feat(test): improvement of performance of UTs on CircleCI by using the maxWorkers option of jest
  .circleci/config.yml
Labels: ready for review

#238 BREAKING: apply styles prop to the root element
  CHANGELOG.md
  build/gulp/tasks/generate/templates/src-components/$DisplayName/$DisplayName.tsx
  docs/src/components/Knobs/KnobsLabel.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.shorthand.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/components/Radio/Radio.tsx
  src/components/Segment/Segment.tsx
  src/components/Status/Status.tsx
  src/components/Text/Text.tsx
  src/lib/getElementType.tsx
  src/lib/renderComponent.tsx
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/commonTests/stylesFunction-test.tsx
  types/theme.d.ts
Labels: ready for review

#242 feat(chat message): add `author` and `timestamp` props
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatExample.tsx
  docs/src/examples/components/Chat/Variations/ChatExampleAvatar.shorthand.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Text/Text.tsx
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Chat/chatMessageVariables.ts
  src/themes/teams/components/Chat/chatStyles.ts
  src/themes/teams/components/Chat/chatVariables.ts
  test/specs/components/Chat/ChatMessage-test.tsx
Labels: ready for merge

#250 fix: allow string or number as Input value
  CHANGELOG.md
  src/components/Input/Input.tsx
Labels: ready for review

#229 feat(radio): Radio group compliant with ARIA patterns
  CHANGELOG.md
  docs/src/examples/components/Radio/States/RadioExampleChecked.shorthand.tsx
  docs/src/examples/components/Radio/States/RadioExampleDisabled.shorthand.tsx
  docs/src/examples/components/Radio/Types/RadioExample.shorthand.tsx
  docs/src/examples/components/Radio/Types/index.tsx
  docs/src/examples/components/Radio/index.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExampleChecked.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExampleDisabled.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/index.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupColorPickerExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupVerticalExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/index.tsx
  docs/src/examples/components/RadioGroup/index.tsx
  src/components/Button/Button.tsx
  src/components/Radio/Radio.tsx
  src/components/Radio/index.ts
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/RadioGroup/index.ts
  src/index.ts
  src/lib/accessibility/Behaviors/Radio/RadioGroupBehavior.ts
  src/lib/accessibility/Behaviors/Radio/RadioGroupItemBehavior.ts
  src/lib/accessibility/index.ts
  src/lib/accessibility/interfaces.ts
  src/lib/isFromKeyboard.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Radio/radioStyles.ts
  src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
  test/setup.ts
  test/specs/commonTests/implementsCollectionShorthandProp.tsx
  test/specs/components/Button/Button-test.tsx
  test/specs/components/Radio/Radio-test.ts
  test/specs/components/RadioGroup/RadioGroup-test.tsx
  test/specs/components/RadioGroup/RadioGroupItem-test.ts
  test/specs/lib/keyboardFocusMock.ts
Labels: RFC, ready for review

#152 docs: add theming guide
  docs/src/components/ExampleSnippet/ExampleSnippet.tsx
  docs/src/components/ExampleSnippet/index.ts
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/routes.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/QuickStart.tsx
  docs/src/views/Theming.tsx
Labels: ready for review

#248 feat(test): add test React app to verify Stardust is consumable
  .circleci/config.yml
  build/gulp/sh.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/screener.ts
  build/gulp/tasks/test-projects.tsx
  build/tsconfig.es.json
  config.ts
  gulpfile.ts
  package.json
Labels: wip

#249 fix(Divider): Matching divider Teams theme to redlines
  CHANGELOG.md
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Divider/dividerVariables.ts
Labels: ready for merge

#243 feat(theme): add font icons support for themes
  docs/src/examples/components/Icon/States/IconExampleDisabled.shorthand.tsx
  docs/src/examples/components/Icon/Types/IconExample.shorthand.tsx
  docs/src/examples/components/Icon/Usage/IconSetExample.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleSpace.shorthand.tsx
  src/components/Icon/Icon.tsx
  src/lib/renderComponent.tsx
  src/themes/teams/components/Avatar/avatarStyles.ts
  src/themes/teams/components/Button/buttonGroupStyles.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Grid/gridStyles.ts
  src/themes/teams/components/Icon/font/index.ts
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/svg/icons/call.tsx
  src/themes/teams/components/Icon/svg/icons/callControlPresentNew.tsx
  src/themes/teams/components/Icon/svg/icons/callControlStopPresentingNew.tsx
  src/themes/teams/components/Icon/svg/icons/callEnd.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideo.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideoOff.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophone.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophoneOff.tsx
  src/themes/teams/components/Icon/svg/icons/more.tsx
  src/themes/teams/components/Icon/svg/icons/teamCreate.tsx
  src/themes/teams/components/Icon/svg/icons/umbrella.tsx
  src/themes/teams/components/Icon/svg/index.ts
  src/themes/teams/components/Icon/svg/types.d.ts
  src/themes/teams/components/Image/imageStyles.ts
  src/themes/teams/components/Input/inputStyles.ts
  src/themes/teams/components/Label/labelStyles.ts
  src/themes/teams/components/List/listItemStyles.ts
  src/themes/teams/components/List/listStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
  src/themes/teams/components/Popup/popupContentStyles.ts
  src/themes/teams/components/Radio/radioStyles.ts
  src/themes/teams/components/Status/statusStyles.ts
  src/themes/teams/index.ts
  test/specs/components/Icon/Icon-test.tsx
  test/utils/testingComponents.tsx
  types/theme.d.ts
  types/utils.d.ts
Labels: ready for merge

#260 feat: themable icons
  CHANGELOG.md
  docs/src/examples/components/Icon/States/IconExampleDisabled.shorthand.tsx
  docs/src/examples/components/Icon/Types/IconExample.shorthand.tsx
  docs/src/examples/components/Icon/Usage/IconSetExample.shorthand.tsx
  docs/src/examples/components/Icon/Usage/index.tsx
  docs/src/examples/components/Icon/Variations/IconExampleSpace.shorthand.tsx
  docs/src/examples/components/Icon/index.tsx
  src/components/Icon/Icon.tsx
  src/lib/mergeThemes.ts
  src/lib/renderComponent.tsx
  src/themes/teams/components/Avatar/avatarStyles.ts
  src/themes/teams/components/Button/buttonGroupStyles.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Grid/gridStyles.ts
  src/themes/teams/components/Icon/font/index.ts
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/svg/icons/call.tsx
  src/themes/teams/components/Icon/svg/icons/callControlPresentNew.tsx
  src/themes/teams/components/Icon/svg/icons/callControlStopPresentingNew.tsx
  src/themes/teams/components/Icon/svg/icons/callEnd.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideo.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideoOff.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophone.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophoneOff.tsx
  src/themes/teams/components/Icon/svg/icons/index.ts
  src/themes/teams/components/Icon/svg/icons/more.tsx
  src/themes/teams/components/Icon/svg/icons/teamCreate.tsx
  src/themes/teams/components/Icon/svg/icons/umbrella.tsx
  src/themes/teams/components/Icon/svg/index.ts
  src/themes/teams/components/Icon/svg/types.d.ts
  src/themes/teams/components/Image/imageStyles.ts
  src/themes/teams/components/Input/inputStyles.ts
  src/themes/teams/components/Label/labelStyles.ts
  src/themes/teams/components/List/listItemStyles.ts
  src/themes/teams/components/List/listStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
  src/themes/teams/components/Popup/popupContentStyles.ts
  src/themes/teams/components/Status/statusStyles.ts
  src/themes/teams/index.ts
  test/specs/components/Icon/Icon-test.tsx
  test/utils/testingComponents.tsx
  types/theme.d.ts
  types/utils.d.ts
Labels: ready for merge

#264 fix(popup): fix licensing issue for create react context
  package.json
  yarn.lock
Labels: ready for review

#262 docs(comments): Improved docsite comments for 'variables'
  src/components/Accordion/Accordion.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Segment/Segment.tsx
  src/components/Status/Status.tsx
  src/components/Text/Text.tsx
Labels: ready for review

#268 docs: adding changelog entry for the theming guide work
  CHANGELOG.md
Labels: ready for merge

#220 feat: add Attachment component
  CHANGELOG.md
  docs/src/examples/components/Attachment/Slots/AttachmentActionExample.shorthand.tsx
  docs/src/examples/components/Attachment/Slots/AttachmentDescriptionExample.shorthand.tsx
  docs/src/examples/components/Attachment/Slots/AttachmentHeaderExample.shorthand.tsx
  docs/src/examples/components/Attachment/Slots/AttachmentIconExample.shorthand.tsx
  docs/src/examples/components/Attachment/Slots/index.tsx
  docs/src/examples/components/Attachment/Types/AttachmentExample.shorthand.tsx
  docs/src/examples/components/Attachment/Types/AttachmentProgressExample.shorthand.tsx
  docs/src/examples/components/Attachment/Types/index.tsx
  docs/src/examples/components/Attachment/Variations/AttachmentActionableExample.shorthand.tsx
  docs/src/examples/components/Attachment/Variations/index.tsx
  docs/src/examples/components/Attachment/index.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Attachment/index.ts
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Attachment/attachmentStyles.ts
  src/themes/teams/components/Attachment/attachmentVariables.ts
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/components/Attachment/Attachment-test.tsx
Labels: ready for merge

#274 docs: update theming `styles` section
  CHANGELOG.md
  docs/src/views/Theming.tsx
Labels: ready for review

#270 feat(Avatar): added image&label shorthands
  CHANGELOG.md
  docs/src/examples/components/Avatar/Variations/AvatarExampleAlt.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleImage.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleImageCustomization.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleLabel.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleSize.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleSrc.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleStatus.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleStatusCustomization.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/index.tsx
  docs/src/examples/components/Chat/Variations/ChatExampleAvatar.shorthand.tsx
  src/components/Avatar/Avatar.tsx
  src/themes/teams/components/Avatar/avatarStyles.ts
  test/specs/components/Avatar/Avatar-test.tsx
Labels: ready for merge

#252 docs: more theming examples
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/routes.tsx
  docs/src/views/Theming.tsx
  docs/src/views/ThemingExamples.tsx
Labels: ready for review

#233 feat(FocusZone): Add embed mode for FocusZone and new Chat behavior
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/index.ts
  src/lib/UIComponent.tsx
  src/lib/accessibility/Behaviors/Chat/ChatBehavior.ts
  src/lib/accessibility/Behaviors/Chat/ChatEnterEscBehavior.ts
  src/lib/accessibility/Behaviors/Chat/ChatMessageBehavior.ts
  src/lib/accessibility/Behaviors/Chat/ChatMessageEnterEscBehavior.ts
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/FocusZone.types.ts
  src/lib/accessibility/FocusZone/focusUtilities.ts
  src/lib/accessibility/interfaces.ts
  src/lib/renderComponent.tsx
  test/specs/commonTests/handlesAccessibility.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Chat/Chat-test.ts
  test/specs/components/Chat/ChatMessage-test.tsx
Labels: RFC, wip

#275 feat: remove handled props declarations
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/components/Portal/Portal.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Segment/Segment.tsx
  src/components/Status/Status.tsx
  src/components/Text/Text.tsx
  src/lib/UIComponent.tsx
  test/specs/commonTests/stylesFunction-test.tsx
Labels: RFC, ready for merge

#277 feat(Text): add "me" option to `atMention` prop
  CHANGELOG.md
  docs/src/examples/components/Text/Variations/TextExampleAtMention.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleAtMention.tsx
  src/components/Text/Text.tsx
  src/themes/teams/components/Text/textStyles.ts
  src/themes/teams/components/Text/textVariables.ts
Labels: ready for review

#214 BREAKING(Text): change font size scheme and Text size API
  CHANGELOG.md
  docs/src/examples/components/Text/Types/TextSizesExample.shorthand.tsx
  docs/src/examples/components/Text/Types/TextSizesExample.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Provider/Provider.tsx
  src/components/Text/Text.tsx
  src/lib/enums/sizes.ts
  src/lib/mergeThemes.ts
  src/lib/renderComponent.tsx
  src/themes/teams/components/Attachment/attachmentVariables.ts
  src/themes/teams/components/Input/inputVariables.ts
  src/themes/teams/components/List/listItemVariables.ts
  src/themes/teams/components/Text/textStyles.ts
  src/themes/teams/components/Text/textVariables.ts
  src/themes/teams/siteVariables.ts
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/lib/mergeThemes/mergeSiteVariables-test.ts
  types/theme.d.ts
Labels: ready for review
