Repository microsoft/fluent-ui-react, pull requests merged in 2018-12, with the labels that each got.

#528 fix(content): fixing the type of the content prop in all components
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Animation/Animation.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Form/Form.tsx
  src/components/Form/FormField.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/components/Portal/Portal.tsx
  src/components/Portal/PortalInner.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Ref/Ref.tsx
  src/components/Segment/Segment.tsx
  src/components/Slot/Slot.tsx
  src/components/Status/Status.tsx
  src/components/Text/Text.tsx
  src/components/Tree/Tree.tsx
  src/components/Tree/TreeItem.tsx
  src/components/Tree/TreeTitle.tsx
  src/index.ts
  src/lib/commonPropInterfaces.ts
  src/lib/commonPropTypes.ts
  src/lib/customPropTypes.tsx
  src/lib/index.ts
Labels: ready for merge

#544 feat: add SVG icons set
  CHANGELOG.md
  src/themes/teams/components/Icon/font/index.ts
  src/themes/teams/components/Icon/svg/icons/addParticipant.tsx
  src/themes/teams/components/Icon/svg/icons/bookmark.tsx
  src/themes/teams/components/Icon/svg/icons/bullets.tsx
  src/themes/teams/components/Icon/svg/icons/calendar.tsx
  src/themes/teams/components/Icon/svg/icons/callControlPresentNew.tsx
  src/themes/teams/components/Icon/svg/icons/callControlStopPresentingNew.tsx
  src/themes/teams/components/Icon/svg/icons/callEnd.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideoOff.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophone.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophoneOff.tsx
  src/themes/teams/components/Icon/svg/icons/callVideo.tsx
  src/themes/teams/components/Icon/svg/icons/callVideoOff.tsx
  src/themes/teams/components/Icon/svg/icons/edit.tsx
  src/themes/teams/components/Icon/svg/icons/error.tsx
  src/themes/teams/components/Icon/svg/icons/index.ts
  src/themes/teams/components/Icon/svg/icons/leave.tsx
  src/themes/teams/components/Icon/svg/icons/like.tsx
  src/themes/teams/components/Icon/svg/icons/markAsUnread.tsx
  src/themes/teams/components/Icon/svg/icons/mention.tsx
  src/themes/teams/components/Icon/svg/icons/menu.tsx
  src/themes/teams/components/Icon/svg/icons/mic.tsx
  src/themes/teams/components/Icon/svg/icons/micOff.tsx
  src/themes/teams/components/Icon/svg/icons/participantRemove.tsx
  src/themes/teams/components/Icon/svg/icons/redbang.tsx
  src/themes/teams/components/Icon/svg/icons/reply.tsx
  src/themes/teams/components/Icon/svg/icons/retry.tsx
  src/themes/teams/components/Icon/svg/icons/send.tsx
  src/themes/teams/components/Icon/svg/icons/teams.tsx
  src/themes/teams/components/Icon/svg/icons/translation.tsx
  src/themes/teams/components/Icon/svg/icons/trashCan.tsx
  src/themes/teams/components/Icon/svg/icons/umbrella.tsx
Labels: ready for review

#552 fix(Icon): updating some incorrect Teams theme icons
  CHANGELOG.md
  src/themes/teams/components/Icon/svg/icons/add.tsx
  src/themes/teams/components/Icon/svg/icons/callControlPresentNew.tsx
  src/themes/teams/components/Icon/svg/icons/callControlStopPresentingNew.tsx
  src/themes/teams/components/Icon/svg/icons/callEnd.tsx
  src/themes/teams/components/Icon/svg/icons/gallery.tsx
  src/themes/teams/components/Icon/svg/icons/leave.tsx
  src/themes/teams/components/Icon/svg/icons/like.tsx
  src/themes/teams/components/Icon/svg/icons/mic.tsx
  src/themes/teams/components/Icon/svg/icons/micOff.tsx
  src/themes/teams/components/Icon/svg/icons/retry.tsx
  src/themes/teams/components/Icon/svg/icons/translation.tsx
Labels: ready for review

#555 fix(Editor): fix broken HTML preview when Provider.Consumer was used
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  package.json
  yarn.lock
Labels: fix, ready for review

#451 feat(Theming): add color palette
  CHANGELOG.md
  docs/src/components/ColorBox.tsx
  docs/src/components/ColorVariants.tsx
  docs/src/components/CopyToClipboard.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Divider/Variations/DividerExampleColor.shorthand.tsx
  docs/src/examples/components/Divider/Variations/index.tsx
  docs/src/routes.tsx
  docs/src/views/ColorPalette.tsx
  package.json
  src/components/Divider/Divider.tsx
  src/lib/colorUtils.ts
  src/lib/commonPropInterfaces.ts
  src/lib/commonPropTypes.ts
  src/lib/index.ts
  src/lib/renderComponent.tsx
  src/themes/default/.gitkeep
  src/themes/default/colors.ts
  src/themes/default/index.ts
  src/themes/default/siteVariables.ts
  src/themes/index.ts
  src/themes/teams/colors.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Divider/dividerVariables.ts
  src/themes/teams/siteVariables.ts
  src/themes/types.ts
  types/utils.d.ts
  yarn.lock
Labels: RFC, ready for review

#491 feat(Ref): support of `forwardRef()` API
  CHANGELOG.md
  docs/src/examples/components/Ref/Types/RefExample.tsx
  docs/src/examples/components/Ref/Types/RefForwardingExample.tsx
  docs/src/examples/components/Ref/Types/index.tsx
  package.json
  src/components/Ref/Ref.tsx
  src/components/Ref/RefFindNode.tsx
  src/components/Ref/RefForward.tsx
  test/specs/components/Ref/Ref-test.tsx
  test/specs/components/Ref/RefFindNode-test.tsx
  test/specs/components/Ref/RefForward-test.tsx
  test/specs/components/Ref/fixtures.tsx
  yarn.lock
Labels: enhancement, ready for review

#559 fix(Provider): staticStyles should be executed with the merged siteVariables
  CHANGELOG.md
  src/components/Provider/Provider.tsx
  test/specs/components/Provider/Provider-test.tsx
Labels: ready for review

#558 refactor(Divider): remove `type` prop
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatExample.tsx
  docs/src/examples/components/Divider/Types/DividerExamplePrimary.shorthand.tsx
  docs/src/examples/components/Divider/Types/DividerExamplePrimary.tsx
  docs/src/examples/components/Divider/Types/DividerExampleSecondary.shorthand.tsx
  docs/src/examples/components/Divider/Types/DividerExampleSecondary.tsx
  docs/src/examples/components/Divider/Types/index.tsx
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  docs/src/views/Theming.tsx
  docs/src/views/ThemingExamples.tsx
  src/components/Divider/Divider.tsx
  src/themes/teams-dark/components/Divider/dividerVariables.ts
  src/themes/teams-high-contrast/components/Divider/dividerVariables.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Divider/dividerVariables.ts
Labels: ready for review

#524 docs(Prototype): Chat messages with reactions popover prototype
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/chatMessageWithPopover/ChatMessageWithPopover.tsx
  docs/src/prototypes/chatMessageWithPopover/ChatWithPopover.tsx
  docs/src/prototypes/chatMessageWithPopover/Popover.tsx
  docs/src/prototypes/chatMessageWithPopover/index.tsx
  docs/src/routes.tsx
Labels: ready for review

#371 fix: refactor approach for px-to-rem conversions
  CHANGELOG.md
  docs/src/app.tsx
  docs/src/index.ejs
  src/lib/fontSizeUtility.ts
  src/lib/index.ts
  src/themes/teams-high-contrast/components/Input/inputVariables.ts
  src/themes/teams/components/Attachment/attachmentStyles.ts
  src/themes/teams/components/Avatar/avatarStyles.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Chat/chatStyles.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Divider/dividerVariables.ts
  src/themes/teams/components/Form/formFieldStyles.ts
  src/themes/teams/components/Form/formStyles.ts
  src/themes/teams/components/Header/headerDescriptionStyles.ts
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/iconVariables.ts
  src/themes/teams/components/Image/imageStyles.ts
  src/themes/teams/components/Image/imageVariables.ts
  src/themes/teams/components/Input/inputVariables.ts
  src/themes/teams/components/ItemLayout/itemLayoutVariables.ts
  src/themes/teams/components/Label/labelStyles.ts
  src/themes/teams/components/Label/labelVariables.ts
  src/themes/teams/components/List/listItemStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
  src/themes/teams/components/Menu/menuVariables.ts
  src/themes/teams/components/Popup/popupContentStyles.ts
  src/themes/teams/components/Popup/popupContentVariables.ts
  src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
  src/themes/teams/components/Status/statusStyles.ts
  src/themes/teams/components/Tree/treeItemStyles.ts
  src/themes/teams/components/Tree/treeStyles.ts
  src/themes/teams/components/Tree/treeTitleStyles.ts
  src/themes/teams/siteVariables.ts
  src/themes/teams/staticStyles/globalStyles.ts
  src/themes/teams/utils/index.ts
  test/specs/lib/fontSizeUtility-test.ts
Labels: needs author feedback

#569 fix(Icon): color and borderColor should inherit the color, or be changed via the variables
  CHANGELOG.md
  docs/src/examples/components/Icon/Variations/IconExampleColor.shorthand.tsx
  docs/src/examples/components/Icon/Variations/index.tsx
  docs/src/prototypes/popups/GridImagePicker/GridImagePickerItem.tsx
  src/lib/accessibility/Behaviors/Dialog/dialogBehavior.ts
  src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
  src/lib/isFromKeyboard.ts
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/svg/ProcessedIcons/index-new.ts
  src/themes/teams/components/Icon/svg/ProcessedIcons/index.ts
  src/themes/teams/components/Icon/svg/icons/translation.tsx
  test/specs/behaviors/behavior-test.tsx
  test/specs/components/Popup/Popup-test.tsx
  test/specs/components/Portal/Portal-test.tsx
Labels: ready for review

#578 fix(Popup): Do not focus trigger on outside click
  CHANGELOG.md
  src/components/Popup/Popup.tsx
Labels: ready for review

#571 fix(docs): EDGE could not open the docs
  CHANGELOG.md
  docs/src/index.ejs
Labels: needs author feedback

#573 fix(lib): correctly handle arrays in felaSanitizeCssPlugin
  CHANGELOG.md
  src/lib/felaSanitizeCssPlugin.ts
  test/specs/lib/felaSanitizeCssPlugin-test.ts
Labels: ready for merge

#510 docs(Accessibility): Display available behaviors for component
  CHANGELOG.md
  build/gulp/plugins/util/getComponentInfo.ts
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  src/components/Grid/Grid.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
Labels: ready for merge

#579 fix(docs): component styles in RTL mode
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: fix, ready for review

#422 Feat/multi dropdown component
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultipleSearch.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/index.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchFluid.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchImageAndContent.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchToggleButton.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/index.tsx
  docs/src/examples/components/Dropdown/index.tsx
  docs/src/examples/components/Input/Variations/InputExampleInputSlot.shorthand.tsx
  package.json
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownItem.tsx
  src/components/Dropdown/DropdownLabel.tsx
  src/components/Dropdown/DropdownSearchInput.tsx
  src/components/Input/Input.tsx
  src/components/Label/Label.tsx
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Dropdown/dropdownItemStyles.ts
  src/themes/teams/components/Dropdown/dropdownSearchInputStyles.ts
  src/themes/teams/components/Dropdown/dropdownStyles.ts
  src/themes/teams/components/Dropdown/dropdownVariables.ts
  src/themes/types.ts
  test/specs/components/Dropdown/Dropdown-test.tsx
  yarn.lock
Labels: ready for review

#583 refactor(lib): remove `createColorVariants` and `setColorLightness` utils
  CHANGELOG.md
  package.json
  src/lib/colorUtils.ts
  src/lib/index.ts
  src/themes/default/colors.ts
Labels: ready for review

#496 fix(factories): shorthand fix for applying props to react element
  CHANGELOG.md
  docs/src/examples/components/Input/Variations/InputExampleInputSlot.shorthand.tsx
  docs/src/examples/components/Input/Variations/InputExampleWrapperSlot.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExampleChecked.shorthand.tsx
  docs/src/examples/components/RadioGroup/Item/RadioGroupItemExampleDisabled.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupColorPickerExample.shorthand.tsx
  src/components/Input/Input.tsx
  src/lib/factories.tsx
  test/specs/commonTests/implementsWrapperProp.tsx
  test/specs/components/RadioGroup/RadioGroup-test.tsx
  test/specs/lib/factories-test.tsx
Labels: architecture, needs author feedback, ready for merge

#570 chore(mixed): fix imports and introduce bundler test
  .circleci/config.yml
  CHANGELOG.md
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-projects/rollup/app.js
  build/gulp/tasks/test-projects/rollup/rollup.config.js
  docs/src/prototypes/chatMessageWithPopover/ChatMessageWithPopover.tsx
  docs/src/prototypes/chatMessageWithPopover/Popover.tsx
  docs/src/views/IntegrateCustomComponents.tsx
  package.json
  src/components/Avatar/Avatar.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/Portal/PortalInner.tsx
  src/components/Ref/RefFindNode.tsx
  src/components/Status/Status.tsx
  src/components/Tree/TreeItem.tsx
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/commonPropTypes.ts
  src/lib/createAnimationStyles.tsx
  src/lib/factories.tsx
  src/lib/renderComponent.tsx
  types/classnames/index.d.ts
  yarn.lock
Labels: fix, ready for merge

#590 fix(Dropdown): use pxToRem from Teams theme
  CHANGELOG.md
  src/themes/teams/components/Dropdown/dropdownVariables.ts
Labels: fix, ready for merge

#592 fix(Popup): restore ability to render popup from React element
  CHANGELOG.md
  src/components/Popup/Popup.tsx
Labels: fix, ready for merge

#563 feat(FocusZone): Handle keyDownCapture based on client needs
  CHANGELOG.md
  src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/FocusZone.types.ts
Labels: ready for merge

#595 fix(getKeyDownHandler): Pass props to client's "onKeyDown" handler
  CHANGELOG.md
  src/lib/getKeyDownHandlers.ts
Labels: fix, ready for review

#599 docs: fix duplicated className in instructions
  CHANGELOG.md
  docs/src/prototypes/chatMessageWithPopover/Popover.tsx
  docs/src/views/IntegrateCustomComponents.tsx
Labels: docs

#602 fix(docs): fix key warnings
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  docs/src/routes.tsx
Labels: fix, ready for review

#603 perf(docgen): speed up `build:docs:component-menu`
  build/gulp/plugins/gulp-component-menu.ts
  build/gulp/tasks/docs.ts
Labels: perf, ready for review

#596 fix(Menu): correctly handle `isFromKeyboard`
  CHANGELOG.md
  build/gulp/tasks/test-projects/rollup/rollup.config.js
  package.json
  src/components/Button/Button.tsx
  src/components/Menu/MenuItem.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/lib/index.ts
  src/lib/isFromKeyboard.ts
  src/lib/typescriptUtils.ts
  src/lib/whatInput.ts
  test/setup.common.ts
  test/specs/lib/keyboardFocusMock.ts
  yarn.lock
Labels: fix, ready for merge

#556 feat(chat): chat item gutter and refactoring
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatExample.tsx
  docs/src/examples/components/Chat/Types/ChatExampleGutterPosition.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.tsx
  docs/src/examples/components/Chat/Types/index.tsx
  docs/src/prototypes/AsyncShorthand/AsyncShorthand.tsx
  docs/src/prototypes/chatPane/chatPaneContent.tsx
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Chat/chatItemStyles.ts
  src/themes/teams/components/Chat/chatItemVariables.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Chat/chatMessageVariables.ts
  src/themes/teams/components/Chat/chatStyles.ts
  test/specs/components/Chat/Chat-test.ts
  test/specs/components/Chat/ChatItem-test.tsx
  test/specs/components/Chat/ChatMessage-test.tsx
Labels: ready for review

#591 fix: names of mapped props for shorthand factories
  CHANGELOG.md
  src/components/Image/Image.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/List/ListItem.tsx
  src/lib/factories.tsx
  test/specs/commonTests/implementsCollectionShorthandProp.tsx
  test/specs/commonTests/implementsShorthandProp.tsx
  test/specs/components/List/List-test.ts
  test/specs/components/RadioGroup/RadioGroup-test.tsx
  test/specs/lib/factories-test.tsx
  types/utils.d.ts
Labels: fix, ready for merge

#606 feat(Popup): add 'offset' prop
  CHANGELOG.md
  docs/src/examples/components/Popup/Variations/PopupExampleOffset.shorthand.tsx
  docs/src/examples/components/Popup/Variations/index.tsx
  src/components/Popup/Popup.tsx
Labels: ready for merge

#609 docs(accordion): remove list from accordion example
  docs/src/examples/components/Accordion/Variations/AccordionExampleList.shorthand.tsx
Labels: ready for merge

#608 chore(CI): reenable `test:projects:cra-ts`
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-projects/cra/App.tsx
Labels: ready for merge

#623 fix(Prototype): Fix Popover prototype after breaking changes
  docs/src/prototypes/chatMessageWithPopover/ChatMessageWithPopover.tsx
  docs/src/prototypes/chatMessageWithPopover/ChatWithPopover.tsx
Labels: fix, ready for review

#621 chore: cache results of vulnerability scans
  .circleci/config.yml
  build/gulp/tasks/test-vulns.ts
  gulpfile.ts
  package.json
Labels: ready for merge

#597 feat(text): color prop
  CHANGELOG.md
  docs/src/examples/components/Text/Variations/TextExampleColor.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleColor.tsx
  docs/src/examples/components/Text/Variations/index.tsx
  src/components/Text/Text.tsx
  src/lib/colorUtils.ts
  src/lib/index.ts
  src/themes/teams/colors.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Divider/dividerVariables.ts
  src/themes/teams/components/Text/textStyles.ts
  src/themes/teams/components/Text/textVariables.ts
  src/themes/types.ts
Labels: ready for review

#628 feat(header): header and header description color prop
  CHANGELOG.md
  docs/src/examples/components/Header/Variations/HeaderExampleColor.shorthand.tsx
  docs/src/examples/components/Header/Variations/HeaderExampleColor.tsx
  docs/src/examples/components/Header/Variations/index.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/themes/teams/components/Header/headerDescriptionStyles.ts
  src/themes/teams/components/Header/headerDescriptionVariables.ts
  src/themes/teams/components/Header/headerStyles.ts
  src/themes/teams/components/Header/headerVariables.ts
Labels: ready for review

#612 fix(Popup): allow to 'detach' from trigger and RTL adjustments
  CHANGELOG.md
  docs/src/examples/components/Popup/Variations/PopupExampleOffset.shorthand.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/positioningHelper.ts
  test/specs/components/Popup/Popup-test.tsx
Labels: ready for merge

#617 docs(Examples): allow to use TS in examples
  .gitignore
  build/babel/transform-star-import-plugin.ts
  build/babel/types.ts
  build/gulp/plugins/gulp-example-source.ts
  build/gulp/plugins/util/getRelativePathToSourceFile.ts
  build/gulp/plugins/util/index.ts
  build/gulp/tasks/docs.ts
  docs/src/components/ComponentDoc/ComponentExample/SourceCodeManager.ts
  docs/src/examples/components/Ref/Types/RefExample.tsx
  docs/src/examples/components/Ref/Types/RefForwardingExample.tsx
  docs/src/examples/components/Text/States/TextExampleDisabled.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleDisabled.tsx
  docs/src/examples/components/Text/States/TextExampleError.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleError.tsx
  docs/src/examples/components/Text/States/TextExampleSuccess.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleSuccess.tsx
  docs/src/examples/components/Text/States/TextExampleTemporary.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleTemporary.tsx
  docs/src/examples/components/Text/States/TextExampleTruncated.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleTruncated.tsx
  docs/src/examples/components/Text/States/index.tsx
  docs/src/examples/components/Text/Types/TextSizesExample.shorthand.tsx
  docs/src/examples/components/Text/Types/TextSizesExample.tsx
  docs/src/examples/components/Text/Types/TextWeightsExample.shorthand.tsx
  docs/src/examples/components/Text/Types/TextWeightsExample.tsx
  docs/src/examples/components/Text/Types/index.tsx
  docs/src/examples/components/Text/Variations/TextExampleAtMention.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleAtMention.tsx
  docs/src/examples/components/Text/Variations/TextExampleImportant.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleImportant.tsx
  docs/src/examples/components/Text/Variations/TextExampleTimestamp.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleTimestamp.tsx
  docs/src/examples/components/Text/Variations/index.tsx
  docs/src/examples/components/Text/index.tsx
  docs/src/types.ts
  package.json
  yarn.lock
Labels: ready for review

#639 feat(icon): Add and export new icons for compose
  CHANGELOG.md
  src/themes/teams/components/Icon/svg/ProcessedIcons/icons-horizontal-rule.tsx
  src/themes/teams/components/Icon/svg/ProcessedIcons/icons-indent.tsx
  src/themes/teams/components/Icon/svg/ProcessedIcons/icons-outdent.tsx
  src/themes/teams/components/Icon/svg/ProcessedIcons/icons-redo.tsx
  src/themes/teams/components/Icon/svg/ProcessedIcons/icons-remove-format.tsx
  src/themes/teams/components/Icon/svg/ProcessedIcons/icons-strike.tsx
  src/themes/teams/components/Icon/svg/ProcessedIcons/icons-undo.tsx
  src/themes/teams/components/Icon/svg/ProcessedIcons/index-new.ts
  src/themes/teams/components/Icon/svg/ProcessedIcons/index.ts
  src/themes/teams/components/Icon/svg/icons/horizontalRule.tsx
  src/themes/teams/components/Icon/svg/icons/indent.tsx
  src/themes/teams/components/Icon/svg/icons/index.ts
  src/themes/teams/components/Icon/svg/icons/outdent.tsx
  src/themes/teams/components/Icon/svg/icons/redo.tsx
  src/themes/teams/components/Icon/svg/icons/removeFormat.tsx
  src/themes/teams/components/Icon/svg/icons/strike.tsx
  src/themes/teams/components/Icon/svg/icons/undo.tsx
Labels: ready for merge

#646 feat(FocusZone): Enable RTL
  CHANGELOG.md
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/renderComponent.tsx
  test/specs/lib/FocusZone-test.tsx
Labels: enhancement, ready for review

#637 fix(FocusZone): Respect defaultTabbable element when FocusZone container gets focus
  CHANGELOG.md
  src/lib/accessibility/Behaviors/Menu/menuBehavior.ts
  src/lib/accessibility/Behaviors/Tab/tabListBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/toolbarBehavior.ts
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/FocusZone.types.ts
  test/specs/lib/FocusZone-test.tsx
Labels: ready for review

#658 fix(Menu): Fix breaking change after merging PR
  src/lib/accessibility/Behaviors/Menu/submenuBehavior.ts
Labels: fix, ready for review

#279 feat(list): enter and spacebar keyboard handling for List and Listitem
  src/lib/accessibility/Behaviors/List/selectableListBehavior.ts
  src/lib/accessibility/Behaviors/List/selectableListItemBehavior.ts
  test/specs/components/List/ListItem-test.ts
  test/specs/components/List/ListItem-test.tsx
Labels: ready for review

#632 feat(segment): color prop
  CHANGELOG.md
  docs/src/examples/components/Segment/Variations/SegmentExampleColor.shorthand.tsx
  docs/src/examples/components/Segment/Variations/SegmentExampleColor.tsx
  docs/src/examples/components/Segment/Variations/SegmentExampleInverted.shorthand.tsx
  docs/src/examples/components/Segment/Variations/SegmentExampleInverted.tsx
  docs/src/examples/components/Segment/Variations/index.tsx
  src/themes/teams/components/Segment/segmentStyles.ts
  src/themes/teams/components/Segment/segmentVariables.ts
Labels: ready for merge

#659 fix(Popup): defaultOpen prop
  CHANGELOG.md
  src/components/Popup/Popup.tsx
Labels: ready for merge

#652 fix(Chat): Adding dark and contrast theme files for Chat
  CHANGELOG.md
  src/themes/teams-dark/componentVariables.ts
  src/themes/teams-dark/components/Chat/chatMessageVariables.ts
  src/themes/teams-dark/components/Chat/chatVariables.ts
  src/themes/teams-high-contrast/componentVariables.ts
  src/themes/teams-high-contrast/components/Chat/chatMessageVariables.ts
  src/themes/teams-high-contrast/components/Chat/chatVariables.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: ready for merge

#640 fix(icon): update size values in Icon
  CHANGELOG.md
  docs/src/examples/components/Icon/Variations/IconExampleSize.shorthand.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsLogo.tsx
  docs/src/views/ThemingExamples.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Icon/Icon.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Status/Status.tsx
  src/themes/teams/components/Icon/iconStyles.ts
Labels: ready for merge

#97 chore: bundle size statistics
  .circleci/config.yml
  .gitignore
  .prettierignore
  build/gulp/tasks/dist.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/stats.ts
  build/gulp/tasks/test-projects/rollup/rollup.config.js
  build/gulp/tasks/test-unit.ts
  build/webpack.config.stats.ts
  docs/src/bundleStats.json
  gulpfile.ts
  package.json
  src/themes/fabric/index.ts
  test/jest.config.common.js
  test/jest.config.strict.js
  yarn.lock
Labels: ready for review

#651 feat(icon): color prop
  CHANGELOG.md
  docs/src/examples/components/Icon/Variations/IconExampleColor.shorthand.tsx
  src/components/Icon/Icon.tsx
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/iconVariables.ts
Labels: ready for merge
