Repository microsoft/fluent-ui-react, pull requests merged in 2018-11, with the labels that each got.

#381 fix(Button): Implementing Contrast Theme and Updating Dark Theme
  CHANGELOG.md
  src/themes/teams-dark/components/Button/buttonVariables.ts
  src/themes/teams-high-contrast/componentVariables.ts
  src/themes/teams-high-contrast/components/Button/buttonVariables.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
Labels: ready for merge, redlines

#428 docs: add search page prototype
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/SearchPage/SearchPage.tsx
  docs/src/prototypes/SearchPage/index.ts
  docs/src/routes.tsx
Labels: ready for merge

#400 test: component description conformance test
  build/gulp/tasks/test-unit.ts
  gulpfile.ts
  package.json
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Segment/Segment.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/components/RadioGroup/RadioGroup-test.tsx
  test/specs/components/RadioGroup/RadioGroupItem-test.ts
Labels: docs, ready for merge

#398 feat(Accessibility): Make Grid keyboard navigable by adding Grid Behavior
  docs/src/examples/components/Grid/Variations/GridExampleKeyboardNavigable.shorthand.tsx
  docs/src/examples/components/Grid/Variations/GridExampleKeyboardNavigable.tsx
  docs/src/examples/components/Grid/Variations/index.tsx
  src/components/Grid/Grid.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Grid/gridBehavior.ts
  src/lib/accessibility/index.ts
  test/specs/behaviors/behavior-test.tsx
  test/specs/behaviors/testDefinitions.ts
Labels: enhancement, ready for review

#429 breaking(Menu): replace `type` with `primary`/`secondary`
  CHANGELOG.md
  docs/src/examples/components/Menu/Types/MenuExamplePrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyPrimaryInverted.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyVerticalPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimaryVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingStartPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleTabList.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlinedPrimary.shorthand.tsx
  docs/src/views/Accessibility.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
  src/themes/teams/components/Menu/menuVariables.ts
Labels: ready for merge

#432 docs(Glossary): remove the `type` prop
  CHANGELOG.md
  docs/src/views/Glossary.tsx
Labels: docs, ready for review

#439 docs: remove glossary
  .github/PULL_REQUEST_TEMPLATE.md
  .github/add-a-feature.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/routes.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/Glossary.tsx
  docs/src/views/QuickStart.tsx
Labels: docs

#435 feat(FocusZone): Set the ref of the Focus Zone in Embed mode
  CHANGELOG.md
  src/lib/renderComponent.tsx
Labels: ready for review

#437 chore: add yarn engines entry
  package.json
Labels: ready for merge

#446 fix(Types): remove Sizes and Weights enums, use typed string in Text instead
  CHANGELOG.md
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/employeeCard/EmployeeCard.tsx
  src/components/Text/Text.tsx
  src/lib/enums/index.ts
  src/lib/enums/sizes.ts
  src/lib/enums/weights.ts
  src/themes/teams/components/Text/textStyles.ts
Labels: fix, ready for merge

#361 fix: updating input colors for dark theme
  src/themes/teams-dark/componentVariables.ts
  src/themes/teams-dark/components/Input/inputVariables.ts
  src/themes/teams-high-contrast/componentVariables.ts
  src/themes/teams-high-contrast/components/Input/inputVariables.ts
  src/themes/teams/components/Input/inputStyles.ts
  src/themes/teams/components/Input/inputVariables.ts
Labels: ready for merge, redlines

#444 chore(lib|tests): remove dead code
  src/lib/classNameBuilders.tsx
  src/lib/getDisplayName.tsx
  src/lib/index.ts
  src/lib/numberToWord.tsx
  test/.gitignore
  test/specs/commonTests/classNameHelpers.tsx
  test/specs/commonTests/hasUIClassName.tsx
  test/specs/commonTests/implementsClassNameProps.ts
  test/specs/commonTests/implementsCreateMethod.tsx
  test/specs/commonTests/implementsShorthandProp-SUI.tsx
  test/specs/commonTests/index.ts
  test/specs/commonTests/rendersChildren.tsx
  test/utils/assertBodyClasses.ts
  test/utils/assertWithTimeout.ts
  test/utils/index.ts
Labels: ready for review

#443 feat(Chat): Set default chatBehavior which uses Enter/Esc keys
  CHANGELOG.md
  src/index.ts
  src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  src/lib/accessibility/Behaviors/Chat/chatEnterEscBehavior.ts
  src/lib/accessibility/Behaviors/Chat/chatMessageEnterEscBehavior.ts
  src/lib/accessibility/index.ts
Labels: ready for merge

#410 feat(Popup): close popup on click
  CHANGELOG.md
  docs/src/components/Editor/Editor.tsx
  docs/src/examples/components/Popup/Types/PopupContentWrapperExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupContentWrapperExample.tsx
  docs/src/examples/components/Popup/Types/PopupCustomTargetExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupCustomTargetExample.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.shorthand.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.tsx
  src/components/Popup/Popup.tsx
  src/components/Portal/Portal.tsx
  src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  src/lib/eventStack/eventStack.tsx
  src/lib/eventStack/index.ts
  src/lib/index.ts
  test/specs/lib/eventStack/eventStack-test.ts
Labels: ready for merge

#413 fix(List): focus behavior
  CHANGELOG.md
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/lib/accessibility/FocusHandling/FocusContainer.ts
  src/lib/accessibility/FocusHandling/FocusableItem.ts
  src/lib/getKeyDownHandlers.ts
  test/specs/lib/accessibility/FocusContainer-test.ts
  test/specs/lib/accessibility/FocusableItem-test.ts
Labels: fix, ready for merge

#450 fix(FocusZone): Fix "defaultTabbableElement" prop
  src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/FocusZone.types.ts
  src/lib/accessibility/FocusZone/index.ts
Labels: fix

#442 feat(Input): add iconPosition property
  CHANGELOG.md
  docs/src/examples/components/Input/Variations/InputExampleIconPosition.shorthand.tsx
  docs/src/examples/components/Input/Variations/index.tsx
  src/components/Input/Input.tsx
  src/themes/teams/components/Input/inputStyles.ts
  src/themes/teams/components/Input/inputVariables.ts
Labels: ready for review

#452 chore(package): correct peer dependencies
  CHANGELOG.md
  package.json
Labels: ready for review

#389 feat(segment): add inverted prop and improved styles
  CHANGELOG.md
  docs/src/examples/components/Segment/Variations/SegmentExampleInverted.shorthand.tsx
  docs/src/examples/components/Segment/Variations/SegmentExampleInverted.tsx
  docs/src/examples/components/Segment/Variations/index.tsx
  docs/src/examples/components/Segment/index.tsx
  src/components/Segment/Segment.tsx
  src/themes/teams/components/Segment/segmentStyles.ts
  src/themes/teams/components/Segment/segmentVariables.ts
Labels: ready for merge

#427 fix(Header): Adding dark and contrast styles for Header
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  src/themes/teams-dark/componentVariables.ts
  src/themes/teams-dark/components/Header/headerVariables.ts
  src/themes/teams-high-contrast/componentVariables.ts
  src/themes/teams-high-contrast/components/Header/headerVariables.ts
  src/themes/teams/components/Header/headerDescriptionVariables.ts
  src/themes/teams/components/Header/headerVariables.ts
Labels: ready for review, redlines

#465 Add focus trap props to Popup behavior
  docs/src/examples/components/Popup/Types/PopupFocusTrapExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupNoFocusTrapExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  src/components/Popup/Popup.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
  src/lib/accessibility/index.ts
  src/lib/accessibility/types.ts
  test/specs/behaviors/behavior-test.tsx
  test/specs/behaviors/testDefinitions.ts
Labels: wip

#470 fix(factories): styles defined as func are not working
  CHANGELOG.md
  src/lib/factories.tsx
  src/lib/mergeThemes.ts
  test/specs/lib/factories-test.tsx
  test/specs/lib/mergeThemes/mergeThemes-test.ts
Labels: fix, needs author feedback

#462 chore: Upgrade to Webpack 4
  build/webpack.config.dll.ts
  build/webpack.config.umd.ts
  package.json
  webpack.config.ts
  yarn.lock
Labels: wip

#472 feat(components): create component implementation
  build/gulp/tasks/docs.ts
  src/components/Button/Button.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Form/FormField.tsx
  src/components/Input/Input.tsx
  src/components/Segment/Segment.tsx
  src/components/Slot/Slot.tsx
  src/lib/UIComponent.tsx
  src/lib/createComponent.tsx
  src/lib/renderComponent.tsx
  test/specs/components/Slot/Slot-test.ts
Labels: ready for review

#460 feat(utils): replace react-docgen with typescript
  CHANGELOG.md
  build/gulp/plugins/util/findExportedComponentDefinitions.ts
  build/gulp/plugins/util/getComponentInfo.ts
  build/gulp/plugins/util/index.ts
  build/gulp/plugins/util/isUIComponentClass.ts
  build/gulp/plugins/util/parserCustomHandler.ts
  docs/src/components/ComponentDoc/ComponentProp/ComponentPropFunctionSignature.tsx
  docs/src/components/ComponentDoc/ComponentTable/ComponentTableRow.tsx
  docs/src/components/DocsBehaviorRoot.tsx
  package.json
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Form/Form.tsx
  src/components/Form/FormField.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/components/Portal/Portal.tsx
  src/components/Portal/PortalInner.tsx
  src/components/Provider/ProviderConsumer.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Segment/Segment.tsx
  src/components/Slot/Slot.tsx
  src/components/Status/Status.tsx
  src/components/Text/Text.tsx
  src/lib/commonPropInterfaces.ts
  src/lib/commonPropTypes.ts
  yarn.lock
Labels: RFC, wip

#441 feat(Icon): Redlining icons
  CHANGELOG.md
  docs/src/examples/components/Avatar/Variations/AvatarExampleImageCustomization.shorthand.tsx
  docs/src/examples/components/Icon/States/IconExampleDisabled.shorthand.tsx
  docs/src/examples/components/Icon/Types/IconExample.shorthand.tsx
  docs/src/examples/components/Icon/Usage/IconSetExample.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleBordered.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleCircular.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleSize.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleSpace.shorthand.tsx
  src/components/Status/Status.tsx
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/iconVariables.ts
  src/themes/teams/components/Icon/svg/icons/call.tsx
  src/themes/teams/components/Icon/svg/icons/callControlPresentNew.tsx
  src/themes/teams/components/Icon/svg/icons/callControlStopPresentingNew.tsx
  src/themes/teams/components/Icon/svg/icons/callEnd.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideo.tsx
  src/themes/teams/components/Icon/svg/icons/callIncomingVideoOff.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophone.tsx
  src/themes/teams/components/Icon/svg/icons/callMicrophoneOff.tsx
  src/themes/teams/components/Icon/svg/icons/fontColor.tsx
  src/themes/teams/components/Icon/svg/icons/fontSize.tsx
  src/themes/teams/components/Icon/svg/icons/format.tsx
  src/themes/teams/components/Icon/svg/icons/giphy.tsx
  src/themes/teams/components/Icon/svg/icons/highlight.tsx
  src/themes/teams/components/Icon/svg/icons/more.tsx
  src/themes/teams/components/Icon/svg/icons/teamCreate.tsx
Labels: ready for review, redlines

#457 feat(Popup): add focus trap
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupFocusTrapExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  src/components/Popup/Popup.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
  src/lib/accessibility/index.ts
  src/lib/accessibility/types.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Popup/popupContentStyles.ts
  src/themes/teams/components/Popup/popupContentVariables.ts
  src/themes/teams/components/Popup/popupStyles.ts
  src/themes/teams/components/Popup/popupVariables.ts
  test/specs/behaviors/behavior-test.tsx
  test/specs/behaviors/testDefinitions.ts
Labels: ready for review

#438 fix(lodash): add types and fix errors
  CHANGELOG.md
  build/gulp/plugins/gulp-example-menu.ts
  build/gulp/plugins/util/parseDocSection.ts
  docs/src/components/ComponentDoc/ComponentProp/ComponentPropExtra.tsx
  docs/src/components/ComponentDoc/ComponentProp/ComponentPropFunctionSignature.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Text/Types/TextSizesExample.shorthand.tsx
  docs/src/examples/components/Text/Types/TextSizesExample.tsx
  docs/src/prototypes/chatPane/services/dataMock.ts
  docs/src/prototypes/chatPane/services/dateUtils.ts
  docs/src/prototypes/chatPane/services/messageFactoryMock.ts
  docs/src/utils/evalTypeScript.ts
  package.json
  src/components/Popup/Popup.tsx
  src/lib/customPropTypes.tsx
  src/lib/eventStack/EventTarget.tsx
  src/lib/mergeThemes.ts
  test/specs/components/Popup/Popup-test.tsx
  yarn.lock
Labels: ready for review

#469 feat(FocusZone): Force focus to first element when container receives focus
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/FocusZone/FocusZone.types.ts
  test/specs/lib/FocusZone-test.tsx
Labels: needs author feedback, ready for merge

#445 feat(tests): make ts-jest compile tests
  package.json
  src/components/Input/Input.tsx
  test/specs/behaviors/testHelper.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Form/FormField-test.tsx
  test/specs/components/Icon/Icon-test.tsx
  test/specs/components/Portal/Portal-test.tsx
  test/specs/components/Provider/ProviderConsumer-test.tsx
  test/specs/components/Slot/Slot-test.ts
  test/specs/lib/AutoControlledComponent-test.tsx
  test/specs/lib/customPropTypes-test.ts
  test/specs/lib/factories-test.tsx
  test/specs/lib/getKeyDownHandlers-test.ts
  test/specs/lib/keyboardHandlerFilter-test.ts
  test/specs/lib/mergeThemes/mergeComponentStyles-test.ts
  test/specs/lib/mergeThemes/mergeComponentVariables-test.ts
  test/specs/lib/mergeThemes/mergeThemes-test.ts
  yarn.lock
Labels: ready for merge

#376 feat(factories): createShorthandFactory API update and removing HTML factories
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Form/FormField.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/Icon/Icon.tsx
  src/components/Image/Image.tsx
  src/components/Input/Input.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/List/ListItem.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/PopupContent.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Segment/Segment.tsx
  src/components/Slot/Slot.tsx
  src/components/Status/Status.tsx
  src/components/Text/Text.tsx
  src/lib/createComponent.tsx
  src/lib/factories.tsx
  test/specs/components/Form/FormField-test.tsx
  test/specs/components/Input/Input-test.tsx
  test/specs/components/Slot/Slot-test.ts
  test/specs/lib/factories-test.tsx
  types/utils.d.ts
Labels: RFC, ready for review

#459 [RFC] feat(handleRef): add an util for handling passed refs
  CHANGELOG.md
  docs/src/examples/components/Ref/Types/RefExampleRef.tsx
  docs/src/examples/components/Ref/Types/index.tsx
  docs/src/examples/components/Ref/index.tsx
  src/components/Ref/Ref.tsx
  src/index.ts
  src/lib/handleRef.ts
  src/lib/index.ts
  test/specs/components/Ref/Ref-test.tsx
  test/specs/lib/handleRef-test.ts
Labels: RFC, enhancement, needs author feedback

#484 chore(package): remove docgen from `pretest`
  package.json
Labels: ready for review

#323 feat(Menu): Add wrapper prop to MenuItem
  CHANGELOG.md
  src/components/Menu/MenuItem.tsx
  src/themes/teams/components/Menu/menuItemStyles.ts
  test/specs/commonTests/handlesAccessibility.tsx
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Menu/MenuItem-test.tsx
Labels: ready for merge

#483 chore(package): bump dependencies, rearrange some of them
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  docs/src/components/DocPage/DocPage.tsx
  docs/src/components/DocsBehaviorRoot.tsx
  docs/src/examples/components/Icon/Usage/IconSetExample.shorthand.tsx
  docs/src/prototypes/chatPane/services/dateUtils.ts
  package.json
  src/components/Popup/positioningHelper.ts
  src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  src/themes/teams/components/Attachment/attachmentStyles.ts
  test/specs/commonTests/isConformant.tsx
  test/specs/components/Menu/MenuItem-test.tsx
  test/specs/components/RadioGroup/RadioGroup-test.tsx
  yarn.lock
Labels: ready for review

#414 feat(theme): support keyframes through animation property
  CHANGELOG.md
  docs/src/examples/components/Transition/Types/TransitionExample.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleDelay.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleDirection.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleDuration.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleFillMode.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleIterationCount.tsx
  docs/src/examples/components/Transition/Types/TransitionExamplePlayState.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleTimingFunction.tsx
  docs/src/examples/components/Transition/Types/index.tsx
  docs/src/examples/components/Transition/index.tsx
  src/components/Attachment/Attachment.tsx
  src/components/Provider/Provider.tsx
  src/components/Transition/Transition.tsx
  src/components/Transition/index.ts
  src/index.ts
  src/lib/commonPropInterfaces.ts
  src/lib/commonPropTypes.ts
  src/lib/createAnimationStyles.tsx
  src/lib/customPropTypes.tsx
  src/lib/index.ts
  src/lib/mergeThemes.ts
  src/lib/renderComponent.tsx
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Text/textStyles.ts
  src/themes/teams/components/Transition/transitionStyles.ts
  src/themes/teams/components/Transition/transitionVariables.ts
  src/themes/teams/index.ts
  src/themes/types.ts
  test/specs/components/Transition/Transition-test.tsx
  test/specs/lib/createAnimationStyles-test.ts
Labels: RFC

#485 build(docs): use caching for `build:docs:docgen`
  build/gulp/plugins/gulp-react-docgen.ts
  build/gulp/plugins/util/checksumUtils.ts
  build/gulp/plugins/util/getComponentInfo.ts
  build/gulp/plugins/util/index.ts
  build/gulp/tasks/docs.ts
Labels: ready for review

#487 fix(handleRef): handle `null` ref correctly
  src/lib/handleRef.ts
  test/specs/lib/handleRef-test.ts
Labels: fix, ready for review

#489 fix(List): remove listRef from API
  CHANGELOG.md
  src/components/List/List.tsx
Labels: fix, ready for review

#493 fix(docs): fix basename logic for accessibility behaviors root component
  docs/src/components/DocsBehaviorRoot.tsx
Labels: fix, ready for review

#492 chore(package): update `enzyme`
  package.json
  test/specs/components/Icon/Icon-test.tsx
  yarn.lock
Labels: ready for review

#499 fix(AutoControlledComponent): fix behaviour when undefined it passed
  CHANGELOG.md
  src/lib/AutoControlledComponent.tsx
  test/specs/lib/AutoControlledComponent-test.tsx
Labels: fix, ready for review

#503 feat(utils): add wrapper for the createComponent function
  CHANGELOG.md
  src/index.ts
  src/lib/createStardustComponent.tsx
  src/lib/index.ts
Labels: ready for review

#515 fix(Popup): Stop event propagation when press Escape on the popup
  CHANGELOG.md
  src/components/Popup/Popup.tsx
Labels: ready for merge

#480 docs(Prototype): Create prototype for Emoji / Sticker popups
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/popups/GridImagePicker/GridImagePicker.tsx
  docs/src/prototypes/popups/GridImagePicker/GridImagePickerItem.tsx
  docs/src/prototypes/popups/dataMocks.ts
  docs/src/prototypes/popups/emojiPicker.tsx
  docs/src/prototypes/popups/index.tsx
  docs/src/prototypes/popups/stickerPicker.tsx
  docs/src/routes.tsx
Labels: ready for review

#521 Fix(Popup): Trigger's props are not passed in onClick handler
  CHANGELOG.md
  src/components/Popup/Popup.tsx
Labels: ready for merge

#5 feat(Text): introduce dir attribute to support RTL
  CHANGELOG.md
  src/components/Text/Text.tsx
Labels: ready for review

#456 chore(CI): add a check for CHANGELOG by dangerjs
  .circleci/config.yml
  dangerfile.ts
  package.json
  yarn.lock
Labels: ready for review

#523 feat(Accessibility): Improvements to Menu accessibility behaviors
  CHANGELOG.md
  src/lib/accessibility/Behaviors/Menu/menuBehavior.ts
  src/lib/accessibility/Behaviors/Tab/tabListBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/toolbarBehavior.ts
  test/specs/behaviors/testDefinitions.ts
Labels: ready for review

#518 feat(chat): remove layout component and allow styling slots
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.tsx
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.tsx
  docs/src/examples/components/Chat/Types/index.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatMessage.tsx
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: help wanted, ready for review

#514 docs(ChatPane): Add attachments and link to chat pane messages in prototype
  docs/src/prototypes/chatPane/services/dataMock.ts
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  docs/src/prototypes/chatPane/services/types.ts
Labels: ready for review

#505 BREAKING(Transition): renamed Transition to Animation and added docs for the animations
  CHANGELOG.md
  docs/src/examples/components/Animation/Types/AnimationExample.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleDelay.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleDirection.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleDuration.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleFillMode.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleIterationCount.tsx
  docs/src/examples/components/Animation/Types/AnimationExamplePlayState.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleTimingFunction.tsx
  docs/src/examples/components/Animation/Types/index.tsx
  docs/src/examples/components/Animation/index.tsx
  docs/src/examples/components/Transition/Types/TransitionExample.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleDelay.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleDirection.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleDuration.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleFillMode.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleIterationCount.tsx
  docs/src/examples/components/Transition/Types/TransitionExamplePlayState.tsx
  docs/src/examples/components/Transition/Types/TransitionExampleTimingFunction.tsx
  docs/src/examples/components/Transition/Types/index.tsx
  docs/src/views/Theming.tsx
  src/components/Animation/Animation.tsx
  src/components/Transition/index.ts
  src/index.ts
  src/lib/commonPropInterfaces.ts
  src/lib/createAnimationStyles.tsx
  src/themes/teams/componentStyles.ts
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Animation/animationStyles.ts
  src/themes/teams/components/Animation/animationVariables.ts
  src/themes/teams/index.ts
  src/themes/types.ts
  test/specs/components/Animation/Animation-test.tsx
  test/specs/components/Transition/Transition-test.tsx
Labels: docs, ready for review

#531 fix: Remove engines entry
  package.json
Labels: ready for review

#529 docs(Prototype): Accessibility enhancements for for chat pane prototype
  docs/src/prototypes/chatPane/chatPaneContent.tsx
  docs/src/prototypes/chatPane/services/dataMock.ts
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
Labels: ready for merge

#530 fix(Accessibility): Remove role="presentation" from chatMessageBehavior and FocusZone
  CHANGELOG.md
  src/lib/accessibility/Behaviors/Chat/chatMessageBehavior.ts
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusZone.tsx
  src/lib/accessibility/types.ts
  test/specs/components/Chat/ChatMessage-test.tsx
Labels: ready for review

#453 chore(tests): fail tests on console output
  .circleci/config.yml
  CHANGELOG.md
  build/gulp/tasks/test-unit.ts
  jest.config.js
  package.json
  src/components/Input/Input.tsx
  test/jest.config.common.js
  test/jest.config.strict.js
  test/setup.common.ts
  test/setup.strict.ts
Labels: ready for merge

#540 docs(Label): fix examples with icon
  docs/src/examples/components/Label/Content/LabelExampleIcon.shorthand.tsx
  docs/src/examples/components/Label/Content/LabelExampleIconPosition.shorthand.tsx
Labels: ready for review

#541 fix(lib): Fix invalid whatInput import
  CHANGELOG.md
  src/lib/isFromKeyboard.ts
  test/specs/lib/keyboardFocusMock.ts
Labels: ready for merge

#527 chore(CI): add vulnerability tests (Snyk)
  .circleci/config.yml
  .snyk
  package.json
Labels: ready for review
