Repository microsoft/fluent-ui-react, pull requests merged in 2019-03, with the labels that each got.

#987 fix(Popup): Do not propagate keydown events outside Popup's content
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/test/specs/components/Popup/Popup-test.tsx
Labels: fix, ready for review

#980 chore(screener): various improvements
  .github/test-a-feature.md
  build/gulp/tasks/screener.ts
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExample.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleClearable.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultiple.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearchMultiple.shorthand.steps.ts
  screener.config.js
  types/global.d.ts
  types/screener.d.ts
Labels: ready for review

#991 fix(Icon): Emoji & settings icon update
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/ProcessedIcons/icons-emoji.tsx
  packages/react/src/themes/teams/components/Icon/svg/ProcessedIcons/icons-settings.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/emoji.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/settings.tsx
Labels: fix, ready for review, styling issue

#997 fix(test): remove hardcoded magic numbers
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Menu/MenuItem-test.tsx
  packages/react/test/utils/getDisplayName.ts
  packages/react/test/utils/index.ts
Labels: ready for review

#993 fix(Ref): update `node` if it was changed
  CHANGELOG.md
  packages/react/src/components/Ref/RefFindNode.tsx
  packages/react/test/specs/components/Ref/RefFindNode-test.tsx
Labels: fix, ready for review

#1002 feat(Icon): add `outline` prop
  CHANGELOG.md
  docs/src/examples/components/Icon/Usage/IconSetExample.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleColor.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  docs/src/prototypes/IconViewer/index.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Icon/iconVariables.ts
Labels: enhancement, ready for review

#985 fix(Popup): close previous popup on enter key
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/test/specs/components/Popup/Popup-test.tsx
Labels: fix, ready for merge

#972 fix(perf): get current commit tag in CI
  .circleci/config.yml
  build/gulp/tasks/stats.ts
Labels: ready for review

#996 chore(shorthands): allow arrays as shorthand value
  CHANGELOG.md
  docs/src/examples/components/Chat/Content/ChatExampleReactionGroup.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleWithSubmenu.shorthand.tsx
  packages/react/src/components/Accordion/AccordionContent.tsx
  packages/react/src/components/Accordion/AccordionTitle.tsx
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Avatar/Avatar.tsx
  packages/react/src/components/Box/Box.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Button/ButtonGroup.tsx
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Divider/Divider.tsx
  packages/react/src/components/Dropdown/DropdownItem.tsx
  packages/react/src/components/Dropdown/DropdownSearchInput.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/src/components/Form/FormField.tsx
  packages/react/src/components/Header/Header.tsx
  packages/react/src/components/Header/HeaderDescription.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Image/Image.tsx
  packages/react/src/components/Indicator/Indicator.tsx
  packages/react/src/components/ItemLayout/ItemLayout.tsx
  packages/react/src/components/Label/Label.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuDivider.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/components/Reaction/Reaction.tsx
  packages/react/src/components/Reaction/ReactionGroup.tsx
  packages/react/src/components/Status/Status.tsx
  packages/react/src/components/Text/Text.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/factories.ts
  packages/react/test/specs/lib/factories-test.tsx
Labels: ready for review

#1009 feat(Menu): allow to pass content to `MenuDivider`
  CHANGELOG.md
  docs/src/examples/components/Menu/Slots/MenuExampleDivider.shorthand.tsx
  docs/src/examples/components/Menu/Slots/MenuExampleDividerHorizontal.shorthand.tsx
  docs/src/examples/components/Menu/Slots/index.tsx
  docs/src/examples/components/Menu/index.tsx
  packages/react/src/components/Menu/MenuDivider.tsx
  packages/react/src/themes/teams/components/Menu/menuDividerStyles.ts
Labels: enhancement, ready for review

#1004 fix(dropdown): applied roving tabindex technique to selected dropdown items
  CHANGELOG.md
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/test/specs/components/Dropdown/DropdownSelectedItem-test.tsx
Labels: ready for review

#934 fix: (menu & menuitem): vertical menu theming updates
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuDivider.tsx
  packages/react/src/themes/teams-dark/components/Menu/menuVariables.ts
  packages/react/src/themes/teams-dark/siteVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Menu/menuItemStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/components/Menu/menuDividerStyles.ts
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
  packages/react/src/themes/teams/components/Menu/menuStyles.ts
  packages/react/src/themes/teams/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: fix, ready for review, styling issue

#1014 fix(docs): rework title in ComponentExample, fix layout
  docs/src/Style.ts
  docs/src/components/ComponentDoc/ComponentControls/ComponentButton.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleTitle.tsx
  docs/src/components/DocsLayout.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Button/index.tsx
  docs/src/examples/components/Indicator/Types/index.tsx
  packages/react/src/themes/teams/components/Segment/segmentVariables.ts
Labels: docs, ready for review

#1016 docs(Editor): improve performance and add TS support to CodeSandbox export
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox/ComponentControlsCodeSandbox.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox/createPackageJson.ts
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox/indexTemplates.ts
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentSourceManager/ComponentSourceManager.ts
  docs/src/components/Editor/Editor.tsx
  package.json
  yarn.lock
Labels: ready for review

#1019 docs(layouts): more layout fixes
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ExampleSection.tsx
  docs/src/components/DocsLayout.tsx
  docs/src/examples/components/Text/States/TextExampleTruncated.shorthand.tsx
  docs/src/examples/components/Text/States/TextExampleTruncated.tsx
Labels: ready for review

#1028 fix(Popup): Do not propagate keyboard event only when focus trap behavior is used
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/test/specs/components/Popup/Popup-test.tsx
Labels: fix, ready for review

#933 docs(menu): show disabled state for menu items in toolbar/submenu
  CHANGELOG.md
  docs/src/examples/components/Menu/Slots/MenuExampleIconOnly.shorthand.tsx
  docs/src/examples/components/Menu/Slots/MenuExampleWithIcons.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleWithSubmenu.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleFluid.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVertical.shorthand.tsx
Labels: ready for review

#994 docs(ChatMessage): prototype of message reactions with Popup
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/ChatWithPopover.tsx
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/Popover.tsx
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/index.tsx
  docs/src/prototypes/chatMessages/ImportantAndMentionMessages/index.tsx
  docs/src/prototypes/chatMessages/MessageReactionsWithPopup/ReactionPopup.tsx
  docs/src/prototypes/chatMessages/MessageReactionsWithPopup/index.tsx
  docs/src/prototypes/chatMessages/index.tsx
  docs/src/routes.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Reaction/Reaction.tsx
  packages/react/src/index.ts
  packages/react/src/themes/teams/components/Reaction/reactionStyles.ts
  packages/react/src/themes/teams/components/Reaction/reactionVariables.ts
Labels: ready for review

#1018 feat(Tree): Adding exclusive flag
  CHANGELOG.md
  docs/src/examples/components/Tree/Types/TreeExclusiveExample.shorthand.tsx
  docs/src/examples/components/Tree/Types/index.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
Labels: enhancement, ready for review

#1041 fix(Input): fix styles of focused border in Teams theme
  CHANGELOG.md
  docs/src/examples/components/Input/Types/InputExample.shorthand.steps.ts
  packages/react/src/themes/teams/components/Input/inputVariables.ts
Labels: fix, ready for review

#1032 fix(dropdown): use Portal to create a11y selection message container
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultiple.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearch.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearchMultiple.shorthand.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: fix, ready for merge

#1046 chore(package): update @types and TS
  build/gulp/tasks/test-projects/cra/App.tsx
  docs/src/examples/components/Ref/index.tsx
  package.json
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/Flex/FlexItem.tsx
  packages/react/src/components/Provider/ProviderConsumer.tsx
  packages/react/src/components/Ref/Ref.tsx
  packages/react/src/components/Ref/RefFindNode.tsx
  packages/react/src/components/Ref/RefForward.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/customPropTypes.tsx
  packages/react/test/specs/components/Ref/Ref-test.tsx
  packages/react/test/specs/lib/AutoFocusZone-test.tsx
  packages/react/test/specs/lib/FocusTrapZone-test.tsx
  packages/react/test/specs/lib/FocusZone-test.tsx
  yarn.lock
Labels: ready for review

#1042 fix(types): make *Props interface extendable
  CHANGELOG.md
  docs/src/prototypes/chatPane/composeMessage.tsx
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/Flex/Flex.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Portal/PortalInner.tsx
  packages/react/src/components/Ref/Ref.tsx
  packages/react/src/lib/commonPropInterfaces.ts
  packages/react/src/types.ts
Labels: fix, ready for review

#1044 fix(chatBehavior): Use FocusZone mode Embed instead of Wrap
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
Labels: fix, ready for review

#1043 feat(screenshot tests): add support for common themes
  .github/test-a-feature.md
  build/gulp/tasks/screener.ts
  build/screener/screener.config.js
  build/screener/screener.states.ts
  build/screener/screener.steps.ts
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/context/ThemeContext.tsx
  docs/src/examples/components/Button/Types/ButtonExample.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Rtl/DropdownExample.rtl.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExample.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleClearable.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultiple.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearchMultiple.shorthand.steps.ts
  docs/src/examples/components/Input/Types/InputExample.shorthand.steps.ts
  docs/src/examples/components/Menu/Slots/MenuExample.shorthand.steps.ts
  docs/src/examples/components/Menu/Slots/MenuExampleIconOnly.shorthand.steps.ts
  docs/src/examples/components/Menu/Slots/MenuExampleWithIcons.shorthand.steps..ts
  docs/src/examples/components/Menu/Types/MenuExamplePointing.shorthand.steps.ts
  docs/src/examples/components/Menu/Types/MenuExampleUnderlined.shorthand.steps.ts
  docs/src/examples/components/Menu/Usages/MenuExampleWithSubmenu.shorthand.steps.ts
  docs/src/examples/components/Menu/Variations/MenuExampleVertical.shorthand.steps.ts
  docs/src/examples/components/Menu/Variations/MenuExampleVerticalPointing.shorthand.steps.ts
  docs/src/examples/components/Menu/commonScreenerSteps.ts
  docs/src/examples/components/Popup/Rtl/PopupExample.rtl.steps.ts
  packages/react/src/themes/types.ts
  screener.config.js
  types/global.d.ts
  types/screener.d.ts
Labels: ready for review

#1059 fix(unit tests): fix warnings
  .circleci/config.yml
  build/gulp/tasks/test-unit.ts
  build/jest/jest.config.common.js
  build/jest/jest.config.strict.js
  jest.config.js
  packages/react-component-event-listener/jest.config.js
  packages/react/jest.config.js
  packages/react/src/themes/teams/components/Icon/svg/icons/numberList.tsx
  packages/react/src/themes/teams/components/Icon/svg/types.ts
  packages/react/test/__mocks__/popper.js.ts
Labels: fix, ready for review

#1070 fix(RadioGroup): use regular components instead of Label
  CHANGELOG.md
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
Labels: fix, ready for review

#1066 fix(Menu): Add aria posinset and setsize, hide indicator from narration
  CHANGELOG.md
  packages/react/src/components/Indicator/Indicator.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  packages/react/test/specs/components/Menu/Menu-test.tsx
Labels: fix, ready for review

#1063 feat(alert): v1
  CHANGELOG.md
  docs/src/examples/components/Alert/Rtl/AlertExample.rtl.tsx
  docs/src/examples/components/Alert/Rtl/index.tsx
  docs/src/examples/components/Alert/Types/AlertExample.shorthand.tsx
  docs/src/examples/components/Alert/Types/AlertExample.tsx
  docs/src/examples/components/Alert/Types/index.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleAction.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleAttached.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleAttached.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleDanger.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleDanger.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleInfo.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleInfo.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleSuccess.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleSuccess.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleWarning.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleWarning.tsx
  docs/src/examples/components/Alert/Variations/index.tsx
  docs/src/examples/components/Alert/index.tsx
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/components/Alert/Alert-test.tsx
  packages/react/test/specs/components/Label/Label-test.tsx
Labels: good first issue, ready for review

#1076 fix(jest): avoid test double run
  build/jest/jest.config.common.js
  packages/react/jest.config.js
Labels: fix, ready for review

#1072 fix(accessibility): apply accessibility handlers with `applyAccessibilityKeyHandlers()`
  CHANGELOG.md
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Chat/Chat.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/List/List.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/lib/applyAccessibilityKeyHandlers.ts
  packages/react/src/lib/getKeyDownHandlers.ts
  packages/react/src/lib/index.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Input/Input-test.tsx
  packages/react/test/specs/lib/getKeyDownHandlers-test.ts
Labels: fix, ready for review

#1080 fix(docs): update Babel config in docs
  docs/src/components/Playground/renderConfig.ts
Labels: fix, ready for review

#1048 fix(prototypes): fix aria attributes for Emoticon Picker prototype
  docs/src/prototypes/popups/GridImagePicker/GridImagePickerItem.tsx
Labels: ready for review

#921 chore: move `customProptypes` to a separate package
  .github/CONTRIBUTING.md
  build/gulp/tasks/test-projects.tsx
  packages/react-proptypes/jest.config.js
  packages/react-proptypes/package.json
  packages/react-proptypes/src/index.ts
  packages/react-proptypes/src/leven.ts
  packages/react-proptypes/test/customPropTypes-test.ts
  packages/react-proptypes/tsconfig.json
  packages/react/package.json
  packages/react/src/lib/accessibility/FocusZone/AutoFocusZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/src/lib/commonPropTypes.ts
  packages/react/src/lib/index.ts
Labels: ready for review

#1074 feat(Flex): replace Flex.Gap with adding margins on the elements
  CHANGELOG.md
  packages/react/src/components/Flex/Flex.tsx
  packages/react/src/components/Flex/FlexGap.tsx
  packages/react/src/themes/teams/components/Flex/flexStyles.ts
Labels: ready for review

#1090 fix(renderer): disable `devMode` for Fela by default
  CHANGELOG.md
  packages/react/src/lib/felaRenderer.tsx
Labels: fix, ready for review

#1087 fix(types): update accessibility types to match React's
  CHANGELOG.md
  docs/src/prototypes/MenuButton/menuButtonBehavior.ts
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/lib/accessibility/Behaviors/Attachment/attachmentBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Radio/radioGroupItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tab/tabBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarButtonBehavior.ts
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/src/lib/accessibility/types.ts
  packages/react/src/lib/getElementType.tsx
  packages/react/src/lib/renderComponent.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
  packages/react/test/specs/behaviors/testHelper.tsx
Labels: fix, ready for review

#966 feat(dropdown): control highlightedIndex from Dropdown
  CHANGELOG.md
  build/gulp/tasks/test-projects/rollup/rollup.config.js
  packages/react/package.json
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  yarn.lock
Labels: ready for review

#1081 feat(Box): add examples and docs
  build/gulp/tasks/docs.ts
  docs/src/examples/components/Box/Types/BoxExample.shorthand.tsx
  docs/src/examples/components/Box/Types/BoxExample.tsx
  docs/src/examples/components/Box/Types/index.tsx
  docs/src/examples/components/Box/index.tsx
  packages/react/src/components/Box/Box.tsx
Labels: docs, ready for review

#1083 feat(prototypes): banner alerts with different intents
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/alerts/AnimatedBannerAlert.tsx
  docs/src/prototypes/alerts/BannerAlerts.tsx
  docs/src/prototypes/alerts/index.tsx
  docs/src/prototypes/chatPane/chatPaneContent.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/chatPane/chatPaneLayout.tsx
  docs/src/prototypes/chatPane/chatProtoStyle.ts
  docs/src/prototypes/chatPane/composeMessage.tsx
  docs/src/prototypes/chatPane/index.tsx
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  docs/src/routes.tsx
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
Labels: ready for review

#1092 feat(Input): add `placeholderColor` variable for Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Input/inputStyles.ts
  packages/react/src/themes/teams/components/Input/inputVariables.ts
Labels: enhancement, ready for review

#949 fix(Popup): proper handling of clicks in nested Popups
  CHANGELOG.md
  docs/src/examples/components/Popup/Usage/PopupExampleNested.shorthand.tsx
  docs/src/examples/components/Popup/Usage/index.tsx
  packages/react/package.json
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/eventStack/EventTarget.tsx
  packages/react/src/lib/eventStack/eventStack.tsx
  packages/react/src/lib/eventStack/index.ts
  packages/react/src/lib/eventStack/normalizeTarget.tsx
  packages/react/src/lib/index.ts
  packages/react/test/specs/components/Popup/Popup-test.tsx
  packages/react/test/specs/lib/eventStack/EventTarget-test.ts
  packages/react/test/specs/lib/eventStack/eventStack-test.ts
  packages/react/test/specs/lib/eventStack/normalizeTarget-test.ts
Labels: fix, ready for review

#1091 docs: layout guide
  CHANGELOG.md
  docs/src/components/GuidesNavigationFooter.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Box/index.tsx
  docs/src/examples/components/Flex/index.tsx
  docs/src/examples/components/Grid/index.tsx
  docs/src/examples/components/Segment/index.tsx
  docs/src/routes.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/IntegrateCustomComponents.tsx
  docs/src/views/Layout.tsx
  docs/src/views/QuickStart.tsx
  docs/src/views/Theming.tsx
  docs/src/views/ThemingExamples.tsx
  packages/react/src/components/Box/Box.tsx
Labels: docs, ready for review

#830 fix(radio buttons): Update radio button styles
  CHANGELOG.md
  docs/src/examples/components/RadioGroup/Types/RadioGroupVerticalExample.shorthand.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/RadioGroup/radioGroupItemVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/RadioGroup/radioGroupItemVariables.ts
  packages/react/src/themes/teams-high-contrast/siteVariables.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
Labels: ready for review, redlines

#852 feat(Provider): Make Provider a UIComponent
  CHANGELOG.md
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ExternalExampleLayout.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/Provider/ProviderBox.tsx
  packages/react/src/lib/mergeThemes.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/themes/base/componentStyles.ts
  packages/react/src/themes/base/componentVariables.ts
  packages/react/src/themes/base/components/Provider/providerBoxStyles.ts
  packages/react/src/themes/base/components/Provider/providerBoxVariables.ts
  packages/react/test/specs/components/Provider/Provider-test.tsx
  packages/react/test/specs/lib/mergeThemes/mergeRTL-test.ts
  packages/react/test/specs/lib/mergeThemes/mergeThemes-test.ts
Labels: ready for review

#1104 fix(docs): fix snippets in Layout docs
  docs/src/components/ExampleSnippet/ExampleSnippet.tsx
  docs/src/views/Layout.tsx
Labels: fix, ready for review

#1105 fix(MenuItem): Item separator - replace ::before with box-shadow
  CHANGELOG.md
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
Labels: ready for review

#1098 fix(FocusZone): Update tabindexes and alignment when item is focused programatically
  packages/react/src/lib/accessibility/Behaviors/Grid/gridBehavior.ts
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/test/specs/lib/FocusZone-test.tsx
Labels: fix, ready for review

#1113 fix(List): fix `selectableFocusHoverColor` value for Teams theme
  CHANGELOG.md
  docs/src/examples/components/List/Types/ListExampleSelectable.shorthand.steps.ts
  packages/react/src/themes/teams/components/List/listItemVariables.ts
Labels: fix, ready for review

#1111 feat(alert): align styles with latest design
  CHANGELOG.md
  docs/src/prototypes/alerts/BannerAlerts.tsx
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
Labels: ready for review

#1093 feat(components): align slotClassNames property for all components
  CHANGELOG.md
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Chat/Chat.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Form/Form.tsx
  packages/react/src/components/Header/Header.tsx
  packages/react/src/components/List/List.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
Labels: ready for merge

#1097 feat(Loader): add support for SVG animations, update in Teams theme
  CHANGELOG.md
  docs/src/examples/components/Loader/Variations/LoaderExampleSize.tsx
  docs/src/prototypes/dropdowns/AsyncDropdownSearch.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Loader/loaderStyles.ts
  packages/react/src/themes/teams/components/Loader/loaderSvgDataUrl.ts
  packages/react/src/themes/teams/components/Loader/loaderVariables.ts
Labels: enhancement, ready for review

#1117 fix(List): update styles for Teams Dark and HC themes
  CHANGELOG.md
  docs/src/examples/components/List/Types/ListExampleSelectable.shorthand.steps.ts
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/List/listItemVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/List/listItemVariables.ts
  packages/react/src/themes/teams/components/List/listItemVariables.ts
Labels: fix, ready for review

#1122 fix(Doc): Re-add example anchor
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: ready for review

#1126 fix(accessibility): add missing types to `role`
  CHANGELOG.md
  packages/react/src/lib/accessibility/types.ts
Labels: fix, ready for review

#1118 fix(dropdown): fix tab selection and blur reset
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: ready for review

#1116 feat(menu): pointing && vertical menu redlining
  CHANGELOG.md
  packages/react/src/themes/teams-dark/components/Menu/menuVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Menu/menuItemStyles.ts
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
  packages/react/src/themes/teams/components/Menu/menuVariables.ts
Labels: ready for review

#1124 fix(Dropdown): close after `searchQuery` will become empty
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: fix, ready for review

#1115 fix(RTL): align text to left
  CHANGELOG.md
  docs/src/examples/components/ItemLayout/Rtl/ItemLayoutExample.rtl.tsx
  docs/src/examples/components/ItemLayout/Rtl/index.tsx
  docs/src/examples/components/ItemLayout/index.tsx
  docs/src/examples/components/Popup/Rtl/PopupExample.rtl.tsx
  packages/react/src/themes/base/components/Provider/providerBoxStyles.ts
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
Labels: ready for review

#1121 fix(Popup): styles for dark and HC Teams themes
  CHANGELOG.md
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Popup/popupContentVariables.ts
  packages/react/src/themes/teams-dark/components/Popup/popupVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Popup/popupVariables.ts
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
  packages/react/src/themes/teams/components/Popup/popupContentVariables.ts
  packages/react/src/themes/teams/components/Popup/popupStyles.ts
  packages/react/src/themes/teams/components/Popup/popupVariables.ts
Labels: fix, ready for review

#1137 fix(chatBehavior): remove role "presentation"
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  packages/react/test/specs/components/Chat/Chat-test.ts
Labels: fix, ready for review
