Repository microsoft/fluent-ui-react, pull requests merged in 2019-05, with the labels that each got.

#1261 style(eslint): enable `spaced-comment`, `@typescript-eslint/no-unused-vars`
  build/gulp/plugins/gulp-component-menu-behaviors.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/perf.ts
  build/gulp/tasks/stats.ts
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-vulns.ts
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentPropsTable/ComponentPropsRow.tsx
  docs/src/components/ComponentDoc/PerfChart/PerfDataProvider.tsx
  docs/src/components/ComponentPlayground.tsx
  docs/src/components/DocsBehaviorRoot.tsx
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/examples/components/Chat/Content/ChatExampleReactionGroupMeReacting.shorthand.tsx
  docs/src/examples/components/Provider/Types/ProviderExample.shorthand.tsx
  docs/src/prototypes/chatPane/services/dateUtils.ts
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  docs/src/prototypes/mentions/MentionsDropdown.tsx
  packages/internal-tooling/eslint/index.js
  packages/react/src/components/Avatar/Avatar.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/positioningHelper.ts
  packages/react/src/lib/accessibility/FocusHandling/FocusContainer.ts
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/src/lib/accessibility/FocusZone/focusUtilities.ts
  packages/react/src/themes/teams/components/Divider/dividerVariables.ts
  packages/react/src/themes/teams/components/Label/labelStyles.ts
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/specs/components/Input/Input-test.tsx
  packages/react/test/specs/components/Menu/MenuItem-test.tsx
  packages/react/test/specs/lib/FocusTrapZone-test.tsx
  packages/react/test/specs/lib/felaSanitizeCssPlugin-test.ts
  perf/src/index.tsx
  perf/types.tsx
  types/screener.d.ts
  types/simulant.d.ts
Labels: ready for review

#1283 docs(pages): fix broken links in docs
  docs/src/components/DocsLayout.tsx
  docs/src/utils/helpers.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/AccessibilityBehaviors.tsx
  docs/src/views/AutoFocusZone.tsx
  docs/src/views/FAQ.tsx
  docs/src/views/FocusTrapZone.tsx
  docs/src/views/FocusZone.tsx
  docs/src/views/Layout.tsx
Labels: fix, ready for review

#1289 Update comments in Focus Zones
  build/gulp/plugins/util/getComponentInfo.ts
  build/gulp/plugins/util/parseDefaultValue.ts
  packages/react/src/lib/accessibility/FocusZone/AutoFocusZone.types.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.types.ts
Labels: docs, ready for review

#1242 chore(dropdown): add more unit tests
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: ready for review

#1267 chore: updated downshift to pick the status cleanup feature
  packages/react/package.json
  yarn.lock
Labels: accessibility, ready for review

#1243 docs(CodeSnippet): switch to PrismJS and reduce bundle size
  config.ts
  docs/src/components/CodeSnippet.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleKnobs.tsx
  docs/src/components/ComponentDoc/ComponentSourceManager/ComponentSourceManager.ts
  docs/src/components/ComponentPlaygroundSnippet.tsx
  docs/src/components/Editor/Editor.tsx
  docs/src/components/ExampleSnippet/ExampleSnippet.tsx
  docs/src/index.ejs
  docs/src/prototypes/dropdowns/AsyncDropdownSearch.tsx
  docs/src/utils/formatCode.ts
  docs/src/views/Accessibility.tsx
  docs/src/views/AccessibilityBehaviors.tsx
  docs/src/views/AutoFocusZone.tsx
  docs/src/views/FAQ.tsx
  docs/src/views/FocusTrapZone.tsx
  docs/src/views/FocusZone.tsx
  docs/src/views/Layout.tsx
  docs/src/views/QuickStart.tsx
  docs/src/views/ShorthandProps.tsx
  package.json
  packages/docs-components/package.json
  packages/docs-components/src/CodeSnippet/CodeSnippet.tsx
  packages/docs-components/src/CodeSnippet/formatCode.ts
  packages/docs-components/src/CodeSnippet/types.ts
  packages/docs-components/src/index.ts
  types/global.d.ts
  webpack.config.ts
  yarn.lock
Labels: docs, ready for review

#1282 feat(a11y): add default children behavior to behaviors
  CHANGELOG.md
  docs/src/examples/components/Menu/Usages/MenuExampleTabList.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  docs/src/views/AccessibilityBehaviors.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/lib/accessibility/Behaviors/Menu/menuBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/submenuBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tab/tabListBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarBehavior.ts
  packages/react/src/lib/accessibility/types.ts
  packages/react/test/specs/components/Menu/Menu-test.tsx
Labels: accessibility, ready for review

#1281 feat(Ref): extract to a separate package, add utils
  CHANGELOG.md
  packages/internal-tooling/package.json
  packages/react-component-ref/.babelrc
  packages/react-component-ref/jest.config.js
  packages/react-component-ref/package.json
  packages/react-component-ref/src/Ref.tsx
  packages/react-component-ref/src/RefFindNode.tsx
  packages/react-component-ref/src/RefForward.tsx
  packages/react-component-ref/src/handleRef.ts
  packages/react-component-ref/src/index.ts
  packages/react-component-ref/src/isRefObject.ts
  packages/react-component-ref/src/toRefObject.ts
  packages/react-component-ref/test/Ref-test.tsx
  packages/react-component-ref/test/RefFindNode-test.tsx
  packages/react-component-ref/test/RefForward-test.tsx
  packages/react-component-ref/test/fixtures.tsx
  packages/react-component-ref/test/handleRef-test.ts
  packages/react-component-ref/test/isRefObject-test.ts
  packages/react-component-ref/test/toRefObject-test.ts
  packages/react-component-ref/tsconfig.json
  packages/react/package.json
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/components/Video/Video.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/FocusZone/AutoFocusZone.tsx
  packages/react/src/lib/index.ts
  packages/react/test/specs/commonTests/isConformant.tsx
Labels: enhancement, ready for review

#1280 chore(perf): Normalize perf tests results POC
  build/gulp/tasks/perf.ts
  perf/src/PerfBaseline.tsx
  perf/src/index.tsx
  perf/types.tsx
Labels: ready for review

#1153 fix(Popup): avoid double rendering
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/createPopperReferenceProxy.ts
Labels: fix, ready for review

#1269 feat(border): focus styles mechanism
  CHANGELOG.md
  docs/src/examples/components/Attachment/Slots/AttachmentActionExample.shorthand.tsx
  docs/src/examples/components/Attachment/Types/AttachmentProgressExample.shorthand.tsx
  docs/src/examples/components/Attachment/Variations/AttachmentActionableExample.shorthand.tsx
  docs/src/examples/components/Button/Usage/ButtonUsageExample.shorthand.tsx
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/themes/teams-dark/components/Button/buttonVariables.ts
  packages/react/src/themes/teams-dark/siteVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Alert/alertStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Alert/alertVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Button/buttonVariables.ts
  packages/react/src/themes/teams-high-contrast/siteVariables.ts
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Attachment/attachmentVariables.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
  packages/react/src/themes/teams/getBorderFocusStyles.ts
  packages/react/src/themes/teams/getIconFillOrOutlineStyles.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: architecture, enhancement, ready for review, redlines

#1314 docs(FAQ): add question about reset/replace fontFaces
  docs/src/utils/helpers.tsx
  docs/src/views/FAQ.tsx
Labels: docs, ready for review

#1309 docs(Menu): add playground for component
  docs/src/components/ComponentDoc/useAccessibilityKnob.ts
  docs/src/components/ComponentDoc/useComponentProps.ts
  docs/src/components/ExampleSnippet/renderElementToJSX.ts
  docs/src/examples/components/Menu/Playground.tsx
Labels: docs, ready for review

#1331 fix(Ref): handle refs on updates of `innerRef` prop
  packages/react-component-ref/src/RefFindNode.tsx
  packages/react-component-ref/test/RefFindNode-test.tsx
Labels: fix, ready for review

#1299 feat(Dropdown): update styles for dark and hc Teams themes
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExample.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearchMultiple.shorthand.steps.ts
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownItem.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams-dark/siteVariables.ts
  packages/react/src/themes/teams-high-contrast/componentStyles.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Input/inputVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownItemStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownSelectedItemStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
Labels: ready for review

#1336 fix(Icon): align color example with the latest color updates
  CHANGELOG.md
  docs/src/examples/components/Icon/Variations/IconExampleColor.shorthand.tsx
  packages/react/src/themes/teams-dark/colors.ts
Labels: ready for review

#1270 feat(Dropdown): highlight by character key in non-search
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/types.ts
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: accessibility, ready for review

#1318 docs(sources): use ESLint to format generated JS output
  build/gulp/plugins/gulp-example-source.ts
  build/gulp/tasks/bundle.ts
  build/gulp/tasks/dll.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/stats.ts
  gulpfile.ts
  packages/internal-tooling/eslint/index.js
  packages/react/src/index.ts
  packages/react/src/themes/teams-dark/siteVariables.ts
  packages/react/src/themes/teams-high-contrast/siteVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownItemVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownSearchInputVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownSelectedItemVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams/components/Menu/menuDividerVariables.ts
  packages/react/src/themes/teams/components/Menu/menuItemVariables.ts
Labels: docs, ready for review

#1339 chore(dropdown): refactored returns in getDerivedStateFromProps
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: ready for review

#1323 feat(chat): focus outline
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.steps.ts
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  packages/react/src/themes/teams-dark/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: bug, ready for review, redlines

#1345 fix(Tree): Invalid DOM property 'tabindex'
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/Tree/treeTitleBehavior.ts
Labels: fix, ready for review

#1341 fix(Popup): fix positioning in scrollable container
  CHANGELOG.md
  packages/react/src/components/Popup/createPopperReferenceProxy.ts
Labels: fix, ready for review

#1292 docs(Slots): Clearly identify Slots in DocSite
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  docs/src/components/ComponentDoc/ComponentProp/ComponentPropName.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentProps.tsx
  docs/src/components/ComponentDoc/ComponentPropsTable/ComponentPropsRow.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Loader/Loader.tsx
Labels: ready for review

#1297 fix(dialogs): themeing support for Teams dark and hc
  CHANGELOG.md
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Dialog/dialogVariables.ts
  packages/react/src/themes/teams-high-contrast/componentStyles.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Dialog/dialogStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Dialog/dialogVariables.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Dialog/dialogStyles.ts
  packages/react/src/themes/teams/components/Dialog/dialogVariables.ts
Labels: ready for review

#1337 feat(themes): add FontAwesome theme
  CHANGELOG.md
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleImageCustomization.shorthand.tsx
  docs/src/examples/components/Icon/Usage/IconSetExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupColorPickerExample.shorthand.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/themes/base/components/Icon/iconNames.ts
  packages/react/src/themes/base/components/Icon/iconStyles.ts
  packages/react/src/themes/base/components/Icon/iconVariables.ts
  packages/react/src/themes/base/index.ts
  packages/react/src/themes/font-awesome/componentStyles.ts
  packages/react/src/themes/font-awesome/components/Icon/iconNames.ts
  packages/react/src/themes/font-awesome/components/Icon/iconStyles.ts
  packages/react/src/themes/font-awesome/index.ts
  packages/react/src/themes/index.ts
  packages/react/src/themes/teams/components/Icon/font/index.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Icon/iconVariables.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/stardustCircle.tsx
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  packages/react/src/themes/teams/index.tsx
  packages/react/src/themes/types.ts
Labels: fix, ready for review

#1353 feat(colors): add red color scheme in Teams theme
  CHANGELOG.md
  docs/src/views/ColorPalette.tsx
  packages/react/src/themes/teams-dark/colors.ts
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Label/labelVariables.ts
  packages/react/src/themes/teams-high-contrast/colors.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Label/labelVariables.ts
  packages/react/src/themes/teams/colors.ts
  packages/react/src/themes/teams/components/Label/labelVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: ready for review

#1354 chore(docs): use babel-loader
  babel.config.js
  build/gulp/tasks/test-projects.tsx
  build/tsconfig.common.json
  build/tsconfig.commonjs.json
  build/tsconfig.es.json
  build/webpack.config.perf.ts
  build/webpack.config.stats.ts
  docs/.babelrc
  docs/src/components/ComponentDoc/ComponentExample/index.tsx
  docs/src/components/ComponentDoc/ComponentSourceManager/index.ts
  docs/src/components/Editor/index.tsx
  package.json
  packages/docs-components/.babelrc
  packages/internal-tooling/babel/index.js
  packages/react-component-event-listener/src/EventListener.ts
  packages/react-component-event-listener/src/StackableEventListener.ts
  packages/react-component-event-listener/src/index.ts
  packages/react-component-event-listener/src/lib/addEventListener.ts
  packages/react-component-event-listener/src/lib/removeEventListener.ts
  packages/react-component-event-listener/src/types.internal.ts
  packages/react-component-event-listener/src/types.ts
  packages/react-component-nesting-registry/src/index.ts
  packages/react-component-ref/src/index.ts
  packages/react/src/components/Popup/positioningHelper.ts
  packages/react/src/index.ts
  packages/react/src/lib/index.ts
  packages/react/src/themes/fabric/.gitkeep
  packages/react/src/themes/fabric/index.ts
  packages/react/src/themes/teams/components/Icon/svg/index.ts
  packages/react/src/types.ts
  perf/.babelrc
  perf/src/index.tsx
  perf/types.ts
  webpack.config.ts
  yarn.lock
Labels: ready for review

#1358 feat(popper): custom react wrapper
  CHANGELOG.md
  docs/src/prototypes/MenuButton/MenuButton.tsx
  docs/src/prototypes/MenuButton/index.tsx
  packages/react/package.json
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Popup/createPopperReferenceProxy.ts
  packages/react/src/index.ts
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/lib/positioner/index.ts
  packages/react/src/lib/positioner/positioningHelper.ts
  packages/react/src/lib/positioner/types.internal.ts
  packages/react/src/lib/positioner/types.ts
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
  packages/react/test/specs/components/Popup/Popup-test.tsx
  packages/react/test/specs/lib/positioner/positioningHelper-test.ts
  yarn.lock
Labels: architecture, perf, ready for review

#1340 chore(colors): Improve colors typings per component variables
  CHANGELOG.md
  docs/src/components/ColorBox.tsx
  docs/src/components/ColorSchemes.tsx
  docs/src/components/ColorVariants.tsx
  docs/src/examples/components/Divider/Variations/DividerExampleColor.shorthand.tsx
  docs/src/examples/components/Header/Variations/HeaderExampleColor.shorthand.tsx
  docs/src/examples/components/Header/Variations/HeaderExampleColor.tsx
  docs/src/examples/components/Icon/Variations/IconExampleColor.shorthand.tsx
  docs/src/examples/components/Label/Variations/LabelExampleColor.shorthand.tsx
  docs/src/examples/components/Segment/Variations/SegmentExampleColor.shorthand.tsx
  docs/src/examples/components/Segment/Variations/SegmentExampleColor.tsx
  docs/src/examples/components/Text/Variations/TextExampleColor.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleColor.tsx
  docs/src/views/ColorPalette.tsx
  packages/react/src/index.ts
  packages/react/src/lib/index.ts
  packages/react/src/lib/stringLiteralsArray.ts
  packages/react/src/themes/base/components/Text/textVariables.ts
  packages/react/src/themes/colorUtils.ts
  packages/react/src/themes/teams-dark/components/Divider/dividerVariables.ts
  packages/react/src/themes/teams-dark/components/Header/headerDescriptionVariables.ts
  packages/react/src/themes/teams-dark/components/Icon/iconVariables.ts
  packages/react/src/themes/teams-dark/components/Label/labelVariables.ts
  packages/react/src/themes/teams-dark/components/Menu/menuVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Label/labelVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/colors.ts
  packages/react/src/themes/teams/components/Divider/dividerStyles.ts
  packages/react/src/themes/teams/components/Divider/dividerVariables.ts
  packages/react/src/themes/teams/components/Header/headerDescriptionVariables.ts
  packages/react/src/themes/teams/components/Header/headerVariables.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Icon/iconVariables.ts
  packages/react/src/themes/teams/components/Label/labelVariables.ts
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
  packages/react/src/themes/teams/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/components/Segment/segmentVariables.ts
  packages/react/src/themes/teams/components/Text/textStyles.ts
  packages/react/src/themes/teams/components/Text/textVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
  packages/react/src/themes/teams/types.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/themes/colorUtils-test.ts
Labels: ready for review

#1379 test(Behaviors): Improve behaviors tests for FocusZone
  packages/react/src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Chat/chatMessageBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Grid/gridBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/menuBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/submenuBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tab/tabListBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeBehavior.ts
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
  packages/react/test/specs/behaviors/testHelper.tsx
Labels: accessibility, ready for review

#1386 fix(menuItemBehavior): Remove redundant aria attributes
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
Labels: fix, ready for review

#1380 chore(behaviors): some a11y behavior improvements
  packages/react/src/lib/accessibility/Behaviors/Alert/alertWarningBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Embed/embedBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Input/inputBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/selectableListBehavior.ts
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: accessibility, ready for review

#1364 chore(dialogBehavior): add more tests
  packages/react/test/specs/behaviors/dialogBehavior-test.tsx
  packages/react/test/specs/behaviors/popupBehavior-test.tsx
Labels: accessibility, ready for review

#1371 docs(Accessibility): improve acc descriptions for components
  CHANGELOG.md
  docs/src/components/ComponentDoc/AccessibilityDescription.tsx
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  package.json
  packages/internal-tooling/babel/index.js
  packages/internal-tooling/package.json
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/Form/Form.tsx
  packages/react/src/components/Grid/Grid.tsx
  packages/react/src/components/Header/Header.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Image/Image.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/Reaction/Reaction.tsx
  yarn.lock
Labels: ready for review

#1370 chore(docs): make HMR working properly
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/index.tsx
  docs/src/routes.tsx
  docs/src/utils/exampleContexts.ts
  package.json
  packages/internal-tooling/babel/index.js
  yarn.lock
Labels: ready for review

#1395 chore(package): use @babel/register instead of ts-node
  babel.register.js
  build/gulp/plugins/gulp-component-menu-behaviors.ts
  build/gulp/plugins/gulp-component-menu.ts
  build/gulp/plugins/gulp-doctoc.ts
  build/gulp/plugins/gulp-example-menu.ts
  build/gulp/plugins/gulp-example-source.ts
  build/gulp/plugins/gulp-react-docgen.ts
  build/gulp/plugins/gulp-webpack.ts
  build/gulp/plugins/util/docgen.ts
  build/gulp/plugins/util/getComponentInfo.ts
  build/gulp/plugins/util/getRelativePathToSourceFile.ts
  build/gulp/plugins/util/parseDefaultValue.ts
  build/gulp/tasks/bundle.ts
  build/gulp/tasks/dll.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/perf.ts
  build/gulp/tasks/stats.ts
  build/gulp/tasks/test-circulars/index.ts
  build/gulp/tasks/test-circulars/utils.ts
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-unit.ts
  build/screener/screener.config.js
  build/screener/screener.states.ts
  build/screener/screener.steps.ts
  build/tsconfig.json
  build/tslint/jsxAttributeNameRule.ts
  build/webpack.config.dll.ts
  build/webpack.config.perf.ts
  build/webpack.config.stats.ts
  build/webpack.config.ts
  build/webpack.config.umd.ts
  gulpfile.js
  package.json
  packages/docs-components/package.json
  packages/react-component-event-listener/package.json
  packages/react-component-nesting-registry/package.json
  packages/react-component-ref/package.json
  tslint.json
  yarn.lock
Labels: ready for review

#1399 refactor(customPropTypes): remove usage of _.chain
  packages/react-proptypes/src/index.ts
  packages/react/test/specs/components/Box/Box-test.ts
Labels: ready for review

#1400 refactor(Ref): use only one type for props
  packages/react-component-ref/src/Ref.tsx
  packages/react-component-ref/src/RefFindNode.tsx
  packages/react-component-ref/src/RefForward.tsx
  packages/react-component-ref/src/index.ts
  packages/react-component-ref/src/types.ts
  packages/react-component-ref/test/toRefObject-test.ts
Labels: ready for review

#1384 feat(menu): automatic positioning inside viewport
  CHANGELOG.md
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/lib/positioner/getScrollParent.ts
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
  packages/react/test/specs/lib/positioner/getScrollParent-test.ts
Labels: enhancement, fix, ready for review

#1312 feat(dropdown): align, position, offset props + automatic position
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Variations/DropdownExampleOffset.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExamplePosition.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/index.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.shorthand.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.tsx
  docs/src/prototypes/mentions/MentionsDropdown.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/lib/positioner/positioningHelper.ts
  packages/react/src/themes/teams-high-contrast/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
Labels: architecture, enhancement, ready for review

#1398 chore(Perf): describe current workflow
  perf/doc/perf.md
  perf/doc/perf_chart.png
Labels: docs, ready for review

#1420 fix(Popup): proptypes for content and trigger
  CHANGELOG.md
  packages/react-proptypes/src/index.ts
  packages/react/src/components/Popup/Popup.tsx
Labels: ready for review

#1418 fix(Accordion.Title): make contentRef prop optional
  CHANGELOG.md
  packages/react/src/components/Accordion/AccordionTitle.tsx
  packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx
Labels: fix, ready for review

#1416 fix(Dropdown): call getDerivedStateFromProps() from AutoControlledComponent
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: fix, ready for review

#1431 fix(popper): fix popper.js imports
  packages/react/src/lib/positioner/Popper.tsx
Labels: fix, ready for review

#1406 fix(input): fixing Firefox placeholder color
  CHANGELOG.md
  packages/react/src/themes/base/components/Input/inputStyles.ts
Labels: ready for review

#1435 fix(Icon): revert changes with different roots
  CHANGELOG.md
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/themes/base/components/Icon/iconStyles.ts
  packages/react/src/themes/font-awesome/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/types.ts
Labels: fix, ready for review

#1434 fix(popper): flickering
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/lib/positioner/types.ts
Labels: fix, ready for review
