Repository microsoft/fluent-ui-react, pull requests merged in 2019-09, with the labels that each got.

#1849 fix(docs): let CodeSandbox package versions match our versions
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox/createPackageJson.ts
  docs/src/components/Playground/renderConfig.ts
Labels: 📚 docs, 🚀 ready for review, 🧰 fix

#1874 fix(doesNodeContainClick): use proper `document` to find nodes
  CHANGELOG.md
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/lib/doesNodeContainClick.tsx
Labels: 🚀 ready for review, 🧰 fix

#1856 docs(Dropdown): update docs regarding `renderSelectedItem`
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: needs author feedback, 🚀 ready for review

#1877 chore: remove dependency on @stardust/proptypes in @stardust/ref
  packages/react-component-ref/package.json
  packages/react-component-ref/src/Ref.tsx
  packages/react-component-ref/src/RefFindNode.tsx
  packages/react-component-ref/src/RefForward.tsx
  packages/react-component-ref/src/isRefObject.ts
  packages/react-component-ref/src/toRefObject.ts
  packages/react-component-ref/src/types.ts
Labels: 🗑️ chore, 🚀 ready for review

#1872 feat(Alert): add `fitted` prop
  CHANGELOG.md
  docs/src/examples/components/Alert/Usage/AlertExampleWidth.shorthand.tsx
  docs/src/examples/components/Alert/Usage/index.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleFitted.shorthand.tsx
  docs/src/examples/components/Alert/Variations/index.tsx
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#1875 fix(factories): add types to createShorthandFactory() methods
  CHANGELOG.md
  packages/react/src/components/Accordion/AccordionContent.tsx
  packages/react/src/components/Accordion/AccordionTitle.tsx
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Avatar/Avatar.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Button/ButtonGroup.tsx
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Divider/Divider.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownItem.tsx
  packages/react/src/components/Dropdown/DropdownSearchInput.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/Flex/FlexItem.tsx
  packages/react/src/components/Form/Form.tsx
  packages/react/src/components/Form/FormField.tsx
  packages/react/src/components/Header/Header.tsx
  packages/react/src/components/Header/HeaderDescription.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTree.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTreeItem.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTreeTitle.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Image/Image.tsx
  packages/react/src/components/ItemLayout/ItemLayout.tsx
  packages/react/src/components/Label/Label.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuDivider.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/MenuButton/MenuButton.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/components/Reaction/Reaction.tsx
  packages/react/src/components/Reaction/ReactionGroup.tsx
  packages/react/src/components/Status/Status.tsx
  packages/react/src/components/Text/Text.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarCustomItem.tsx
  packages/react/src/components/Toolbar/ToolbarDivider.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenu.tsx
  packages/react/src/components/Toolbar/ToolbarMenuDivider.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
  packages/react/src/components/Toolbar/ToolbarRadioGroup.tsx
  packages/react/src/components/Tooltip/TooltipContent.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/components/Video/Video.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/factories.ts
Labels: 🚀 ready for review, 🧰 fix

#1883 chore(changelog): fix heading order
  CHANGELOG.md
Labels: 🚀 ready for review

#1882 perf(Tooltip): fix Popper positioning called when unnecessary
  CHANGELOG.md
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/test/specs/components/Tooltip/Tooltip-test.tsx
Labels: perf, 🚀 ready for review

#1879 fix(Toolbar): overflow screener test
  CHANGELOG.md
  docs/src/examples/components/Toolbar/Content/ToolbarExampleOverflow.shorthand.tsx
Labels: 🚧 WIP

#1852 feat(Dialog): add `backdrop` and `closeOnOutsideClick` props
  CHANGELOG.md
  docs/src/examples/components/Dialog/Content/DialogExampleHeaderAction.shorthand.tsx
  docs/src/examples/components/Dialog/Usage/index.tsx
  docs/src/examples/components/Dialog/Variations/DialogExampleBackdrop.shorthand.steps.ts
  docs/src/examples/components/Dialog/Variations/DialogExampleBackdrop.shorthand.tsx
  docs/src/examples/components/Dialog/Variations/index.tsx
  docs/src/examples/components/Dialog/index.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/themes/base/components/Dialog/dialogStyles.ts
  packages/react/src/themes/teams/components/Dialog/dialogStyles.ts
  packages/react/src/themes/teams/components/Dialog/dialogVariables.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#1850 chore: remove isFromKeyboard prop from components
  CHANGELOG.md
  docs/src/prototypes/customToolbar/darkThemeOverrides.ts
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/Grid/Grid.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/components/Reaction/Reaction.tsx
  packages/react/src/components/Slider/Slider.tsx
  packages/react/src/components/Toolbar/ToolbarCustomItem.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
  packages/react/src/lib/felaFocusVisibleEnhancer.ts
  packages/react/src/lib/felaRenderer.tsx
  packages/react/src/themes/teams-high-contrast/components/Alert/alertStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownItemStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams/components/Embed/embedStyles.ts
  packages/react/src/themes/teams/components/HierarchicalTree/hierarchicalTreeItemStyles.ts
  packages/react/src/themes/teams/components/HierarchicalTree/hierarchicalTreeTitleStyles.ts
  packages/react/src/themes/teams/components/List/listItemStyles.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  packages/react/src/themes/teams/components/Reaction/reactionStyles.ts
  packages/react/src/themes/teams/components/Slider/sliderStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarCustomItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarMenuItemStyles.ts
  packages/react/src/themes/teams/components/Tree/treeItemStyles.ts
  packages/react/src/themes/teams/components/Tree/treeTitleStyles.ts
  packages/react/src/themes/teams/getBorderFocusStyles.ts
  packages/react/test/specs/lib/__snapshots__/felaFocusVisibleEnhancer-test.ts.snap
  packages/react/test/specs/lib/felaFocusVisibleEnhancer-test.ts
Labels: ⚙️ enhancement, 🗑️ chore, 🚀 ready for review

#1884 fix(Dropdown): pass custom window to Downshift
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: accessibility, 🚀 ready for review

#1743 chore: switch back to Fela
  build/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleColorPicker.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleVariables.tsx
  docs/src/components/ComponentPlayground/usePlaygroundComponent.tsx
  docs/src/components/Playground/renderConfig.ts
  docs/src/components/VariableResolver/VariableResolver.tsx
  packages/internal-tooling/package.json
  packages/react/package.json
  packages/react/src/components/Design/Design.tsx
  packages/react/src/components/Portal/PortalInner.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/Provider/ProviderConsumer.tsx
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/felaFocusVisibleEnhancer.ts
  packages/react/src/lib/felaRenderer.tsx
  packages/react/src/lib/index.ts
  packages/react/src/lib/mergeProviderContexts.ts
  packages/react/src/themes/base/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/base/components/Dialog/dialogStyles.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/components/Provider/Provider-test.tsx
  packages/react/test/specs/lib/felaFocusVisibleEnhancer-test.ts
  packages/react/test/specs/lib/mergeProviderContexts/mergeProviderContexts-test.ts
  packages/react/test/utils/withProvider.tsx
  yarn.lock
Labels: 🗑️ chore, 🚀 ready for review

#1868 docs(fix): navigation links
  CHANGELOG.md
  docs/src/components/DocsLayout.tsx
  docs/src/utils/helpers.tsx
Labels: 📚 docs, 🚀 ready for review, 🧰 bug

#1860 feat(CopyToClipboard): add prototype
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/CopyToClipboard/CopyToClipboard.tsx
  docs/src/prototypes/CopyToClipboard/NotificationProvider.tsx
  docs/src/prototypes/CopyToClipboard/index.tsx
  docs/src/prototypes/CopyToClipboard/themeOverrides.ts
  docs/src/routes.tsx
  packages/react/src/themes/types.ts
Labels: 🚀 ready for review, 🤖 prototype

#1876 feat(Knobs): improve `useRangeKnob()` and add `LogInspector`/`useLogKnob()`
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/examples/components/Alert/Usage/AlertExampleWidth.shorthand.tsx
  docs/src/examples/components/Dialog/Usage/DialogExampleCallbacks.shorthand.tsx
  docs/src/examples/components/MenuButton/State/MenuButtonExampleOpen.shorthand.tsx
  docs/src/examples/components/Portal/State/PortalExampleOpen.tsx
  docs/src/examples/components/Portal/State/index.tsx
  docs/src/examples/components/Portal/Types/PortalExampleControlled.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExampleControlled.tsx
  docs/src/examples/components/Portal/Types/index.tsx
  docs/src/examples/components/Portal/index.tsx
  packages/docs-components/package.json
  packages/docs-components/src/index.ts
  packages/docs-components/src/knobs/KnobContexts.ts
  packages/docs-components/src/knobs/KnobInspector.tsx
  packages/docs-components/src/knobs/KnobProvider.tsx
  packages/docs-components/src/knobs/LogInspector.tsx
  packages/docs-components/src/knobs/defaultComponents.tsx
  packages/docs-components/src/knobs/lib/parseRangeValue.ts
  packages/docs-components/src/knobs/types.ts
  packages/docs-components/src/knobs/useKnob.ts
  packages/docs-components/src/knobs/useKnobValues.ts
  packages/docs-components/src/knobs/useLogKnob.ts
  packages/docs-components/src/knobs/useRangeKnob.ts
Labels: ⚙️ enhancement, 📚 docs, 🚀 ready for review

#1895 perf: use `Object.assign` in `@babel/plugin-proposal-object-rest-spread`
  CHANGELOG.md
  docs/src/examples/components/Chat/Performance/Chat.perf.tsx
  packages/internal-tooling/babel/index.js
Labels: perf, 🚀 ready for review

#1831 fix(Menu): Menu width and Submenu indicator fix
  CHANGELOG.md
  docs/src/examples/components/Menu/Usage/MenuExampleWithSubmenu.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVertical.shorthand.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/themes/base/components/Icon/iconNames.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/chevronDownMedium.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/chevronRightMedium.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
  packages/react/src/themes/teams/components/Menu/menuStyles.ts
  packages/react/src/themes/teams/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/index.tsx
Labels: help wanted, 💅 styling issue, 🚀 ready for review

#1903 fix(Chat): fix handling of `onMouseEnter`
  CHANGELOG.md
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/test/specs/components/Chat/ChatMessage-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#1886 fix(factories): CreateShorthandOptions should be typed
  CHANGELOG.md
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTree.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTreeItem.tsx
  packages/react/src/components/MenuButton/MenuButton.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/lib/factories.ts
  packages/react/src/types.ts
Labels: needs author changes, 🗑️ chore

#1897 feat(TextArea): add component
  CHANGELOG.md
  docs/src/examples/components/TextArea/States/TextAreaDisabledExample.shorthand.tsx
  docs/src/examples/components/TextArea/States/TextAreaValueExample.shorthand.tsx
  docs/src/examples/components/TextArea/States/index.tsx
  docs/src/examples/components/TextArea/Types/TextAreaExample.shorthand.tsx
  docs/src/examples/components/TextArea/Types/index.tsx
  docs/src/examples/components/TextArea/Usage/TextAreaMaxLengthExample.shorthand.tsx
  docs/src/examples/components/TextArea/Usage/index.tsx
  docs/src/examples/components/TextArea/index.tsx
  packages/react/src/components/TextArea/TextArea.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/TextArea/textAreaBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/TextArea/textAreaStyles.ts
  packages/react/src/themes/teams/components/TextArea/textAreaVariables.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Input/Input-test.tsx
  packages/react/test/specs/components/TextArea/TextArea-test.tsx
Labels: RFC, 🚧 WIP

#1916 docs: persist editor state in url
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  packages/react/package.json
  yarn.lock
Labels: 📚 docs

#1901 fix(Accessibility): fix order of applying unhandled props and key handlers
  CHANGELOG.md
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTreeItem.tsx
  packages/react/src/components/Slider/Slider.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/test/specs/commonTests/eventTarget.ts
  packages/react/test/specs/commonTests/handlesAccessibility.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Embed/Embed-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#1887 feat(shadows): updating the shadow variables
  CHANGELOG.md
  packages/react/src/themes/teams/siteVariables.ts
Labels: 💅 styling issue

#1912 fix(Tree): fix focus styles
  CHANGELOG.md
  docs/src/examples/components/Tree/Types/TreeExample.shorthand.steps.ts
  packages/react/src/themes/teams/components/HierarchicalTree/hierarchicalTreeItemStyles.ts
  packages/react/src/themes/teams/components/Tree/treeItemStyles.ts
Labels: accessibility, 🚀 ready for review

#1890 feat(Tree): add virtualized tree prototype
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/VirtualizedTree/VirtualizedTree.tsx
  docs/src/prototypes/VirtualizedTree/index.tsx
  docs/src/prototypes/VirtualizedTree/itemsGenerator.ts
  docs/src/routes.tsx
  package.json
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  yarn.lock
Labels: 🚀 ready for review, 🤖 prototype

#1913 docs(Knobs): improve LogInspector
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox/createPackageJson.ts
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/Playground/renderConfig.ts
  docs/src/examples/components/Dialog/Usage/DialogExampleCallbacks.shorthand.tsx
  docs/src/examples/components/Portal/State/PortalExampleOpen.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenu.shorthand.tsx
  packages/code-sandbox/src/createCallbackLogFormatter.ts
  packages/code-sandbox/src/index.ts
  packages/code-sandbox/src/knobComponents.tsx
  packages/docs-components/src/CodeSnippet/CodeSnippet.tsx
  packages/docs-components/src/CodeSnippet/formatCode.ts
  packages/docs-components/src/CodeSnippet/types.ts
Labels: 📚 docs, 🚀 ready for review

#1929 fix(Chat): use more accurate positioning in scrollable containers
  CHANGELOG.md
  docs/src/examples/components/Chat/Usage/ChatExampleInScrollable.shorthand.tsx
  docs/src/examples/components/Chat/Usage/index.tsx
  packages/docs-components/src/knobs/useRangeKnob.ts
  packages/react/src/components/Chat/ChatMessage.tsx
Labels: 🚧 WIP

#1930 fix(FocusTrapZone): Do not force focus inside focus trap zone on outside focus
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
Labels: accessibility, 🚀 ready for review

#1937 fix(menuButtonBehavior): Don't add 'aria-haspopup', when 'MenuButton' behaves as context menu
  packages/react/src/lib/accessibility/Behaviors/MenuButton/menuButtonBehavior.ts
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: 🚀 ready for review

#1920 feat(Toolbar): add support for radio & checkbox groups
  CHANGELOG.md
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenuItemToggle.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenuRadioGroup.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/index.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarMenu.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenuRadioGroup.tsx
  packages/react/src/components/Toolbar/ToolbarRadioGroup.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarMenuItemCheckboxBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarMenuItemRadioBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarMenuRadioGroupBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarMenuItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarMenuRadioGroupStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarMenuRadioGroupVariables.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Toolbar/ToolbarMenuRadioGroup-test.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#1927 feat(Toolbar): support for a popup in menu
  CHANGELOG.md
  docs/src/examples/components/Toolbar/Content/ToolbarExampleRadioGroup.shorthand.tsx
  docs/src/examples/components/Toolbar/Usage/ToolbarExampleActionPopupInMenu.shorthand.steps.ts
  docs/src/examples/components/Toolbar/Usage/ToolbarExampleActionPopupInMenu.shorthand.tsx
  docs/src/examples/components/Toolbar/Usage/ToolbarExamplePopupInMenu.shorthand.steps.ts
  docs/src/examples/components/Toolbar/Usage/ToolbarExamplePopupInMenu.shorthand.tsx
  docs/src/examples/components/Toolbar/Usage/ToolbarExampleWithTooltip.shorthand.tsx
  docs/src/examples/components/Toolbar/Usage/index.tsx
  e2e/tests/popupInToolbarMenu-example.tsx
  e2e/tests/popupInToolbarMenu-test.ts
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
Labels: RFC, 🚀 ready for review

#1940 chore(ComponentExample): use React.Elements by default
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentSourceManager/ComponentSourceManager.ts
  docs/src/components/ComponentDoc/ComponentSourceManager/getExampeSource.ts
  docs/src/components/ExamplePlaceholder.tsx
  docs/src/utils/exampleContexts.ts
  docs/src/utils/index.tsx
  package.json
  yarn.lock
Labels: 📚 docs, 🗑️ chore, 🚀 ready for review

#1948 docs: remove Usage tab
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentUsage.tsx
  docs/src/components/DocsRoot.tsx
  docs/src/examples/components/Accordion/Usage/index.tsx
  docs/src/examples/components/Accordion/index.tsx
  docs/src/examples/components/Alert/index.tsx
  docs/src/examples/components/Avatar/Usage/index.tsx
  docs/src/examples/components/Avatar/index.tsx
  docs/src/examples/components/Button/Usage/index.tsx
  docs/src/examples/components/Button/index.tsx
  docs/src/examples/components/Chat/Usage/index.tsx
  docs/src/examples/components/Chat/index.tsx
  docs/src/examples/components/Dropdown/Usage/index.tsx
  docs/src/examples/components/Dropdown/index.tsx
  docs/src/examples/components/Embed/Usage/index.tsx
  docs/src/examples/components/Embed/index.tsx
  docs/src/examples/components/Form/Usage/index.tsx
  docs/src/examples/components/Form/index.tsx
  docs/src/examples/components/Icon/Usage/index.tsx
  docs/src/examples/components/Icon/index.tsx
  docs/src/examples/components/Loader/Usage/index.tsx
  docs/src/examples/components/Loader/index.tsx
  docs/src/examples/components/Menu/Usage/index.tsx
  docs/src/examples/components/Menu/index.tsx
  docs/src/examples/components/MenuButton/Usage/index.tsx
  docs/src/examples/components/MenuButton/index.tsx
  docs/src/examples/components/Popup/Usage/index.tsx
  docs/src/examples/components/Popup/index.tsx
  docs/src/examples/components/Provider/Usage/index.tsx
  docs/src/examples/components/Provider/index.tsx
  docs/src/examples/components/Slider/Usage/index.tsx
  docs/src/examples/components/Slider/index.tsx
  docs/src/examples/components/TextArea/Usage/index.tsx
  docs/src/examples/components/TextArea/index.tsx
  docs/src/examples/components/Toolbar/Usage/index.tsx
  docs/src/examples/components/Toolbar/index.tsx
  docs/src/examples/components/Tooltip/Usage/index.tsx
  docs/src/examples/components/Tooltip/index.tsx
  docs/src/examples/components/Tree/index.tsx
Labels: 📚 docs, 🚀 ready for review

#1938 fix(Dropdown): properly accept id on searchInput from Form
  CHANGELOG.md
  docs/src/examples/components/Form/Usage/FormExampleDropdown.shorthand.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: accessibility, 🚀 ready for review

#1949 docs(Dialog): remove cancel button in an example containing X
  CHANGELOG.md
  docs/src/examples/components/Dialog/Content/DialogExampleHeaderAction.shorthand.tsx
Labels: 🚀 ready for review

#1950 chore(codesandbox): add prettier dependency
  docs/src/components/Playground/renderConfig.ts
Labels: ready for merge, 🗑️ chore

#1909 fix(Embed): get rid of white flash
  CHANGELOG.md
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/themes/teams/components/Embed/embedStyles.ts
Labels: 🚀 ready for review, 🧰 fix

#1922 feat(TextArea): add basic styles and inverted variant
  CHANGELOG.md
  docs/src/examples/components/TextArea/Types/textAreaExample.shorthand.steps.ts
  docs/src/examples/components/TextArea/Usage/TextAreaExampleHeight.shorthand.tsx
  docs/src/examples/components/TextArea/Usage/TextAreaExampleMaxLength.shorthand.tsx
  docs/src/examples/components/TextArea/Usage/TextAreaExampleResize.shorthand.tsx
  docs/src/examples/components/TextArea/Usage/TextAreaMaxLengthExample.shorthand.tsx
  docs/src/examples/components/TextArea/Usage/index.tsx
  docs/src/examples/components/TextArea/Variations/TextAreaExampleFluid.shorthand.tsx
  docs/src/examples/components/TextArea/Variations/TextAreaExampleInverted.shorthand.steps.ts
  docs/src/examples/components/TextArea/Variations/TextAreaExampleInverted.shorthand.tsx
  docs/src/examples/components/TextArea/Variations/index.tsx
  docs/src/examples/components/TextArea/index.tsx
  packages/react/src/components/TextArea/TextArea.tsx
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/TextArea/textAreaVariables.ts
  packages/react/src/themes/teams/components/TextArea/textAreaStyles.ts
  packages/react/src/themes/teams/components/TextArea/textAreaVariables.ts
Labels: ⚙️ enhancement, 💅 styling issue, 🚀 ready for review

#1943 fix(Dropdown): comparison of custom objects
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#1892 docs(props): put props on a single page, fix props links
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentPropCard.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentProps.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentPropsComponents.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentPropsDescription.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentPropsOutline.tsx
  docs/src/components/ComponentDoc/ComponentPropsTable/ComponentPropsRow.tsx
  docs/src/components/ComponentDoc/ComponentPropsTable/ComponentPropsTable.tsx
  docs/src/components/DocsLayout.tsx
Labels: 📚 docs, 🚀 ready for review

#1956 docs(mixed): fix knobs on CodeSandbox, display LogInspector always
  build/webpack.config.ts
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/prototypes/customToolbar/index.tsx
  packages/code-sandbox/src/KnobsSnippet.tsx
  packages/code-sandbox/src/SandboxApp.tsx
  packages/code-sandbox/src/index.ts
  packages/docs-components/src/CodeSnippet/formatCode.ts
Labels: 📚 docs, 🗑️ chore, 🚀 ready for review

#1942 fix(tooltip): Make tooltip visible for screen reader
  CHANGELOG.md
  packages/react/src/themes/teams/components/Tooltip/tooltipStyles.ts
Labels: 🚀 ready for review, 🧰 fix

#1958 docs(ComponentExample): temporary enable HTML rendering
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: 📚 docs, 🚀 ready for review

#1957 perf(renderComponent): avoid multiple style function calls
  CHANGELOG.md
  packages/react/src/components/Design/Design.tsx
  packages/react/src/lib/getClasses.ts
  packages/react/src/lib/index.ts
  packages/react/src/lib/renderComponent.tsx
Labels: perf, 🚀 ready for review

#1959 fix(Popper): fix comparison for `scrollParent`
  CHANGELOG.md
  packages/react/src/lib/positioner/Popper.tsx
Labels: 🚀 ready for review, 🧰 fix

#1961 fix(theme): updating `bodyBackground` color for Teams dark theme
  CHANGELOG.md
  packages/react/src/themes/teams-dark/siteVariables.ts
Labels: 🚀 ready for review

#1933 feat(buttons): update button colors to match current Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams-dark/components/Button/buttonVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Button/buttonVariables.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
Labels: 💅 styling issue

#1954 fix(icons): update Office brand icons
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/icons/filesExcel.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesExcelBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesOneNote.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesOneNoteBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesPowerPoint.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesPowerPointBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesVisio.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesVisioBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesWord.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesWordBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/oneDrive.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/yammer.tsx
Labels: 💅 styling issue, 🚀 ready for review

#1911 feat(Accessibility): Initial accessibility attributes schema.
  .prettierignore
  CHANGELOG.md
  build/gulp/tasks/docs.ts
  codecov.yml
  config.ts
  docs/src/app.tsx
  packages/ability-attributes/.gitignore
  packages/ability-attributes/package.json
  packages/ability-attributes/schema.json
  packages/ability-attributes/src/index.ts
  packages/ability-attributes/tsconfig.json
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/lib/renderComponent.tsx
  yarn.lock
Labels: ⚙️ enhancement, 🚀 ready for review

#1970 fix(mixed): avoid usages of global `document` and `window`
  CHANGELOG.md
  packages/react/.eslintrc.json
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarRadioGroup.tsx
  packages/react/src/lib/accessibility/FocusZone/focusUtilities.ts
  packages/react/src/lib/debug/debugApi.ts
  packages/react/src/lib/debug/index.ts
  packages/react/src/lib/doesNodeContainClick.tsx
  packages/react/src/lib/felaRenderer.tsx
  packages/react/src/lib/fontSizeUtility.ts
  packages/react/src/lib/isBrowser.tsx
  packages/react/src/lib/mergeProviderContexts.ts
  packages/react/src/lib/positioner/getScrollParent.ts
Labels: 🚀 ready for review, 🧰 fix

#1972 fix(whatInput): use proper `document` to set `data-whatinput` attr
  CHANGELOG.md
  docs/src/examples/components/Provider/Usage/ProviderExampleTargetFrame.tsx
  docs/src/examples/components/Provider/Usage/index.tsx
  packages/react/src/lib/whatInput.ts
Labels: 🚀 ready for review, 🧰 fix

#1955 docs(VirtualizedTree): left-arrow navigation to hidden parent item
  docs/src/prototypes/VirtualizedTree/VirtualizedTree.tsx
Labels: accessibility, 🚀 ready for review, 🧰 fix

#1975 chore: release 0.38.2
  CHANGELOG.md
Labels: 🗑️ chore

#1103 fix(build): remove prepush
  build/gulp/tasks/git/index.ts
  build/gulp/tasks/git/prepush.ts
  gulpfile.ts
  package.json
Labels: 🚀 ready for review

#1978 docs(prototypes): remove MenuButton
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/MenuButton/MenuButton.tsx
  docs/src/prototypes/MenuButton/focusUtils.ts
  docs/src/prototypes/MenuButton/index.tsx
  docs/src/prototypes/MenuButton/menuButtonBehavior.ts
  docs/src/routes.tsx
Labels: 📚 docs, 🚀 ready for review
