Repository microsoft/fluent-ui-react, pull requests merged in 2019-12, with the labels that each got.

#2151 Perf: Component Comparisons
  packages/perf-test/.digest/config.tsx
  packages/perf-test/package.json
  packages/perf-test/stories/Button.perf.tsx
  packages/perf-test/stories/Checkbox.perf.tsx
  packages/perf-test/stories/Icon.perf.tsx
  packages/perf-test/stories/Slider.perf.tsx
  packages/perf-test/tasks/perf-test.ts
  yarn.lock
Labels: :hammer_and_wrench: tooling

#2161 adds publishconfig public for new packages so we don't run into publish issues
  CHANGELOG.md
  packages/digest/package.json
  packages/perf-test/package.json
  packages/playground/package.json
  packages/react-theming/package.json
  scripts/package.json
  yarn.lock
Labels: :hammer_and_wrench: tooling

#2156 feat(Icons): Add new icons to Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/noPresenter.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/presenter.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/volume.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/volumeDown.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/volumeUp.tsx
Labels: 🚀 ready for review

#2160 fix(renderer): properly expand colors in "border-color" shorthand
  CHANGELOG.md
  packages/react/src/utils/cssExpandShorthand.ts
  packages/react/test/specs/utils/__snapshots__/felaRenderer-test.tsx.snap
  packages/react/test/specs/utils/felaRenderer-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#2176 docs(Embed): update examples
  docs/src/examples/components/Embed/Slots/EmbedExampleIframe.shorthand.tsx
  docs/src/examples/components/Embed/Slots/index.tsx
  docs/src/examples/components/Embed/Usage/EmbedExampleYouTube.shorthand.tsx
Labels: 📚 docs, 🚀 ready for review

#2186 fix(CI): dangerjs error
  yarn.lock
Labels: 🗑️ chore

#2180 feat(Icons): Add tag icon to Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/tag.tsx
Labels: 🚀 ready for review

#2189 fix(Checkbox): toggle changes width during animation in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/teams/components/Checkbox/checkboxVariables.ts
Labels: 🧰 fix

#2134 Adding component specs for Button, Checkbox, Icon, Link, Menu and Slider
  specs/Button.md
  specs/Checkbox.md
  specs/Icon.md
  specs/Link.md
  specs/Menu.md
  specs/Slider.md
Labels: 📚 docs

#2187 fix(Popper): improve positioning in multiple cases
  CHANGELOG.md
  packages/react/src/themes/teams/components/Popup/popupStyles.ts
  packages/react/src/utils/positioner/Popper.tsx
  packages/react/test/specs/utils/__snapshots__/felaRenderer-test.tsx.snap
  packages/react/test/specs/utils/felaRenderer-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#2141 feat(Divider): add vertical prop
  CHANGELOG.md
  docs/src/examples/components/Divider/Variations/DividerExampleVertical.shorthand.tsx
  docs/src/examples/components/Divider/Variations/index.tsx
  packages/react/src/components/Divider/Divider.tsx
  packages/react/src/themes/teams/components/Divider/dividerStyles.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#2195 fix(Tooltip): make tooltipAsLabelBehavior as default behavior
  CHANGELOG.md
  docs/src/examples/components/Tooltip/BestPractices/TooltipBestPractices.tsx
  packages/accessibility/src/behaviors/Menu/menuItemBehavior.ts
  packages/accessibility/src/behaviors/Tab/tabBehavior.ts
  packages/accessibility/src/behaviors/Toolbar/menuItemAsToolbarButtonBehavior.ts
  packages/accessibility/src/behaviors/Toolbar/toolbarMenuItemBehavior.ts
  packages/accessibility/src/behaviors/Tooltip/tooltipAsDescriptionBehavior.ts
  packages/accessibility/src/behaviors/Tooltip/tooltipAsLabelBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/accessibility/test/behaviors/behavior-test.tsx
  packages/accessibility/test/behaviors/testDefinitions.ts
  packages/react/src/components/Tooltip/Tooltip.tsx
Labels: accessibility, 🚀 ready for review

#2076 feat(button): Adding inverted button for Teams theme
  CHANGELOG.md
  docs/src/examples/components/Button/States/ButtonExampleDisabled.shorthand.tsx
  docs/src/examples/components/Button/States/ButtonExampleDisabled.tsx
  docs/src/examples/components/Button/Types/ButtonExampleInverted.tsx
  docs/src/examples/components/Button/Types/index.tsx
  docs/src/examples/components/Button/Usage/ButtonUsageExample.shorthand.tsx
  docs/src/examples/components/Button/Usage/index.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
Labels: teams theme, 💅 styling issue
