Repository microsoft/fluent-ui-react, pull requests merged in 2019-06, with the labels that each got.

#1405 feat(Checkbox): add component
  CHANGELOG.md
  docs/src/components/ExampleSnippet/renderElementToJSX.ts
  docs/src/examples/components/Checkbox/Playground.tsx
  docs/src/examples/components/Checkbox/Types/CheckboxExample.shorthand.steps.ts
  docs/src/examples/components/Checkbox/Types/CheckboxExample.shorthand.tsx
  docs/src/examples/components/Checkbox/Types/CheckboxExampleDisabled.shorthand.tsx
  docs/src/examples/components/Checkbox/Types/CheckboxExampleToggle.shorthand.steps.ts
  docs/src/examples/components/Checkbox/Types/CheckboxExampleToggle.shorthand.tsx
  docs/src/examples/components/Checkbox/Types/index.tsx
  docs/src/examples/components/Checkbox/index.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/Checkbox/checkboxBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/themes/base/componentStyles.ts
  packages/react/src/themes/base/componentVariables.ts
  packages/react/src/themes/base/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/base/components/Checkbox/checkboxVariables.ts
  packages/react/src/themes/base/components/Icon/iconNames.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/teams/components/Checkbox/checkboxVariables.ts
  packages/react/src/themes/teams/index.tsx
  packages/react/src/themes/types.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Checkbox/Checkbox-test.tsx
Labels: enhancement, ready for review

#1439 chore(package): update Popper.JS version
  packages/react/package.json
  yarn.lock
Labels: ready for merge

#1408 feat(Toolbar): add component
  CHANGELOG.md
  docs/src/app.tsx
  docs/src/examples/components/Toolbar/Types/ToolbarExampleEditor.shorthand.steps.ts
  docs/src/examples/components/Toolbar/Types/ToolbarExampleEditor.shorthand.tsx
  docs/src/examples/components/Toolbar/Types/index.tsx
  docs/src/examples/components/Toolbar/index.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarDivider.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarRadioGroup.tsx
  packages/react/src/index.ts
  packages/react/src/themes/base/componentStyles.ts
  packages/react/src/themes/base/components/Toolbar/toolbarStyles.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Toolbar/toolbarVariables.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarDividerStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarDividerVariables.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarItemVariables.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarVariables.ts
  packages/react/test/specs/components/Toolbar/Toolbar-test.ts
  packages/react/test/specs/components/Toolbar/ToolbarDivider-test.ts
  packages/react/test/specs/components/Toolbar/ToolbarItem-test.ts
  packages/react/test/specs/components/Toolbar/ToolbarRadioGroup-test.ts
Labels: ready for review

#1442 docs(Embed): update component's description, add example
  docs/src/examples/components/Embed/Slots/EmbedExampleIframe.shorthand.tsx
  docs/src/examples/components/Embed/Slots/index.tsx
  docs/src/examples/components/Embed/Types/EmbedExample.shorthand.tsx
  docs/src/examples/components/Embed/index.tsx
  packages/react/src/components/Embed/Embed.tsx
Labels: docs, ready for merge

#1421 chore(accessibility): refactor types
  CHANGELOG.md
  docs/src/prototypes/MenuButton/MenuButton.tsx
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Accordion/AccordionTitle.tsx
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Chat/Chat.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/List/List.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/index.ts
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/accessibility/Behaviors/Checkbox/checkboxBehavior.ts
  packages/react/src/lib/accessibility/reactTypes.ts
  packages/react/src/lib/accessibility/types.ts
  packages/react/src/lib/applyAccessibilityKeyHandlers.ts
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/createStardustComponent.tsx
  packages/react/src/lib/getKeyDownHandlers.ts
  packages/react/src/lib/keyboardHandlerFilter.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/lib/shouldHandleOnKeys.ts
  packages/react/test/specs/lib/shouldHandleOnKeys.ts
Labels: ready for merge

#1444 fix(attachment): action click
  CHANGELOG.md
  packages/react/src/themes/teams/getBorderFocusStyles.ts
Labels: fix, ready for review

#1448 fix(ListItem): end media in Teams theme breaks ButtonGroup styles
  CHANGELOG.md
  docs/src/examples/components/List/Variations/ListExampleTruncate.shorthand.tsx
  packages/react/src/themes/teams/components/List/listItemStyles.ts
Labels: ready for review

#1445 feat(attachmentBehavior): add "data-is-focusable" for attachment
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/Attachment/attachmentBehavior.ts
Labels: accessibility, enhancement, ready for review

#1441 chore(Dropdown): Add additional description for Left/Right arrow navigation
  docs/src/examples/components/Dropdown/Variations/DropdownExampleSearchMultipleFrenchLanguage.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/index.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: accessibility, ready for review

#1458 chore(eslint): add lint rule to disable access modifiers
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-projects/cra/App.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCopyLink.tsx
  docs/src/components/ComponentDoc/ComponentExamples.tsx
  docs/src/components/CopyToClipboard.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/IconViewer/index.tsx
  docs/src/prototypes/chatPane/chatPaneContent.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/mentions/PortalAtCursorPosition.ts
  packages/eslint-plugin/index.js
  packages/eslint-plugin/package.json
  packages/eslint-plugin/rules/no-visibility-modifiers/index.js
  packages/internal-tooling/eslint/index.js
  packages/internal-tooling/package.json
  packages/react-component-ref/src/RefForward.tsx
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Accordion/AccordionContent.tsx
  packages/react/src/components/Accordion/AccordionTitle.tsx
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Button/ButtonGroup.tsx
  packages/react/src/components/Chat/Chat.tsx
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownItem.tsx
  packages/react/src/components/Dropdown/DropdownSearchInput.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/src/components/Flex/Flex.tsx
  packages/react/src/components/Form/Form.tsx
  packages/react/src/components/Form/FormField.tsx
  packages/react/src/components/Grid/Grid.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/List/List.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/components/Reaction/Reaction.tsx
  packages/react/src/components/Reaction/ReactionGroup.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarRadioGroup.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/accessibility/FocusZone/AutoFocusZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/test/specs/behaviors/testHelper.tsx
  packages/react/test/specs/commonTests/stylesFunction-test.tsx
  packages/react/test/specs/lib/FocusTrapZone-test.tsx
  yarn.lock
Labels: ready for review

#1456 chore(behaviors): added tests for autoFocus and FocusTrap popup behaviors
  packages/react/src/lib/accessibility/Behaviors/Dialog/dialogBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupAutoFocusBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
  packages/react/test/specs/behaviors/popupAutoFocusBehavior-test.tsx
  packages/react/test/specs/behaviors/popupFocusTrapBehavior-test.tsx
Labels: accessibility, ready for review

#1436 chore(gulp): revert to gulpfile.ts
  .gulp.json
  babel.config.js
  babel.register.js
  build/gulp/plugins/gulp-example-source.ts
  build/gulp/tasks/test-projects.ts
  build/screener/screener.config.js
  build/webpack.config.ts
  docs/.babelrc
  gulpfile.ts
  package.json
  packages/docs-components/.babelrc
  packages/internal-tooling/babel/index.js
  packages/internal-tooling/babel/register.js
  packages/react-component-event-listener/.babelrc
  packages/react-component-nesting-registry/.babelrc
  packages/react-component-ref/.babelrc
  packages/react-proptypes/.babelrc
  packages/react/.babelrc
  perf/.babelrc
  yarn.lock
Labels: ready for review

#1473 docs: Remove Base and FontAwesome themes from themes dropdown
  CHANGELOG.md
  docs/src/context/ThemeContext.tsx
Labels: ready for review

#1464 fix(MenuItem): icon only active state in Teams theme
  CHANGELOG.md
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.steps.ts
  docs/src/examples/components/Menu/commonScreenerSteps.ts
  packages/react/src/themes/teams-high-contrast/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/components/Menu/menuItemStyles.ts
Labels: ready for review

#1476 perf(themes): use minified normalize.css in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/staticStyles/normalizeCSS.ts
Labels: ready for review

#1457 feat(Tree): expand all siblings on asterisk key
  CHANGELOG.md
  docs/src/examples/components/Tree/Types/TreeExample.shorthand.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Tree/subtreeBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
  packages/react/test/specs/components/Tree/Tree-test.tsx
Labels: accessibility, ready for review

#1469 chore(package): update Enzyme
  package.json
  packages/react/test/specs/commonTests/htmlIsAccessibilityCompliant.ts
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/specs/components/Popup/Popup-test.tsx
  packages/react/test/specs/components/Portal/Portal-test.tsx
  packages/react/test/utils/index.ts
  packages/react/test/utils/withProvider.tsx
  yarn.lock
Labels: ready for review

#1477 docs(CodeSnippet): add copy, support SSR
  docs/src/components/ColorBox.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/CopyToClipboard.tsx
  docs/src/prototypes/IconViewer/index.tsx
  packages/docs-components/package.json
  packages/docs-components/src/CodeSnippet/CodeSnippet.tsx
  packages/docs-components/src/CodeSnippet/CodeSnippetLabel.tsx
  packages/docs-components/src/CodeSnippet/formatCode.ts
  packages/docs-components/src/CodeSnippet/types.ts
  packages/docs-components/src/CopyToClipboard.tsx
  packages/docs-components/src/index.ts
  yarn.lock
Labels: ready for review

#1451 feat(Tree): left and right arrow keyboard navigation
  CHANGELOG.md
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/lib/accessibility/Behaviors/Tree/treeItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeTitleBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Tree/Tree-test.tsx
Labels: accessibility

#1482 fix(Popup): click/keypress handling logic for content
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
Labels: ready for review

#1481 feat(AccessibilityBehaviors): Define types for accessibility behaviors
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/Accordion/accordionBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Accordion/accordionContentBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Accordion/accordionTitleBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Alert/alertBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Alert/alertWarningBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Attachment/attachmentBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Button/buttonBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Button/toggleButtonBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Chat/chatMessageBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Checkbox/checkboxBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Dialog/dialogBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Embed/embedBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Grid/gridBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Icon/iconBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Image/imageBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Input/inputBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/basicListBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/basicListItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/listBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/listItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/selectableListBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/selectableListItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/menuBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/menuDividerBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/submenuBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupAutoFocusBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Radio/radioGroupBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Radio/radioGroupItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Status/statusBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tab/tabBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tab/tabListBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/menuAsToolbarBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/menuItemAsToolbarButtonBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/subtreeBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeTitleBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/defaultBehavior.ts
  packages/react/test/specs/behaviors/testDefinitions.ts
  packages/react/test/specs/components/Button/Button-test.tsx
Labels: accessibility, enhancement, ready for review

#1446 feat(Label): integrate with Dropdown
  CHANGELOG.md
  docs/src/examples/components/Form/Types/FormExampleDropdown.shorthand.tsx
  docs/src/examples/components/Form/Types/FormExampleDropdown.tsx
  docs/src/examples/components/Form/Types/index.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: accessibility, ready for review

#1483 feat(AutoControlledComponent): add getAutoControlledStateFromProps()
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/lib/AutoControlledComponent.tsx
  packages/react/test/specs/lib/AutoControlledComponent-test.tsx
Labels: ready for review

#1471 feat(popup): unstable_pinned prop
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Variations/DropdownExamplePosition.shorthand.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.shorthand.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/lib/positioner/types.ts
Labels: ready for review

#1491 chore(dangerjs): Check changelog entries' format
  CHANGELOG.md
  dangerfile.ts
Labels: ready for review

#1449 fix(dialogBehavior): move id generation to component
  CHANGELOG.md
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/lib/accessibility/Behaviors/Dialog/dialogBehavior.ts
  packages/react/test/specs/behaviors/dialogBehavior-test.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
  packages/react/test/specs/components/Dialog/Dialog-test.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/utils/findIntrinsicElement.ts
  packages/react/test/utils/index.ts
Labels: fix, ready for review

#1404 chore(babel): switch to Babel in distribution
  .browserslistrc
  build/gulp/tasks/bundle.ts
  build/tsconfig.commonjs.json
  build/tsconfig.es.json
  package.json
  packages/docs-components/package.json
  packages/docs-components/src/knobs/useKnobValues.ts
  packages/internal-tooling/babel/index.js
  packages/internal-tooling/package.json
  packages/react-component-event-listener/package.json
  packages/react-component-nesting-registry/package.json
  packages/react-component-ref/package.json
  packages/react-proptypes/package.json
  packages/react/package.json
  packages/react/src/index.ts
  packages/react/src/lib/index.ts
  yarn.lock
Labels: ready for review

#1489 docs(Knobs): fix registerKnob()
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleKnobs.tsx
  docs/src/components/ComponentPlayground.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.shorthand.tsx
  docs/src/examples/components/Popup/Variations/PopupExamplePosition.tsx
  docs/src/examples/components/Tooltip/States/TooltipOpenControlledExample.shorthand.tsx
  docs/src/examples/components/Tooltip/States/TooltipOpenControlledExample.tsx
  docs/src/examples/components/Tooltip/Variations/TooltipExamplePosition.shorthand.tsx
  docs/src/examples/components/Tooltip/Variations/TooltipExamplePosition.tsx
  packages/docs-components/src/index.ts
  packages/docs-components/src/knobs/KnobProvider.tsx
Labels: ready for review

#1480 feat(Toolbar): add popup prop
  CHANGELOG.md
  docs/src/examples/components/Toolbar/Types/ToolbarExampleEditor.shorthand.tsx
  docs/src/examples/components/Toolbar/Types/ToolbarExamplePopup.shorthand.steps.ts
  docs/src/examples/components/Toolbar/Types/ToolbarExamplePopup.shorthand.tsx
  docs/src/examples/components/Toolbar/Types/index.tsx
  packages/react-proptypes/src/index.ts
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/themes/types.ts
  packages/react/src/types.ts
Labels: ready for review

#1499 fix(Tooltip): prop types
  CHANGELOG.md
  packages/react/src/components/Tooltip/Tooltip.tsx
Labels: fix, ready for review

#1492 fix(Popup): fix styling with `pointer` when it is wrapped by FocusZones
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
Labels: fix, ready for review

#1494 feat(docs): improve color guide
  CHANGELOG.md
  docs/src/components/ColorBox.tsx
  docs/src/components/ColorSchemes.tsx
  docs/src/components/ColorVariants.tsx
  docs/src/components/Fader.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/routes.tsx
  docs/src/views/ColorPalette.tsx
  docs/src/views/ColorSchemes.tsx
  docs/src/views/Colors.tsx
  docs/src/views/Layout.tsx
  docs/src/views/ThemingExamples.tsx
Labels: ready for review

#1488 feat(Tree): integrate ARIA HTML design pattern
  CHANGELOG.md
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/lib/accessibility/Behaviors/Tree/subtreeBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeTitleBehavior.ts
  packages/react/src/lib/accessibility/types.ts
  packages/react/test/specs/behaviors/treeItemBehavior-test.tsx
  packages/react/test/specs/behaviors/treeTitleBehavior-test.tsx
  packages/react/test/specs/components/Tree/Tree-test.tsx
Labels: accessibility, ready for review

#1452 fix(attachment) - more option button invoke correctly action on space/enter
  packages/react/src/components/Attachment/Attachment.tsx
Labels: accessibility, ready for review

#1507 fix(Accessibility): Action handlers should respect modifiers
  packages/react/src/lib/shouldHandleOnKeys.ts
  packages/react/test/specs/lib/shouldHandleOnKeys-test.ts
Labels: accessibility, fix, ready for review

#1468 feat(Toolbar): Add toolbarBehavior and toolbarItemBehavior
  docs/src/examples/components/Toolbar/Types/ToolbarExampleEditor.shorthand.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/Button/buttonBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Button/toggleButtonBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: accessibility, enhancement, ready for merge

#1459 perf(render): use single Fela renderer
  CHANGELOG.md
  packages/react/package.json
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/lib/felaInvokeKeyframesPlugin.ts
  packages/react/src/lib/felaRenderKeyframesPlugin.ts
  packages/react/src/lib/felaRenderer.tsx
  packages/react/src/lib/getClasses.ts
  packages/react/src/lib/index.ts
  packages/react/src/lib/mergeProviderContexts.ts
  packages/react/src/themes/base/components/Loader/loaderStyles.ts
  packages/react/src/themes/teams/components/Loader/loaderStyles.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/lib/felaInvokeKeyframesPlugin-test.ts
  packages/react/test/specs/lib/felaRenderKeyframesPlugin-test.ts
  packages/react/test/specs/lib/mergeProviderContexts/mergeProviderContexts-test.ts
  yarn.lock
Labels: perf, ready for review

#1487 fix(styles): update definition of `FontFace` and rename `FontFaceStyle`
  CHANGELOG.md
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/themes/teams/fontFaces.ts
  packages/react/src/themes/types.ts
Labels: ready for review

#1508 fix(types): for theme
  CHANGELOG.md
  packages/react/src/themes/types.ts
Labels: fix, ready for review

#1522 docs(Menu): Improve Menu accessibility information
  packages/react/src/components/Menu/Menu.tsx
Labels: accessibility, ready for review

#1520 docs(Accessibility): Improve layout of behaviors pages
  docs/src/components/ComponentDoc/BehaviorDescription.tsx
  docs/src/components/DocsBehaviorRoot.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/lib/accessibility/Behaviors/Accordion/accordionBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Accordion/accordionContentBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Accordion/accordionTitleBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Alert/alertWarningBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Attachment/attachmentBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Checkbox/checkboxBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Dialog/dialogBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Embed/embedBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Loader/loaderBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/menuDividerBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupAutoFocusBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tab/tabBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tab/tabListBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/menuAsToolbarBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/menuItemAsToolbarButtonBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/subtreeBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeBehavior.ts
  packages/react/src/lib/getKeyDownHandlers.ts
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: accessibility, ready for review

#1516 feat(segment): disabled prop
  CHANGELOG.md
  docs/src/examples/components/Segment/States/SegmentExampleDisabled.shorthand.tsx
  docs/src/examples/components/Segment/States/SegmentExampleDisabled.tsx
  docs/src/examples/components/Segment/States/index.tsx
  docs/src/examples/components/Segment/index.tsx
  packages/react/src/components/Segment/Segment.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Segment/segmentVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Segment/segmentVariables.ts
  packages/react/src/themes/teams/components/Segment/segmentStyles.ts
  packages/react/src/themes/teams/components/Segment/segmentVariables.ts
Labels: fix, ready for review

#1515 fix(RadioGroup): First item should be tabbable by default when none of the items selected
  CHANGELOG.md
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Radio/radioGroupItemBehavior.ts
  packages/react/test/specs/components/RadioGroup/RadioGroup-test.tsx
Labels: accessibility, fix, ready for review

#1538 fix(Accessibility): Export all behaviors
  CHANGELOG.md
  packages/react/src/index.ts
Labels: accessibility, ready for review

#1505 fix(FocusTrapZone): Set focus into zone when inner content is lazy loaded
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx
  packages/react/test/specs/lib/FocusTrapZone-test.tsx
Labels: accessibility, fix, ready for review

#1556 chore(themes): enable all themes in dev mode
  docs/src/context/ThemeContext.tsx
  yarn.lock
Labels: ready for review

#1526 feat(Toolbar): Add ARIA attributes and focus handling for radio group
  CHANGELOG.md
  docs/src/examples/components/Toolbar/Content/ToolbarExampleRadioGroup.shorthand.steps.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleRadioGroup.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/index.tsx
  docs/src/examples/components/Toolbar/Types/ToolbarExampleEditor.shorthand.tsx
  packages/react/src/components/Toolbar/ToolbarRadioGroup.tsx
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarRadioGroupBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarRadioGroupItemBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Toolbar/ToolbarRadioGroup-test.tsx
Labels: accessibility, enhancement, ready for review

#1553 feat(Toolbar): Add ARIA attributes and keyboard handling for a menu
  CHANGELOG.md
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarItemBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/lib/applyAccessibilityKeyHandlers.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: accessibility, enhancement, ready for review

#1523 fix(Dropdown, DropdownItem, ListItem): Updating theme files
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/themes/teams-dark/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownItemStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams/components/List/listItemStyles.ts
Labels: ready for review

#1551 docs(Composition): add section about `as` prop and DOM attributes
  build/webpack.config.ts
  docs/src/components/DocsLayout.tsx
  docs/src/components/GuidesNavigationFooter.tsx
  docs/src/components/MarkdownPage.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/pages/Composition.mdx
  docs/src/routes.tsx
  package.json
  types/global.d.ts
  yarn.lock
Labels: docs, ready for review
