Repository microsoft/fluent-ui-react, pull requests merged in 2019-11, with the labels that each got.

#2079 feat(Provider): Rendering performance telemetry
  CHANGELOG.md
  docs/src/prototypes/customToolbar/index.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/lib/Telemetry.ts
  packages/react/src/lib/index.ts
  packages/react/src/lib/mergeProviderContexts.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/types.ts
Labels: 🚧 WIP

#2091 docs(Tooltip): add usage example for Tooltip on disabled elements
  CHANGELOG.md
  docs/src/examples/components/Tooltip/Usage/TooltipExampleDisabledTrigger.shorthand.tsx
  docs/src/examples/components/Tooltip/Usage/index.tsx
Labels: 📚 docs, 🚀 ready for review

#2099 feat(Table): base implementation
  CHANGELOG.md
  docs/src/components/ComponentPlayground/ComponentPlayground.tsx
  docs/src/examples/components/Table/Usage/TableExampleStatic.shorthand.tsx
  docs/src/examples/components/Table/Usage/TableExampleStatic.tsx
  docs/src/examples/components/Table/Usage/TableExampleStaticCompact.shorthand.tsx
  docs/src/examples/components/Table/Usage/TableExampleStaticHeadless.shorthand.tsx
  docs/src/examples/components/Table/Usage/TableExampleStaticRowless.shorthand.tsx
  docs/src/examples/components/Table/Usage/TableExampleStaticTruncate.shorthand.tsx
  docs/src/examples/components/Table/Usage/index.tsx
  docs/src/examples/components/Table/index.tsx
  packages/accessibility/src/behaviors/Table/tableBehavior.ts
  packages/accessibility/src/behaviors/Table/tableCellBehavior.ts
  packages/accessibility/src/behaviors/Table/tableHeaderCellBehavior.ts
  packages/accessibility/src/behaviors/Table/tableRowBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/accessibility/src/types.ts
  packages/accessibility/test/behaviors/behavior-test.tsx
  packages/react/src/components/Table/Table.tsx
  packages/react/src/components/Table/TableCell.tsx
  packages/react/src/components/Table/TableRow.tsx
  packages/react/src/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Table/tableCellStyles.ts
  packages/react/src/themes/teams/components/Table/tableCellVariables.ts
  packages/react/src/themes/teams/components/Table/tableRowStyles.ts
  packages/react/src/themes/teams/components/Table/tableRowVariables.ts
  packages/react/src/themes/teams/components/Table/tableStyles.ts
  packages/react/src/themes/teams/components/Table/tableVariables.ts
  packages/react/test/specs/components/Table/Table-test.tsx
  packages/react/test/specs/components/Table/TableCell-test.tsx
  packages/react/test/specs/components/Table/TableRow-test.tsx
Labels: 🚀 ready for review

#2093 docs(prototypes): Added prototype for hexagonal avatars
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/hexagonalAvatar/CustomAvatar.tsx
  docs/src/prototypes/hexagonalAvatar/index.tsx
  docs/src/routes.tsx
Labels: 🚀 ready for review, 🤖 prototype

#2105 fix(Ref): Apply unhandled props to the children if used
  CHANGELOG.md
  packages/react-component-ref/src/Ref.tsx
Labels: 🚀 ready for review

#2103 fix(Accessibility): allow focusing radio and checkbox in the focus zone
  CHANGELOG.md
  packages/accessibility/src/behaviors/Checkbox/checkboxBehavior.ts
  packages/accessibility/src/behaviors/Radio/radioGroupItemBehavior.ts
Labels: 🚀 ready for review

#2107 fix(menuButton) - accessibility - add aria-controls attribute, when exists
  CHANGELOG.md
  packages/accessibility/src/behaviors/MenuButton/menuButtonBehavior.ts
  packages/accessibility/test/behaviors/menuButtonBehavior-test.tsx
  packages/react/test/specs/components/MenuButton/MenuButton-test.tsx
Labels: accessibility, 🚀 ready for review

#2104 fix(Dialog): Content should have 100% width
  CHANGELOG.md
  docs/src/examples/components/Dialog/Content/DialogExampleFullWidth.shorthand.steps.ts
  docs/src/examples/components/Dialog/Content/DialogExampleFullWidth.shorthand.tsx
  packages/react/src/themes/teams/components/Dialog/dialogStyles.ts
Labels: 🚀 ready for review

#2098 fix(Button): Correcting button shadow opacity
  CHANGELOG.md
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: 🚀 ready for review

#2061 feat(Tree): control activeItemIds through expended prop of items
  CHANGELOG.md
  packages/accessibility/src/behaviors/Tree/treeItemBehavior.ts
  packages/accessibility/src/behaviors/Tree/treeTitleBehavior.ts
  packages/accessibility/test/behaviors/testDefinitions.ts
  packages/accessibility/test/behaviors/treeItemBehavior-test.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/test/specs/components/Tree/Tree-test.tsx
  packages/react/test/specs/components/Tree/TreeItem-test.tsx
  packages/react/test/specs/components/Tree/TreeTitle-test.tsx
Labels: ⚙️ enhancement, 🚀 ready for review

#1979 feat(Carousel): base component
  CHANGELOG.md
  docs/src/components/ComponentPlayground/ComponentPlayground.tsx
  docs/src/examples/components/Carousel/Types/CarouselExample.tsx
  docs/src/examples/components/Carousel/Types/CarouselPaginationExample.tsx
  docs/src/examples/components/Carousel/Types/index.tsx
  docs/src/examples/components/Carousel/Variations/CarouselCircularExample.tsx
  docs/src/examples/components/Carousel/Variations/index.tsx
  docs/src/examples/components/Carousel/index.tsx
  packages/accessibility/src/behaviors/Carousel/carouselBehavior.ts
  packages/accessibility/src/behaviors/Carousel/carouselItemBehavior.ts
  packages/accessibility/src/behaviors/Tab/tabBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/accessibility/src/types.ts
  packages/accessibility/test/behaviors/behavior-test.tsx
  packages/accessibility/test/behaviors/testDefinitions.ts
  packages/react/src/components/Carousel/Carousel.tsx
  packages/react/src/components/Carousel/CarouselItem.tsx
  packages/react/src/components/Carousel/CarouselNavigation.tsx
  packages/react/src/components/Carousel/CarouselNavigationItem.tsx
  packages/react/src/index.ts
  packages/react/src/lib/debounce.ts
  packages/react/src/lib/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Carousel/carouselItemStyles.ts
  packages/react/src/themes/teams/components/Carousel/carouselItemVariables.ts
  packages/react/src/themes/teams/components/Carousel/carouselNavigationItemStyles.ts
  packages/react/src/themes/teams/components/Carousel/carouselNavigationItemVariables.ts
  packages/react/src/themes/teams/components/Carousel/carouselNavigationStyles.ts
  packages/react/src/themes/teams/components/Carousel/carouselNavigationVariables.ts
  packages/react/src/themes/teams/components/Carousel/carouselStyles.ts
  packages/react/src/themes/teams/components/Carousel/carouselVariables.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/chevronEnd.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/chevronStart.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/withProcessedIcons.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/components/Carousel/Carousel-test.tsx
  packages/react/test/specs/components/Carousel/CarouselItem-test.tsx
  packages/react/test/specs/components/Carousel/CarouselNavigation-test.tsx
  packages/react/test/specs/components/Carousel/CarouselNavigationItem-test.tsx
Labels: new component, ⚙️ enhancement, 🚀 ready for review

#1951 feat(factories): use `children` in shorthands as render props
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleImageCustomization.shorthand.tsx
  docs/src/examples/components/Menu/Usage/MenuExampleWithTooltip.shorthand.tsx
  docs/src/examples/components/Toolbar/Performance/CustomToolbar.perf.tsx
  docs/src/examples/components/Toolbar/Usage/ToolbarExampleWithTooltip.shorthand.tsx
  docs/src/pages/ShorthandProps.mdx
  docs/src/prototypes/AsyncShorthand/AsyncShorthand.tsx
  docs/src/prototypes/CopyToClipboard/index.tsx
  docs/src/prototypes/EditorToolbar/EditorToolbar.tsx
  docs/src/prototypes/ParticipantsList/index.tsx
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/ChatWithPopover.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/src/lib/factories.ts
  packages/react/src/types.ts
  packages/react/test/specs/lib/factories-test.tsx
Labels: ⚙️ enhancement, 🚀 ready for review
