Repository microsoft/fluent-ui-react, pull requests merged in 2019-07, with the labels that each got.

#1558 feat(Toolbar): add `custom` kind of ToolbarItem
  CHANGELOG.md
  docs/src/examples/components/Toolbar/Content/ToolbarExampleCustomContent.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/index.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarCustomItem.tsx
  packages/react/src/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarCustomItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarCustomItemVariables.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarVariables.ts
  packages/react/test/specs/components/Toolbar/Toolbar-test.tsx
  packages/react/test/specs/components/Toolbar/ToolbarCustomItem-test.ts
Labels: enhancement, ready for review

#1568 docs: fix content overlap with sidebar
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
Labels: ready for review

#1557 perf(docs): remove DLL, use splitChunks & runtimeChunk
  .eslintignore
  .gitignore
  .prettierignore
  build/gulp/plugins/webpack-open-browser.ts
  build/gulp/tasks/dll.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/screener.ts
  build/gulp/tasks/test-circulars/index.ts
  build/gulp/tasks/test-projects.ts
  build/webpack.config.dll.ts
  build/webpack.config.ts
  config.ts
  gulpfile.ts
  package.json
  yarn.lock
Labels: chore, ready for review

#1576 docs(CodeSnippet): fixing issue with copy icon taking up entire page
  CHANGELOG.md
  packages/docs-components/src/CodeSnippet/CodeSnippetLabel.tsx
Labels: ready for review, styling issue

#1575 feat(Tooltip): Add accessibility attributes and keyboard handlers
  CHANGELOG.md
  docs/src/examples/components/Tooltip/Types/TooltipExample.shorthand.tsx
  docs/src/examples/components/Tooltip/Types/TooltipExample.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/lib/accessibility/Behaviors/Tooltip/tooltipBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/lib/getOrGenerateIdFromShorthand.ts
  packages/react/src/lib/index.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Tooltip/Tooltip-test.tsx
Labels: accessibility, enhancement

#1564 fix(Dropdown): fix Dropdown ArrowLeft keydown behavior for multiple variants
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: accessibility, ready for review

#1570 fix: refactored highlightedIndex on Arrow keydown
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: accessibility, ready for review

#1563 fix(createComponent): add static className prop
  CHANGELOG.md
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/createStardustComponent.tsx
  packages/react/test/specs/lib/createComponent-test.tsx
Labels: ready for review

#1578 feat(Checkbox): add `labelPosition` prop
  CHANGELOG.md
  docs/src/examples/components/Checkbox/Slots/CheckboxExampleLabel.shorthand.tsx
  docs/src/examples/components/Checkbox/Slots/index.tsx
  docs/src/examples/components/Checkbox/States/CheckboxExampleChecked.shorthand.tsx
  docs/src/examples/components/Checkbox/States/CheckboxExampleDisabled.shorthand.tsx
  docs/src/examples/components/Checkbox/States/index.tsx
  docs/src/examples/components/Checkbox/Types/index.tsx
  docs/src/examples/components/Checkbox/index.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/themes/base/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/base/components/Checkbox/checkboxVariables.ts
Labels: enhancement, ready for review

#1562 feat(Icon): add props arg to SVG spec
  CHANGELOG.md
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Icon/iconVariables.ts
  packages/react/src/themes/types.ts
Labels: ready for review

#1561 fix(Popup): update styles for popup colors in Teams themes
  CHANGELOG.md
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Popup/popupContentVariables.ts
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
  packages/react/src/themes/teams/components/Popup/popupContentVariables.ts
Labels: ready for review

#1580 feat(Tooltip): add svg beak in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Tooltip/tooltipContentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Tooltip/tooltipVariables.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentStyles.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentVariables.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipStyles.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipVariables.ts
  packages/react/src/themes/teams/getPointerStyles.ts
  packages/react/src/themes/teams/pointerSvgUrl.ts
Labels: ready for review

#1541 docs(Toolbar): Prototype for custom toolbar
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Button/Playground.tsx
  docs/src/prototypes/customToolbar/CustomToolbar.tsx
  docs/src/prototypes/customToolbar/darkThemeOverrides.ts
  docs/src/prototypes/customToolbar/highContrastThemeOverrides.ts
  docs/src/prototypes/customToolbar/index.tsx
  docs/src/routes.tsx
Labels: docs, ready for review

#1581 feat(color): add new colors and schema tokens in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams-dark/colors.ts
  packages/react/src/themes/teams-high-contrast/colors.ts
  packages/react/src/themes/teams/colors.ts
Labels: ready for review

#1260 chore(deployment): add dynamic deployment with now.sh
  .eslintignore
  .gitignore
  .nowignore
  build/gulp/plugins/gulp-doctoc.ts
  config.ts
  now.json
  package.json
Labels: chore, ready for review

#1595 docs(Layout): update documentation page
  CHANGELOG.md
  docs/src/components/ExampleSnippet/ExampleSnippet.tsx
  docs/src/components/ExampleSnippet/renderElementToJSX.ts
  docs/src/examples/components/Flex/Recipes.mdx
  docs/src/examples/components/Flex/index.tsx
  docs/src/pages/Layout.mdx
  docs/src/public/images/flex-column.svg
  docs/src/public/images/flex.svg
  docs/src/public/images/grid-page.svg
  docs/src/public/images/grid.svg
  docs/src/routes.tsx
Labels: docs, ready for review

#1619 docs(ExampleSnippet): fix error when children are missing
  CHANGELOG.md
  docs/src/components/ExampleSnippet/ExampleSnippet.tsx
Labels: ready for review

#1565 fix(Popup): Move `trapFocus` and `autoFocus` to props from accessibility behaviors
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupFocusTrapExample.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOnWithFocusTrap.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExampleFocusTrapped.shorthand.tsx
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/ReactionPopup.tsx
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/AccessibilityBehaviors.tsx
  docs/src/views/AutoFocusZone.tsx
  docs/src/views/FocusTrapZone.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Dialog/dialogBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupAutoFocusBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/lib/accessibility/types.ts
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/behaviors/popupAutoFocusBehavior-test.tsx
  packages/react/test/specs/behaviors/popupFocusTrapBehavior-test.tsx
  packages/react/test/specs/components/Popup/Popup-test.tsx
Labels: accessibility, enhancement, fix, ready for review

#1600 chore(accessibility): remove `defaultBehavior`
  .github/add-a-feature.md
  CHANGELOG.md
  docs/src/prototypes/MenuButton/MenuButton.tsx
  docs/src/prototypes/MenuButton/menuButtonBehavior.ts
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Avatar/Avatar.tsx
  packages/react/src/components/Button/ButtonGroup.tsx
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Divider/Divider.tsx
  packages/react/src/components/Form/Form.tsx
  packages/react/src/components/Form/FormField.tsx
  packages/react/src/components/Grid/Grid.tsx
  packages/react/src/components/Header/Header.tsx
  packages/react/src/components/Header/HeaderDescription.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/Label/Label.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Reaction/Reaction.tsx
  packages/react/src/components/Reaction/ReactionGroup.tsx
  packages/react/src/components/Segment/Segment.tsx
  packages/react/src/components/Text/Text.tsx
  packages/react/src/components/Toolbar/ToolbarCustomItem.tsx
  packages/react/src/components/Toolbar/ToolbarDivider.tsx
  packages/react/src/components/Toolbar/ToolbarMenuDivider.tsx
  packages/react/src/components/Tooltip/TooltipContent.tsx
  packages/react/src/components/Video/Video.tsx
  packages/react/src/lib/accessibility/Behaviors/Alert/alertBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/defaultBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/lib/accessibility/reactTypes.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/test/specs/behaviors/alertBehavior-test.tsx
  packages/react/test/specs/commonTests/handlesAccessibility.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
Labels: chore, ready for review

#1559 feat(slider): v1
  CHANGELOG.md
  docs/src/examples/components/Slider/Playground.tsx
  docs/src/examples/components/Slider/Rtl/SliderExample.rtl.steps.ts
  docs/src/examples/components/Slider/Rtl/SliderExample.rtl.tsx
  docs/src/examples/components/Slider/Rtl/index.tsx
  docs/src/examples/components/Slider/States/SliderExampleDisabled.shorthand.tsx
  docs/src/examples/components/Slider/States/index.tsx
  docs/src/examples/components/Slider/Types/SliderExample.shorthand.steps.ts
  docs/src/examples/components/Slider/Types/SliderExample.shorthand.tsx
  docs/src/examples/components/Slider/Types/index.tsx
  docs/src/examples/components/Slider/Usage/SliderExampleAction.shorthand.tsx
  docs/src/examples/components/Slider/Usage/index.tsx
  docs/src/examples/components/Slider/Variations/SliderExampleFluid.shorthand.tsx
  docs/src/examples/components/Slider/Variations/SliderExampleVertical.shorthand.tsx
  docs/src/examples/components/Slider/Variations/index.tsx
  docs/src/examples/components/Slider/commonScreenerSteps.ts
  docs/src/examples/components/Slider/index.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/Slider/Slider.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/Slider/sliderBehavior.tsx
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/lib/htmlPropsUtils.tsx
  packages/react/src/themes/base/componentStyles.ts
  packages/react/src/themes/base/componentVariables.ts
  packages/react/src/themes/base/components/Slider/sliderStyles.ts
  packages/react/src/themes/base/components/Slider/sliderVariables.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Slider/sliderStyles.ts
  packages/react/src/themes/teams/components/Slider/sliderVariables.ts
  packages/react/src/themes/teams/getBorderFocusStyles.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Slider/Slider-test.tsx
Labels: architecture, new component, ready for review

#1638 fix(docs): ChatWithPopover prototype action menu regression after the factories updates
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/ChatWithPopover.tsx
Labels: fix, prototype, ready for review

#1637 fix(ChatMessage): chat message focus is overlaying message actions in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: fix, ready for review

#1631 docs(Menu): small fix in best practices DOs section
  docs/src/examples/components/Menu/BestPractices/MenuBestPractices.tsx
  packages/react/src/components/Menu/Menu.tsx
Labels: fix, ready for review

#1635 feat(Tooltip): Add label behavior for Tooltip
  CHANGELOG.md
  docs/src/examples/components/Tooltip/BestPractices/TooltipBestPractices.tsx
  docs/src/examples/components/Tooltip/BestPractices/index.tsx
  docs/src/examples/components/Tooltip/index.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/lib/accessibility/Behaviors/Tooltip/tooltipAsLabelBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
Labels: accessibility, enhancement, ready for review

#1641 docs(slider): best practices and usage in form
  CHANGELOG.md
  docs/src/examples/components/Form/Types/FormExampleSlider.shorthand.tsx
  docs/src/examples/components/Form/Types/FormExampleSlider.tsx
  docs/src/examples/components/Form/Types/index.tsx
  docs/src/examples/components/Slider/BestPractices/SliderBestPractices.tsx
  docs/src/examples/components/Slider/BestPractices/index.tsx
  docs/src/examples/components/Slider/Usage/SliderExampleForm.shorthand.tsx
  docs/src/examples/components/Slider/Usage/index.tsx
  docs/src/examples/components/Slider/index.tsx
Labels: docs, ready for review

#1654 docs(perf): improve rendering perf for examples
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ExamplePlaceholder.tsx
  package.json
  yarn.lock
Labels: ready for review

#1667 feat(Popup): altered controlled example to contain close icon in the content
  docs/src/examples/components/Popup/Types/PopupControlledExample.shorthand.steps.ts
  docs/src/examples/components/Popup/Types/PopupControlledExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupControlledExample.tsx
Labels: ready for review

#1623 feat(icon): adding menu's outline icon and Visio icon to Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/icons/filesVisio.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/menu.tsx
Labels: ready for review

#1524 feat(Popup): show on `contextmenu`
  CHANGELOG.md
  build/gulp/tasks/test-projects/rollup/rollup.config.js
  docs/src/examples/components/Popup/Usage/PopupExampleContextOnElement.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOn.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOnMultiple.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOnWithFocusTrap.shorthand.tsx
  docs/src/examples/components/Popup/Usage/index.tsx
  docs/src/views/Accessibility.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/createReferenceFromContextClick.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  packages/react/src/lib/isRightClick.ts
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/lib/positioner/types.ts
  packages/react/test/specs/behaviors/dialogBehavior-test.tsx
  packages/react/test/specs/behaviors/popupBehavior-test.tsx
  packages/react/test/specs/components/Popup/Popup-test.tsx
Labels: ready for review

#1690 feat(renderComponent): remove `focusZoneRef`
  docs/src/routes.tsx
  docs/src/views/AutoFocusZoneDoc.tsx
  docs/src/views/FocusTrapZoneDoc.tsx
  docs/src/views/FocusZoneDoc.tsx
  packages/react/src/components/Chat/Chat.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/accessibility/Behaviors/Chat/chatBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Chat/chatMessageBehavior.ts
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/renderComponent.tsx
Labels: accessibility, enhancement, ready for review

#1683 fix(Checkbox): fix gap styling in RTL
  CHANGELOG.md
  docs/src/examples/components/Checkbox/Rtl/CheckboxExample.rtl.tsx
  docs/src/examples/components/Checkbox/Rtl/index.tsx
  docs/src/examples/components/Checkbox/index.tsx
  packages/react/src/themes/base/components/Checkbox/checkboxStyles.ts
Labels: fix, ready for review

#1646 feat(docs): add FAQ entry for Flex, Grid, Layout, Box, Segment
  CHANGELOG.md
  docs/src/views/FAQ.tsx
Labels: docs, ready for review

#1691 fix(factories): fix key handling on React.Element
  packages/react/src/lib/factories.ts
  packages/react/test/specs/lib/factories-test.tsx
Labels: fix, ready for review

#1702 fix(Dialog|Segment): update support of `color` prop
  CHANGELOG.md
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Segment/Segment.tsx
Labels: fix, ready for review

#1701 fix(Loader): use Text component for `label` slot
  CHANGELOG.md
  packages/react/src/components/Loader/Loader.tsx
Labels: fix, ready for review

#1704 docs(Button): separate overflow example
  docs/src/examples/components/Button/Types/ButtonExample.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExample.tsx
  docs/src/examples/components/Button/Usage/ButtonExampleOverflow.shorthand.tsx
  docs/src/examples/components/Button/Usage/ButtonExampleOverflow.tsx
  docs/src/examples/components/Button/Usage/index.tsx
Labels: docs

#1707 chore(dangerjs): fix path to CHANGELOG.md
  build/dangerjs/checkChangelog.ts
Labels: fix, ready for review

#1706 fix(Dialog): support nested Dialogs and Popups
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/NestedPopupsAndDialogs/index.tsx
  docs/src/routes.tsx
  e2e/e2eApi.ts
  e2e/tests/dialogInDialog-example.tsx
  e2e/tests/dialogInDialog-test.ts
  e2e/tests/dialogInPopup-example.tsx
  e2e/tests/dialogInPopup-test.ts
  e2e/tsconfig.json
  packages/react-component-nesting-registry/src/types.ts
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/lib/handleRef.ts
Labels: fix, ready for review

#1656 fix(Checkbox): refined styles to match redline and add dark and contrast theme
  CHANGELOG.md
  docs/src/examples/components/Checkbox/States/CheckboxExampleDisabled.shorthand.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/themes/base/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/base/components/Checkbox/checkboxVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Checkbox/checkboxVariables.ts
  packages/react/src/themes/teams/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/teams/components/Checkbox/checkboxVariables.ts
  packages/react/src/themes/teams/components/Icon/svg/icons/stardustCircle.tsx
Labels: ready for review

#1668 feat(Text): add align prop
  CHANGELOG.md
  docs/src/components/ComponentDoc/ExampleSection.tsx
  docs/src/components/DocPage/DocPage.tsx
  docs/src/examples/components/Header/Variations/HeaderExample.shorthand.tsx
  docs/src/examples/components/Header/Variations/HeaderExampleAlign.tsx
  docs/src/examples/components/Header/Variations/HeaderExampleTextAlign.shorthand.tsx
  docs/src/examples/components/Header/Variations/HeaderExampleTextAlign.tsx
  docs/src/examples/components/Header/Variations/index.tsx
  docs/src/examples/components/Text/Variations/TextExampleAlign.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleAlign.tsx
  docs/src/examples/components/Text/Variations/index.tsx
  docs/src/prototypes/IconViewer/index.tsx
  docs/src/views/PageNotFound.tsx
  packages/react-proptypes/src/index.ts
  packages/react/src/components/Header/Header.tsx
  packages/react/src/components/Text/Text.tsx
  packages/react/src/lib/commonPropInterfaces.ts
  packages/react/src/styles/translateAlignProp.ts
  packages/react/src/themes/base/components/Text/textStyles.ts
  packages/react/src/themes/teams/components/Header/headerStyles.ts
  packages/react/src/themes/teams/components/Text/textStyles.ts
Labels: ready for review

#1670 docs(Playground): add auto generated playgrounds
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentPlayground.tsx
  docs/src/components/ComponentPlayground/ComponentPlayground.tsx
  docs/src/components/ComponentPlayground/ComponentPlaygroundSnippet.tsx
  docs/src/components/ComponentPlayground/ComponentPlaygroundTemplate.tsx
  docs/src/components/ComponentPlayground/componentGenerators.ts
  docs/src/components/ComponentPlayground/createHookGenerator.ts
  docs/src/components/ComponentPlayground/propGenerators.tsx
  docs/src/components/ComponentPlayground/typeGenerators.ts
  docs/src/components/ComponentPlayground/usePlaygroundComponent.tsx
  docs/src/components/ComponentPlaygroundSnippet.tsx
  docs/src/examples/components/Button/Playground.tsx
  docs/src/examples/components/Checkbox/Playground.tsx
  docs/src/examples/components/Header/Playground.tsx
  docs/src/examples/components/Slider/Playground.tsx
  docs/src/public/images/tears-of-steel.jpg
  docs/src/types.ts
  packages/docs-components/src/index.ts
  packages/docs-components/src/knobs/KnobInspector.tsx
  packages/docs-components/src/knobs/defaultComponents.tsx
  packages/docs-components/src/knobs/types.ts
  packages/docs-components/src/knobs/useNumberKnob.ts
  packages/docs-components/src/knobs/useSelectKnob.ts
  packages/react/src/components/Loader/Loader.tsx
Labels: docs, ready for review

#1716 feat(Button): add `size` prop
  CHANGELOG.md
  docs/src/examples/components/Button/Variations/ButtonExampleSize.shorthand.tsx
  docs/src/examples/components/Button/Variations/index.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
Labels: enhancement, ready for review

#1688 fix(Toolbar): close menu when it looses focus
  CHANGELOG.md
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarItemBehavior.ts
Labels: accessibility, fix, ready for review

#1252 feat(Provider): allow to render to multiple documents
  CHANGELOG.md
  build/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
  build/dangerjs/detectNonApprovedDependencies/utils/getVersionConstrains.ts
  docs/src/components/ComponentPlayground/usePlaygroundComponent.tsx
  docs/src/components/Playground/renderConfig.ts
  docs/src/examples/components/Provider/Usage/ProviderExampleTarget.tsx
  docs/src/examples/components/Provider/Usage/index.tsx
  docs/src/examples/components/Provider/index.tsx
  packages/react/package.json
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/Provider/ProviderConsumer.tsx
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/felaRenderer.tsx
  packages/react/src/themes/teams/components/ItemLayout/itemLayoutStyles.ts
  packages/react/src/themes/types.ts
  packages/react/test/utils/withProvider.tsx
  yarn.lock
Labels: enhancement, ready for review

#1729 feat(Grid): Expose `isFromKeyboard` prop
  CHANGELOG.md
  packages/react/src/components/Grid/Grid.tsx
Labels: enhancement, ready for review

#1626 fix(docs): changing component variables example snippet
  CHANGELOG.md
  docs/src/views/ThemingExamples.tsx
Labels: docs, ready for review

#1723 fix(Icon): make "name" prop required
  CHANGELOG.md
  packages/react/src/components/Icon/Icon.tsx
  packages/react/test/specs/commonTests/implementsShorthandProp.tsx
  packages/react/test/specs/components/Attachment/Attachment-test.tsx
  packages/react/test/specs/components/Button/Button-test.tsx
  packages/react/test/specs/components/Icon/Icon-test.tsx
  packages/react/test/specs/components/Input/Input-test.tsx
  packages/react/test/specs/components/Label/Label-test.tsx
Labels: fix, ready for review

#1732 fix(FocusTrapZone): firstFocusableSelector is fragile
  CHANGELOG.md
  docs/src/views/AutoFocusZoneDoc.tsx
  packages/react/src/lib/accessibility/FocusZone/AutoFocusZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/test/specs/lib/AutoFocusZone-test.tsx
Labels: accessibility, fix, ready for review

#1428 docs(Examples): fix Grid variables to fix gaps in Firefox
  CHANGELOG.md
  packages/react/src/themes/base/components/Grid/gridVariables.ts
Labels: ready for review

#1721 feat(List): add horizontal prop
  CHANGELOG.md
  docs/src/examples/components/List/Variations/ListExampleHorizontal.shorthand.tsx
  docs/src/examples/components/List/Variations/index.tsx
  packages/react/src/components/List/List.tsx
  packages/react/src/lib/accessibility/Behaviors/List/listBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/List/selectableListBehavior.ts
  packages/react/src/themes/teams/components/List/listStyles.ts
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: ready for review

#1740 chore(FocusZone): Update FocusZone changelog
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
Labels: ready for review
