Repository microsoft/fluent-ui-react, pull requests merged in 2019-04, with the labels that each got.

#1133 feat(Icon): export `flag` icon in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/icons/flag.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/index.ts
Labels: ready for review

#1125 feat(Menu): Make Submenu open state controlled
  CHANGELOG.md
  docs/src/examples/components/Menu/Slots/MenuExampleSlot.shorthand.steps.ts
  docs/src/examples/components/Menu/Slots/MenuExampleSlot.shorthand.tsx
  docs/src/examples/components/Menu/Slots/index.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleWithSubmenuControlled.shorthand.tsx
  docs/src/examples/components/Menu/Usages/index.tsx
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/lib/AutoControlledComponent.tsx
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  packages/react/test/specs/lib/AutoControlledComponent-test.tsx
Labels: enhancement, ready for review

#1132 fix(EventListener): do not rerender on `listener` prop change
  CHANGELOG.md
  packages/react-component-event-listener/src/EventListener.ts
  packages/react-component-event-listener/src/StackableEventListener.ts
  packages/react-component-event-listener/src/lib/shouldUpdateListener.ts
  packages/react-component-event-listener/test/EventListener-test.tsx
Labels: fix, ready for review

#1136 test(projects): add browser step
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-projects/rollup/index.html
  config.ts
  package.json
  yarn.lock
Labels: ready for review

#1147 chore(package): require React 16.8
  CHANGELOG.md
  package.json
  packages/react-component-event-listener/package.json
  packages/react-component-nesting-registry/package.json
  packages/react/package.json
  yarn.lock
Labels: ready for review

#1127 fix(layout): remove truncate* props from Layout and ItemLayout
  CHANGELOG.md
  docs/src/examples/components/ItemLayout/Variations/ItemLayoutExampleTruncate.knobs.tsx
  docs/src/examples/components/ItemLayout/Variations/ItemLayoutExampleTruncate.shorthand.tsx
  docs/src/examples/components/ItemLayout/Variations/index.tsx
  docs/src/examples/components/ItemLayout/index.tsx
  docs/src/examples/components/Layout/index.tsx
  packages/react/src/components/ItemLayout/ItemLayout.tsx
  packages/react/src/components/Layout/Layout.tsx
  packages/react/src/themes/teams/components/Layout/layoutStyles.ts
Labels: ready for review

#1148 fix: remove inferior <-> index circular dependencies
  CHANGELOG.md
  build/gulp/plugins/util/getComponentInfo.ts
  packages/react/src/components/Ref/RefFindNode.tsx
  packages/react/src/components/Ref/RefForward.tsx
  packages/react/src/lib/renderComponent.tsx
Labels: fix, ready for review

#1154 feat(docs): links to layout documentation
  docs/src/components/ComponentDoc/Suggestions.tsx
  docs/src/examples/components/Box/index.tsx
  docs/src/examples/components/ItemLayout/index.tsx
  docs/src/examples/components/Layout/Types/LayoutExample.shorthand.tsx
  docs/src/examples/components/Layout/Types/LayoutExampleVertical.shorthand.tsx
  docs/src/examples/components/Layout/Variations/LayoutExample.shorthand.tsx
  docs/src/examples/components/Layout/Variations/LayoutExampleDisappearing.shorthand.tsx
  docs/src/examples/components/Layout/Variations/LayoutExampleGap.shorthand.tsx
  docs/src/examples/components/Layout/Variations/LayoutExampleReducing.shorthand.tsx
  docs/src/examples/components/Layout/index.tsx
Labels: ready for review

#1151 feat(what-input): add functionality for changing the currentInput
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/lib/whatInput.ts
Labels: ready for review

#1157 fix(Icons): fixing errors with brand icons
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/icons/filesExcelBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesOneNoteBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesPowerPointBrand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/filesWordBrand.tsx
Labels: ready for review

#1135 chore(Test): add filename filter
  build/gulp/tasks/test-unit.ts
Labels: ready for review

#1106 perf(Theme): performance measures for Context usage
  build/gulp/tasks/perf.ts
  build/webpack.config.perf.ts
  docs/src/components/Playground/renderConfig.ts
  docs/src/examples/components/Box/index.tsx
  docs/src/index.ejs
  package.json
  perf/src/index.html
  perf/src/index.tsx
  perf/types.tsx
  yarn.lock
Labels: perf, ready for review

#1162 chore: add circular dependencies check
  .circleci/config.yml
  build/gulp/plugins/gulp-webpack.ts
  build/gulp/tasks/test-circulars/config.ts
  build/gulp/tasks/test-circulars/index.ts
  build/gulp/tasks/test-circulars/utils.ts
  gulpfile.ts
  package.json
  packages/react/src/themes/teams/components/Icon/svg/icons/callPstn.tsx
  yarn.lock
Labels: ready for review

#1150 fix(dropdown): fixes tab focus on closed list
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: ready for review

#1167 docs(contributing): update docs, remove info about `yarn generate`
  .github/CONTRIBUTING.md
  .github/add-a-feature.md
Labels: docs, ready for review

#1175 fix(MenuItem): click triggering logic on Space and Enter key press
  CHANGELOG.md
  packages/react/src/components/Menu/MenuItem.tsx
Labels: ready for review

#1180 fix(FocusTrapZone): do not propagate any keyboard events
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
Labels: fix, ready for review

#1152 feat(Reaction): add styles for dark and hoc Teams theme
  CHANGELOG.md
  docs/src/prototypes/chatMessages/MessageReactionsWithPopup/index.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Reaction/reactionVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Reaction/reactionVariables.ts
  packages/react/src/themes/teams/components/Reaction/reactionStyles.ts
  packages/react/src/themes/teams/components/Reaction/reactionVariables.ts
Labels: ready for review

#1166 docs(Accessibility): Add documentation on Focus Zones and overall improvements
  docs/src/routes.tsx
  docs/src/utils/helpers.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/AccessibilityBehaviors.tsx
  docs/src/views/AutoFocusZone.tsx
  docs/src/views/FocusTrapZone.tsx
  docs/src/views/FocusZone.tsx
  docs/src/views/Layout.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx
Labels: docs

#1182 feat(Grid|Image): move styles to base theme
  CHANGELOG.md
  packages/react/src/themes/base/componentStyles.ts
  packages/react/src/themes/base/componentVariables.ts
  packages/react/src/themes/base/components/Grid/gridStyles.ts
  packages/react/src/themes/base/components/Grid/gridVariables.ts
  packages/react/src/themes/base/components/Image/imageStyles.ts
  packages/react/src/themes/base/components/Image/imageVariables.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
Labels: ready for merge

#1164 test(projects): add a new check to ensure that typings are correct
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-projects/typings/index.tsx
  build/gulp/tasks/test-projects/typings/tsconfig.json
Labels: ready for review

#1183 fix: escape behavior of popup and dropdown
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Popup/Popup.tsx
Labels: ready for review

#1033 fix(attachment): themeing and redline
  CHANGELOG.md
  docs/src/examples/components/Attachment/Slots/AttachmentActionExample.shorthand.tsx
  docs/src/examples/components/Attachment/Types/AttachmentProgressExample.shorthand.tsx
  docs/src/examples/components/Attachment/Variations/AttachmentActionableExample.shorthand.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Attachment/attachmentVariables.ts
  packages/react/src/themes/teams-dark/siteVariables.ts
  packages/react/src/themes/teams-high-contrast/componentStyles.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Attachment/attachmentVariables.ts
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Attachment/attachmentVariables.ts
Labels: ready for review

#1163 perf(renderComponent): drop FelaTheme and use React.Context directly
  CHANGELOG.md
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/renderComponent.tsx
Labels: perf, ready for review

#1184 chore(tslib): optimize imports
  CHANGELOG.md
  build/tsconfig.common.json
  build/tsconfig.es.json
  packages/react-component-event-listener/package.json
  packages/react-component-nesting-registry/package.json
  packages/react-proptypes/package.json
  packages/react/package.json
Labels: ready for review

#1192 fix(docs): fix code example of theming guide
  CHANGELOG.md
  docs/src/views/ThemingExamples.tsx
Labels: ready for review

#1190 fix(Theme): Use global REM-base, do not set html font-size in static styles
  CHANGELOG.md
  docs/src/app.tsx
  docs/src/index.ejs
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/lib/fontSizeUtility.ts
  packages/react/src/lib/index.ts
  packages/react/src/themes/teams/siteVariables.ts
  packages/react/src/themes/teams/staticStyles/globalStyles.ts
  packages/react/src/themes/types.ts
Labels: ready for review

#1197 fix(MenuItem): prop types
  CHANGELOG.md
  packages/react/src/components/Menu/MenuItem.tsx
Labels: ready for review

#1195 fix(grid): move focus outline inside grid items
  CHANGELOG.md
  docs/src/examples/components/Grid/Variations/GridExampleKeyboardNavigable.shorthand.tsx
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/components/Grid/gridStyles.ts
Labels: ready for review

#1108 feat(Embed|Video): add components
  CHANGELOG.md
  docs/src/examples/components/Embed/Types/EmbedExample.shorthand.tsx
  docs/src/examples/components/Embed/Types/index.tsx
  docs/src/examples/components/Embed/index.tsx
  docs/src/examples/components/Video/Types/VideoExample.shorthand.tsx
  docs/src/examples/components/Video/Types/index.tsx
  docs/src/examples/components/Video/index.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/Video/Video.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/Embed/embedBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/themes/base/components/Icon/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Embed/embedStyles.ts
  packages/react/src/themes/teams/components/Embed/embedVariables.ts
  packages/react/src/themes/teams/components/Video/videoStyles.ts
  packages/react/src/themes/teams/components/Video/videoVariables.ts
  packages/react/src/themes/teams/index.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/components/Embed/Embed-test.tsx
  packages/react/test/specs/components/Video/Video-test.tsx
Labels: enhancement, ready for review

#1204 test(Reaction): add tests for dark and hoc teams Theme
  docs/src/examples/components/Chat/Content/ChatExampleReactionGroupMeReacting.shorthand.steps.ts
  docs/src/examples/components/Chat/Content/ChatExampleReactionGroupMeReacting.shorthand.tsx
  docs/src/examples/components/Chat/Content/index.tsx
Labels: ready for review

#1202 chore: disable bundle stat collection/save for dev branches
  .circleci/config.yml
Labels: ready for review

#1208 fix(docs): Fix routing for accessibility documentation
  CHANGELOG.md
  docs/src/views/Accessibility.tsx
  docs/src/views/AccessibilityBehaviors.tsx
  docs/src/views/AutoFocusZone.tsx
  docs/src/views/FocusTrapZone.tsx
  docs/src/views/FocusZone.tsx
Labels: fix, ready for review

#1212 fix(Dialog): update type for `content` prop
  CHANGELOG.md
  packages/react/src/components/Dialog/Dialog.tsx
Labels: fix, ready for review

#1206 feat(Flex): move styles to base theme
  CHANGELOG.md
  packages/react/src/themes/base/componentStyles.ts
  packages/react/src/themes/base/componentVariables.ts
  packages/react/src/themes/base/components/Flex/flexItemStyles.ts
  packages/react/src/themes/base/components/Flex/flexItemVariables.ts
  packages/react/src/themes/base/components/Flex/flexStyles.ts
  packages/react/src/themes/base/components/Flex/flexVariables.ts
  packages/react/src/themes/base/components/Flex/utils.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
Labels: ready for review

#1057 feat(theme): add box-sizing to the global styles (Teams theme)
  CHANGELOG.md
  docs/src/prototypes/chatPane/composeMessage.tsx
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Avatar/avatarStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams/components/Embed/embedStyles.ts
  packages/react/src/themes/teams/components/Input/inputStyles.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  packages/react/src/themes/teams/components/Status/statusStyles.ts
  packages/react/src/themes/teams/components/Video/videoStyles.ts
  packages/react/src/themes/teams/staticStyles/globalStyles.ts
Labels: ready for review

#1218 fix(List): reduce number of rendered DOM nodes
  CHANGELOG.md
  packages/react/src/components/List/ListItem.tsx
Labels: fix, ready for review

#1198 feat(Popup): add `pointing` prop
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupExamplePointing.shorthand.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Popup/popupVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Popup/popupVariables.ts
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
  packages/react/src/themes/teams/components/Popup/popupContentVariables.ts
  packages/react/src/themes/teams/components/Popup/popupStyles.ts
  packages/react/src/themes/teams/components/Popup/popupVariables.ts
  packages/react/test/specs/components/Popup/Popup-test.tsx
Labels: enhancement, ready for review

#1222 fix(List): apply gaps on `ListItem.main`
  docs/src/examples/components/List/Variations/ListExampleFixedTruncate.shorthand.tsx
  docs/src/examples/components/List/Variations/index.tsx
  packages/react/src/components/List/ListItem.tsx
Labels: fix, ready for review

#1201 test(Dropdown): add more unit tests
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: ready for review

#1082 docs(ComponentPlayground): add playground to docs
  build/screener/screener.states.ts
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentPlayground.tsx
  docs/src/components/ComponentPlaygroundSnippet.tsx
  docs/src/components/ExampleSnippet/ExampleSnippet.tsx
  docs/src/components/ExampleSnippet/renderElementToJSX.ts
  docs/src/examples/components/Button/Playground.tsx
  docs/src/examples/components/Header/Playground.tsx
  docs/src/utils/exampleContexts.ts
  docs/src/utils/index.tsx
  packages/docs-components/package.json
  packages/docs-components/src/index.ts
  packages/docs-components/src/knobs/KnobContext.ts
  packages/docs-components/src/knobs/KnobInspector.tsx
  packages/docs-components/src/knobs/KnobProvider.tsx
  packages/docs-components/src/knobs/defaultComponents.tsx
  packages/docs-components/src/knobs/types.ts
  packages/docs-components/src/knobs/useBooleanKnob.ts
  packages/docs-components/src/knobs/useKnob.ts
  packages/docs-components/src/knobs/useKnobValues.ts
  packages/docs-components/src/knobs/useSelectKnob.ts
  packages/docs-components/src/knobs/useStringKnob.ts
Labels: docs, enhancement, ready for review

#1199 fix(Toolbar): do not close submenu and navigate next item when press Left/Right arrow keys
  CHANGELOG.md
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Toolbar/toolbarButtonBehavior.ts
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: fix, ready for review

#1223 feat(Provider): set scrollbar styles
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Provider/Types/ProviderExampleScrollbar.tsx
  docs/src/examples/components/Provider/Types/index.tsx
  packages/react/src/lib/handleRef.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Provider/providerBoxStyles.ts
  packages/react/src/themes/teams/components/Provider/providerBoxVariables.ts
Labels: enhancement, ready for review

#1229 feat(FocusZone): export FocusZoneMode type
  CHANGELOG.md
  packages/react/src/index.ts
Labels: enhancement, ready for review

#1236 perf(Dropdown): add tests
  docs/src/examples/components/Dropdown/Performance/Dropdown.perf.tsx
  docs/src/examples/components/Dropdown/Performance/index.tsx
  docs/src/examples/components/Dropdown/index.tsx
Labels: ready for review

#923 chore(package): use Babel for Jest
  .github/CONTRIBUTING.md
  babel.config.js
  build/jest/jest.config.common.js
  build/jest/setup.common.ts
  build/jest/setup.strict.ts
  docs/src/examples/components/Dialog/Usage/DialogExampleCallbacks.shorthand.tsx
  jest.config.js
  package.json
  packages/internal-tooling/babel/index.js
  packages/internal-tooling/jest/index.js
  packages/internal-tooling/jest/setupTests.js
  packages/internal-tooling/package.json
  packages/react-component-event-listener/.babelrc
  packages/react-component-event-listener/jest.config.js
  packages/react-component-event-listener/package.json
  packages/react-component-nesting-registry/.babelrc
  packages/react-component-nesting-registry/jest.config.js
  packages/react-component-nesting-registry/package.json
  packages/react-proptypes/.babelrc
  packages/react-proptypes/jest.config.js
  packages/react-proptypes/package.json
  packages/react/.babelrc
  packages/react/jest.config.js
  packages/react/package.json
  packages/react/src/components/Grid/Grid.tsx
  packages/react/src/lib/mergeThemes.ts
  packages/react/test/specs/behaviors/testHelper.tsx
  packages/react/test/specs/components/Form/FormField-test.tsx
  packages/react/test/specs/components/Ref/fixtures.tsx
  packages/react/test/utils/domEvent.ts
  yarn.lock
Labels: ready for review

#1232 fix(Chat Message): update at mention colors
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatMessageExampleBadge.shorthand.steps.ts
  docs/src/examples/components/Chat/Types/ChatMessageExampleBadge.shorthand.tsx
  packages/react/src/themes/teams-dark/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: ready for merge

#1238 fix(Alert): add `isFromKeyboard` to state
  CHANGELOG.md
  packages/react/src/components/Alert/Alert.tsx
Labels: fix, ready for review

#1251 chore(package): add `publishConfig` to `@stardust-ui/internal-tooling`
  packages/internal-tooling/package.json
Labels: ready for review

#1239 feat(doc): Add component perf charts
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentPerfExample/ComponentPerfChart.tsx
  docs/src/components/ComponentDoc/ComponentPerfExample/ComponentPerfExample.tsx
  docs/src/components/ComponentDoc/ComponentPerfExample/index.ts
  docs/src/components/ComponentDoc/PerfChart/PerfChart.tsx
  docs/src/components/ComponentDoc/PerfChart/PerfChartTooltip.tsx
  docs/src/components/ComponentDoc/PerfChart/PerfDataContext.ts
  docs/src/components/ComponentDoc/PerfChart/PerfDataProvider.tsx
  docs/src/components/ComponentDoc/PerfChart/index.ts
  docs/src/components/ComponentDoc/PerfChart/usePerfData.ts
  docs/src/config.ts
  docs/src/examples/components/Attachment/Performance/index.tsx
  docs/src/examples/components/Button/Performance/index.tsx
  docs/src/examples/components/Chat/Performance/index.tsx
  docs/src/examples/components/Divider/Performance/index.tsx
  docs/src/examples/components/Dropdown/Performance/index.tsx
  docs/src/examples/components/Header/Performance/index.tsx
  docs/src/examples/components/Icon/Performance/index.tsx
  docs/src/examples/components/List/Performance/index.tsx
  docs/src/examples/components/Loader/Performance/index.tsx
  docs/src/index.ejs
  package.json
  webpack.config.ts
  yarn.lock
Labels: docs, ready for review

#1253 feat(Accessibility): Add roles to Popup's content in accessibility behavior
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
Labels: enhancement, ready for review

#1246 fix(Chat): update ChatMessage styles in Teams themes
  CHANGELOG.md
  docs/src/examples/components/Chat/Content/ChatExampleReactionGroup.shorthand.tsx
  docs/src/examples/components/Chat/Content/ChatExampleReactionGroupMeReacting.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/themes/teams-dark/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: fix, ready for review

#600 chore(package): add ESLint
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  build/gulp/plugins/util/parseType.ts
  build/gulp/sh.ts
  build/gulp/tasks/test-projects/.eslintrc.json
  package.json
  packages/internal-tooling/eslint/index.js
  packages/internal-tooling/package.json
  packages/react-proptypes/src/leven.ts
  packages/react/.eslintignore
  packages/react/.eslintrc.json
  packages/react/src/lib/whatInput.ts
  yarn.lock
Labels: ready for review

#1258 fix(Dropdown): keep focused style when focus is on List
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: accessibility, ready for review

#1224 docs(Knobs): use new knobs
  docs/src/components/CodeSnippet.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleKnobs.tsx
  docs/src/components/Knobs/Knobs.tsx
  docs/src/components/Knobs/KnobsBoolean.tsx
  docs/src/components/Knobs/KnobsControl.tsx
  docs/src/components/Knobs/KnobsField.tsx
  docs/src/components/Knobs/KnobsLabel.tsx
  docs/src/components/Knobs/KnobsScalar.tsx
  docs/src/components/Knobs/KnobsValue.tsx
  docs/src/components/Playground/renderConfig.ts
  docs/src/examples/components/Dropdown/State/DropdownExampleLoading.knobs.tsx
  docs/src/examples/components/Dropdown/State/DropdownExampleLoading.shorthand.tsx
  docs/src/examples/components/ItemLayout/Types/ItemLayoutExample.knobs.tsx
  docs/src/examples/components/ItemLayout/Types/ItemLayoutExample.shorthand.tsx
  docs/src/examples/components/ItemLayout/Types/ItemLayoutExampleSelection.knobs.tsx
  docs/src/examples/components/ItemLayout/Types/ItemLayoutExampleSelection.shorthand.tsx
  docs/src/examples/components/Layout/Variations/LayoutExampleGap.knobs.tsx
  docs/src/examples/components/Layout/Variations/LayoutExampleGap.shorthand.tsx
  docs/src/examples/components/List/Types/ListExample.knobs.tsx
  docs/src/examples/components/List/Types/ListExample.shorthand.tsx
  docs/src/examples/components/List/Types/ListExample.tsx
  docs/src/examples/components/List/Variations/ListExampleTruncate.knobs.tsx
  docs/src/examples/components/List/Variations/ListExampleTruncate.shorthand.tsx
  docs/src/examples/components/List/Variations/ListExampleTruncate.tsx
  docs/src/examples/components/Loader/Usage/LoaderExampleDelay.knobs.tsx
  docs/src/examples/components/Loader/Usage/LoaderExampleDelay.tsx
  docs/src/utils/index.tsx
  docs/src/utils/knobsContext.ts
  packages/docs-components/src/index.ts
  packages/docs-components/src/knobs/KnobInspector.tsx
  packages/docs-components/src/knobs/KnobProvider.tsx
  packages/docs-components/src/knobs/defaultComponents.tsx
  packages/docs-components/src/knobs/types.ts
  packages/docs-components/src/knobs/useRangeKnob.ts
  packages/docs-components/tsconfig.json
Labels: ready for review

#1231 proto(dropdown mentions): improvements and refactoring
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/Prototypes.tsx
  docs/src/prototypes/dropdowns/MentionsWithDropdown.tsx
  docs/src/prototypes/dropdowns/index.tsx
  docs/src/prototypes/mentions/MentionsDropdown.tsx
  docs/src/prototypes/mentions/MentionsEditor.tsx
  docs/src/prototypes/mentions/PortalAtCursorPosition.ts
  docs/src/prototypes/mentions/dataMocks.ts
  docs/src/prototypes/mentions/index.tsx
  docs/src/prototypes/mentions/utils.ts
  docs/src/routes.tsx
Labels: enhancement, prototype, ready for review

#1226 fix(Alert): themeing updates for the alert component
  CHANGELOG.md
  docs/src/examples/components/Alert/Variations/AlertExampleAction.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleDanger.shorthand.steps.ts
  docs/src/examples/components/Alert/Variations/AlertExampleInfo.shorthand.steps.ts
  docs/src/examples/components/Alert/Variations/AlertExampleOofs.shorthand.steps.ts
  docs/src/examples/components/Alert/Variations/AlertExampleOofs.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleOofs.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleUrgent.shorthand.steps.ts
  docs/src/examples/components/Alert/Variations/AlertExampleUrgent.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleUrgent.tsx
  docs/src/examples/components/Alert/Variations/commonScreenerSteps.ts
  docs/src/examples/components/Alert/Variations/index.tsx
  docs/src/prototypes/alerts/AnimatedBannerAlert.tsx
  docs/src/prototypes/alerts/BannerAlerts.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Alert/alertVariables.ts
  packages/react/src/themes/teams-high-contrast/componentStyles.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Alert/alertStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Alert/alertVariables.ts
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
Labels: redlines

#869 fix(styles): expand css shorthands in order for them to be applied properly
  CHANGELOG.md
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-projects/rollup/rollup.config.js
  packages/react/package.json
  packages/react/src/lib/felaExpandCssShorthandsPlugin.ts
  packages/react/src/lib/felaRenderer.tsx
  packages/react/src/themes/teams/components/Segment/segmentStyles.ts
  packages/react/test/specs/lib/felaExpandCssShorthandsPlugin-test.ts
  yarn.lock
Labels: ready for review

#1256 fix(Chat): update me message background color for dark theme
  CHANGELOG.md
  packages/react/src/themes/teams-dark/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: ready for review
