Repository microsoft/fluent-ui-react, pull requests merged in 2019-10, with the labels that each got.

#1996 chore(screener): makes builds evergreen 🌲
  build/gulp/tasks/docs.ts
  package.json
  yarn.lock
Labels: 🗑️ chore, 🚀 ready for review

#1989 docs(Menu): Adding JAWS bugs
  packages/react/src/components/Menu/Menu.tsx
Labels: ready for merge, 📚 docs

#2003 chore: simplify getUnhandledProps() & getElementType()
  packages/react-bindings/jest.config.js
  packages/react-bindings/package.json
  packages/react-bindings/src/index.ts
  packages/react-bindings/src/utils/getElementType.ts
  packages/react-bindings/src/utils/getUnhandledProps.ts
  packages/react-bindings/test/utils/getElementType-test.ts
  packages/react-bindings/test/utils/getUnhandledProps-test.ts
  packages/react-bindings/tsconfig.json
  packages/react/package.json
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/accessibility/FocusZone/AutoFocusZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/src/lib/createComponent.ts
  packages/react/src/lib/getElementType.tsx
  packages/react/src/lib/index.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/test/specs/lib/getUnhandledProps-test.tsx
Labels: 🗑️ chore, 🚀 ready for review

#1969 chore(downshift): update to 3.2.14
  build/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
  packages/react/package.json
  yarn.lock
Labels: ready for merge, 🗑️ chore

#1981 perf(tooltip): Simplify rendering when tooltip is not visible
  CHANGELOG.md
  docs/src/examples/components/Toolbar/Performance/CustomToolbar.perf.tsx
  docs/src/examples/components/Toolbar/Performance/index.tsx
  docs/src/examples/components/Toolbar/index.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/components/Tooltip/TooltipContent.tsx
Labels: 🚀 ready for review

#1983 docs(add-a-feature): update path names of new component files with Lerna & Yarn workspaces
  .github/add-a-feature.md
Labels: ready for merge, 📚 docs

#2004 chore: move FocusZone components to react-bindings
  build/gulp/tasks/docs.ts
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleVariables.tsx
  docs/src/components/VariableResolver/useEnhancedRenderer.ts
  packages/react-bindings/package.json
  packages/react-bindings/src/FocusZone/AutoFocusZone.tsx
  packages/react-bindings/src/FocusZone/AutoFocusZone.types.tsx
  packages/react-bindings/src/FocusZone/CHANGELOG.md
  packages/react-bindings/src/FocusZone/FocusTrapZone.tsx
  packages/react-bindings/src/FocusZone/FocusTrapZone.types.tsx
  packages/react-bindings/src/FocusZone/FocusZone.tsx
  packages/react-bindings/src/FocusZone/FocusZone.types.ts
  packages/react-bindings/src/FocusZone/focusUtilities.ts
  packages/react-bindings/src/hooks/useStateManager.ts
  packages/react-bindings/src/index.ts
  packages/react-bindings/src/utils/callable.ts
  packages/react-bindings/test/FocusZone/AutoFocusZone-test.tsx
  packages/react-bindings/test/FocusZone/FocusTrapZone-test.tsx
  packages/react-bindings/test/FocusZone/FocusZone-test.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTreeItem.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/MenuButton/focusUtils.ts
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/FocusZone/index.ts
  packages/react/src/lib/felaInvokeKeyframesPlugin.ts
  packages/react/src/lib/index.ts
  packages/react/src/lib/mergeThemes.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/test/specs/commonTests/handlesAccessibility.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/lib/factories-test.tsx
Labels: 🗑️ chore, 🚀 ready for review

#1900 feat(prototypes): Allow attaching notification to a target ref in CopyToClipboard prototype
  .github/add-a-feature.md
  CHANGELOG.md
  docs/src/prototypes/CopyToClipboard/CopyToClipboard.tsx
  docs/src/prototypes/CopyToClipboard/NotificationProvider.tsx
  docs/src/prototypes/CopyToClipboard/index.tsx
  docs/src/prototypes/CopyToClipboard/themeOverrides.ts
  packages/react/src/components/Tooltip/Tooltip.tsx
Labels: 🚀 ready for review, 🤖 prototype

#2001 fix(Chat): adding border for reaction popup in Teams high contrast theme
  CHANGELOG.md
  packages/react/src/themes/teams-high-contrast/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: 💅 styling issue, 🚀 ready for review

#2013 test(projects): add behaviors usage
  build/gulp/tasks/test-projects/cra/App.tsx
  build/gulp/tasks/test-projects/typings/index.tsx
  packages/accessibility/src/behaviors/Image/imageBehavior.ts
Labels: 🚀 ready for review

#2010 feat(Toolbar): overflow menu via DOM
  CHANGELOG.md
  build/gulp/plugins/util/parseDefaultValue.ts
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleOverflow.shorthand.tsx
  docs/src/prototypes/EditorToolbar/EditorToolbar.tsx
  docs/src/prototypes/EditorToolbar/EditorToolbarTable.tsx
  docs/src/prototypes/EditorToolbar/PortalWindow.tsx
  docs/src/prototypes/EditorToolbar/editorToolbarReducer.ts
  docs/src/prototypes/EditorToolbar/index.tsx
  docs/src/routes.tsx
  packages/react-component-ref/src/toRefObject.ts
  packages/react/package.json
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/themes/teams/components/Toolbar/toolbarStyles.ts
  packages/react/test/specs/components/Toolbar/Toolbar-test.tsx
  yarn.lock
Labels: ⚙️ enhancement, 🚀 ready for review

#2018 fix(Alert): correctly handle RTL if shorthand API is used
  CHANGELOG.md
  docs/src/examples/components/Alert/Rtl/AlertExampleChildren.rtl.tsx
  docs/src/examples/components/Alert/Rtl/AlertExampleDismissAction.rtl.tsx
  docs/src/examples/components/Alert/Rtl/index.tsx
  packages/react/src/components/Alert/Alert.tsx
Labels: 🧰 fix

#2023 perf: remove Box usages where it is redundant
  CHANGELOG.md
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/components/Tooltip/TooltipContent.tsx
Labels: perf, 🚀 ready for review

#1974 feat(Debug): Add CSSinJS debug panel
  CHANGELOG.md
  docs/src/app.tsx
  docs/src/components/DocsLayout.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Provider/Performance/ProviderMergeThemes.perf.tsx
  docs/src/examples/components/Provider/Performance/index.tsx
  docs/src/examples/components/Provider/index.tsx
  packages/react/src/components/Debug/Debug.tsx
  packages/react/src/components/Debug/DebugComponentViewer.tsx
  packages/react/src/components/Debug/DebugLine.tsx
  packages/react/src/components/Debug/DebugPanel.tsx
  packages/react/src/components/Debug/DebugPanelData.tsx
  packages/react/src/components/Debug/DebugPanelItem.tsx
  packages/react/src/components/Debug/DebugRect.tsx
  packages/react/src/components/Debug/FiberNavigator.ts
  packages/react/src/components/Debug/ScrollToBottom.tsx
  packages/react/src/components/Debug/utils.ts
  packages/react/src/index.ts
  packages/react/src/lib/createComponent.ts
  packages/react/src/lib/debug/debugApi.ts
  packages/react/src/lib/debug/debugData.ts
  packages/react/src/lib/debug/debugDataProvider.ts
  packages/react/src/lib/debug/debugDataTraversal.ts
  packages/react/src/lib/debug/debugEnabled.ts
  packages/react/src/lib/debug/index.ts
  packages/react/src/lib/debug/types.ts
  packages/react/src/lib/debug/utils.ts
  packages/react/src/lib/getClasses.ts
  packages/react/src/lib/index.ts
  packages/react/src/lib/mergeThemes.ts
  packages/react/src/lib/objectKeysToValues.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/lib/withDebugId.ts
  packages/react/src/themes/createTheme.ts
  packages/react/src/themes/teams-dark/index.ts
  packages/react/src/themes/teams-high-contrast/index.ts
  packages/react/src/themes/teams/index.tsx
  packages/react/test/specs/components/Debug/utils-test.ts
  packages/react/test/specs/lib/mergeThemes/mergeComponentStyles-test.ts
  packages/react/test/specs/lib/mergeThemes/mergeComponentVariables-test.ts
  packages/react/test/specs/lib/mergeThemes/mergeSiteVariables-test.ts
  packages/react/test/specs/lib/mergeThemes/mergeThemeVariables-test.ts
  packages/react/test/specs/lib/mergeThemes/mergeThemes-test.ts
  packages/react/test/specs/lib/objectKeysToValues-test.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#2036 chore: run Screener on Github actions
  .circleci/config.yml
  .github/workflows/screener.yml
  build/screener/screener.config.js
Labels: 🗑️ chore, 🚀 ready for review

#2033 docs(Editor): fix issues with context
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/examples/components/Dialog/index.tsx
  package.json
  yarn.lock
Labels: 📚 docs, 🚀 ready for review

#2035 chore: remove snyk checks
  .circleci/config.yml
  .nowignore
  .snyk
  build/gulp/tasks/test-vulns.ts
  gulpfile.ts
  package.json
  yarn.lock
Labels: 🗑️ chore, 🚀 ready for review

#2028 fix(Popper): patch popper to use the correct window instance
  CHANGELOG.md
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/test/__mocks__/popper.js.ts
Labels: 🚀 ready for review, 🧰 fix

#1962 feat(prototypes): add prototype for custom scrollbar for menu, dialog, popup and list
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/customScrollbar/index.tsx
  docs/src/routes.tsx
Labels: 🚀 ready for review, 🤖 prototype

#2037 docs(Dialog): Fix closing of dialog in header action example
  docs/src/examples/components/Dialog/Content/DialogExampleHeaderAction.shorthand.tsx
Labels: 🚀 ready for review

#2005 feat(Dialog): Add ability to set custom footer
  CHANGELOG.md
  build/screener/screener.config.js
  docs/src/components/ComponentPlayground/componentGenerators.ts
  docs/src/components/ComponentPlayground/createHookGenerator.ts
  docs/src/examples/components/Dialog/Content/DialogExampleFooter.shorthand.steps.ts
  docs/src/examples/components/Dialog/Content/DialogExampleFooter.shorthand.tsx
  docs/src/examples/components/Dialog/Content/index.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Dialog/DialogFooter.tsx
  packages/react/src/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/components/Dialog/dialogFooterStyles.ts
  packages/react/src/themes/teams/components/Dialog/dialogStyles.ts
  packages/react/test/specs/components/Dialog/DialogFooter-test.tsx
Labels: ⚙️ enhancement, 🚧 WIP

#2025 perf(List): remove Flex usage
  CHANGELOG.md
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/themes/teams/components/List/listItemStyles.ts
Labels: perf, 🚀 ready for review

#2042 chore: update Screener triggers
  .github/workflows/screener.yml
  build/screener/screener.config.js
Labels: 🗑️ chore, 🚀 ready for review

#2041 perf: cache component variables
  CHANGELOG.md
  packages/react/src/lib/mergeProviderContexts.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/types.ts
Labels: perf, 🚀 ready for review

#2040 fix(accessibility): checking if the slot attributes are defined
  CHANGELOG.md
  packages/react/src/lib/renderComponent.tsx
Labels: ready for merge, 🧰 fix

#2047 docs(Toolbar): Label toolbars examples, adding best practices
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/examples/components/Toolbar/BestPractices/ToolbarBestPractices.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleCustomContent.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenu.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenuItemToggle.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenuRadioGroup.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleOverflow.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExamplePopup.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/ToolbarExampleRadioGroup.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/index.tsx
  docs/src/examples/components/Toolbar/Types/ToolbarExampleEditor.shorthand.tsx
  docs/src/examples/components/Toolbar/Types/index.tsx
  docs/src/examples/components/Toolbar/Usage/ToolbarExampleActionPopupInMenu.shorthand.tsx
  docs/src/examples/components/Toolbar/Usage/ToolbarExamplePopupInMenu.shorthand.tsx
  docs/src/examples/components/Toolbar/Usage/ToolbarExampleWithTooltip.shorthand.tsx
  docs/src/examples/components/Toolbar/Usage/index.tsx
Labels: 📚 docs, 🚀 ready for review

#2046 docs(readme): update references to fluent-ui-react
  README.md
Labels: 🚀 ready for review

#1984 feat(ToolbarMenuItem): add menu prop
  CHANGELOG.md
  build/gulp/tasks/test-circulars/config.ts
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenuWithSubmenu.shorthand.steps.ts
  docs/src/examples/components/Toolbar/Content/ToolbarExampleMenuWithSubmenu.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/index.tsx
  e2e/tests/popupInSubmenuInToolbarMenu-example.tsx
  e2e/tests/popupInSubmenuInToolbarMenu-test.ts
  e2e/tests/submenuInToolbarMenu-example.tsx
  e2e/tests/submenuInToolbarMenu-test.ts
  packages/accessibility/src/behaviors/Toolbar/toolbarItemBehavior.ts
  packages/accessibility/src/behaviors/Toolbar/toolbarMenuBehavior.ts
  packages/accessibility/src/behaviors/Toolbar/toolbarMenuItemBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/accessibility/test/behaviors/behavior-test.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenu.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
  packages/react/src/lib/AutoControlledComponent.tsx
  packages/react/src/themes/teams/components/Toolbar/toolbarMenuItemStyles.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#2059 fix(Icon): update the call-missed-line icon in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/icons/callMissedLine.tsx
Labels: 💅 styling issue, 🚀 ready for review

#2011 feat(ListItem,Button,ToolbarItem,ToolbarMenu): Adding/fixing universal focus indicator
  CHANGELOG.md
  docs/src/examples/components/Button/Usage/ButtonUsageExample.shorthand.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Button/buttonVariables.ts
  packages/react/src/themes/teams-dark/components/List/listItemVariables.ts
  packages/react/src/themes/teams-high-contrast/componentStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Button/buttonStyles.ts
  packages/react/src/themes/teams-high-contrast/components/Button/buttonVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Toolbar/toolbarVariables.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams/components/List/listItemStyles.ts
  packages/react/src/themes/teams/components/List/listItemVariables.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarCustomItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarMenuItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarVariables.ts
  packages/react/src/themes/teams/getBorderFocusStyles.ts
Labels: 💅 styling issue, 🚀 ready for review

#2067 fix(Popper): disable gpuAcceleration
  CHANGELOG.md
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/themes/teams/components/Toolbar/toolbarMenuItemStyles.ts
Labels: 🚀 ready for review

#2066 fix(MenuButton): do not force pinned in MenuButton
  CHANGELOG.md
  packages/react/src/components/MenuButton/MenuButton.tsx
Labels: 🚀 ready for review

#2062 fix(Popper): remove reference to popper element after destroy
  CHANGELOG.md
  packages/react/src/lib/positioner/Popper.tsx
Labels: 🚀 ready for review

#2050 feat(Chat): add unstable_overflow for Chat.Message
  CHANGELOG.md
  docs/src/examples/components/Chat/Usage/ChatExampleInScrollable.shorthand.steps.ts
  docs/src/examples/components/Chat/Usage/ChatExampleInScrollable.shorthand.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#1724 feat(button): adding animation to button mousedown
  CHANGELOG.md
  packages/react/src/themes/teams/animations/scale.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
Labels: 💅 styling issue, 🚀 ready for review

#2012 fix(attachment): Removing opacity from subtext, updating colors to match Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams-dark/components/Attachment/attachmentVariables.ts
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Attachment/attachmentVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: teams theme, vsts, 💅 styling issue
