Repository microsoft/fluent-ui-react, pull requests merged in 2019-08, with the labels that each got.

#1682 feat(docs): add search capability
  CHANGELOG.md
  docs/src/components/DocsLayout.tsx
  docs/src/components/Sidebar/Sidebar.tsx
Labels: ready for review

#1744 chore(tooling): Upgrade Prettier to 1.18.2
  build/gulp/plugins/util/docgen.ts
  docs/src/components/ComponentPlayground/propGenerators.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultiple.shorthand.steps.ts
  docs/src/prototypes/mentions/MentionsEditor.tsx
  docs/src/utils/helpers.tsx
  package.json
  packages/docs-components/src/CopyToClipboard.tsx
  packages/docs-components/src/knobs/useKnob.ts
  packages/react-component-event-listener/src/hooks/useEventListener.ts
  packages/react/src/components/Flex/FlexItem.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/lib/positioner/Popper.tsx
  packages/react/src/lib/providerMissingHandler.ts
  packages/react/src/themes/types.ts
  packages/react/test/specs/commonTests/implementsCollectionShorthandProp.tsx
  yarn.lock
Labels: ready for review

#1726 feat: add support for styles debugging
  CHANGELOG.md
  packages/react/src/lib/UIComponent.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/debug/debugApi.ts
  packages/react/src/lib/debug/debugData.ts
  packages/react/src/lib/debug/debugDataProvider.ts
  packages/react/src/lib/debug/debugDataTraversal.ts
  packages/react/src/lib/debug/index.ts
  packages/react/src/lib/debug/types.ts
  packages/react/src/lib/debug/utils.ts
  packages/react/src/lib/mergeProviderContexts.ts
  packages/react/src/lib/mergeThemes.ts
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/types.ts
Labels: ready for review

#1749 fix(FocusZone): Elements with `contenteditable` attribute should be respected on Home/End key press
  CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/test/specs/lib/FocusZone-test.tsx
Labels: accessibility, fix, ready for review

#1739 fix(ChatMessage): actions menu's appearance
  CHANGELOG.md
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: ready for review

#1750 chore(Dialog): use `ButtonGroup` instead of `Box`
  packages/react/src/components/Dialog/Dialog.tsx
Labels: ready for review

#1748 docs(Examples): use proper component variables
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleVariable.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleVariables.tsx
  docs/src/components/ExamplePlaceholder.tsx
  docs/src/components/VariableResolver/VariableResolver.tsx
  docs/src/components/VariableResolver/useClassNamesListener.ts
  docs/src/components/VariableResolver/useEnhancedRenderer.ts
  package.json
  packages/react/src/lib/renderComponent.tsx
  packages/react/src/themes/types.ts
  yarn.lock
Labels: docs, ready for review

#1741 fix(fela): plugin order, invokeKeyframes
  CHANGELOG.md
  package.json
  packages/internal-tooling/package.json
  packages/react/jest.config.js
  packages/react/src/lib/felaInvokeKeyframesPlugin.ts
  packages/react/src/lib/felaRenderer.tsx
  packages/react/test/specs/lib/__snapshots__/felaRenderer-test.tsx.snap
  packages/react/test/specs/lib/felaInvokeKeyframesPlugin-test.ts
  packages/react/test/specs/lib/felaRenderer-test.tsx
  yarn.lock
Labels: ready for review

#1755 chore(EventListener): use hooks
  CHANGELOG.md
  packages/react-component-event-listener/src/EventListener.ts
  packages/react-component-event-listener/src/StackableEventListener.ts
  packages/react-component-event-listener/src/hooks/types.ts
  packages/react-component-event-listener/src/hooks/useEventListener.ts
  packages/react-component-event-listener/src/hooks/useStackableEventListener.ts
  packages/react-component-event-listener/src/index.ts
  packages/react-component-event-listener/src/lib/addEventListener.ts
  packages/react-component-event-listener/src/lib/listenerRegistries.ts
  packages/react-component-event-listener/src/lib/removeEventListener.ts
  packages/react-component-event-listener/src/lib/shouldUpdateListener.ts
  packages/react-component-event-listener/src/types.internal.ts
  packages/react-component-event-listener/src/types.ts
  packages/react-component-event-listener/src/useEventListener.ts
  packages/react-component-event-listener/test/EventListener-test.tsx
  packages/react-component-event-listener/test/StackableEventListener-test.tsx
  packages/react/test/specs/components/Popup/Popup-test.tsx
  tslint.json
Labels: chore, ready for review

#1771 docs(server): remove opening browser tab on start
  build/gulp/plugins/webpack-open-browser.ts
  build/gulp/tasks/docs.ts
  package.json
  yarn.lock
Labels: chore

#1662 feat(Button): add loading prop
  CHANGELOG.md
  docs/src/examples/components/Button/States/ButtonExampleLoading.shorthand.tsx
  docs/src/examples/components/Button/States/index.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
Labels: ready for review

#1777 docs(Ref): show again docs
  CHANGELOG.md
  build/gulp/plugins/util/getComponentInfo.ts
  build/gulp/tasks/docs.ts
  docs/src/components/ComponentPlayground/ComponentPlayground.tsx
Labels: docs, ready for review

#1765 feat(Chat): Add expandable control messages prototype
  CHANGELOG.md
  docs/src/prototypes/chatMessages/ControlMessages/ControlMessage.tsx
  docs/src/prototypes/chatMessages/ControlMessages/GroupControlMessages.tsx
  docs/src/prototypes/chatMessages/ControlMessages/controlMessagesGroupBehavior.ts
  docs/src/prototypes/chatMessages/ControlMessages/index.tsx
  docs/src/prototypes/chatMessages/ControlMessages/mockData.tsx
  docs/src/prototypes/chatMessages/index.tsx
  packages/react/src/lib/accessibility/Behaviors/Chat/chatMessageBehavior.ts
Labels: prototype, ready for review

#1780 feat(Provider): add overwrite prop
  CHANGELOG.md
  packages/react/src/components/Provider/Provider.tsx
  packages/react/test/specs/components/Provider/Provider-test.tsx
Labels: enhancement, ready for review

#1772 feat(FocusZone): Upgrade to the latest version
  CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.types.ts
  packages/react/src/lib/accessibility/FocusZone/focusUtilities.ts
  packages/react/test/specs/lib/FocusZone-test.tsx
Labels: accessibility, enhancement, ready for review

#1719 fix(Button): Update text button styles
  CHANGELOG.md
  docs/src/examples/components/Button/States/ButtonExampleDisabled.shorthand.tsx
  docs/src/examples/components/Button/States/ButtonExampleDisabled.tsx
  docs/src/examples/components/Button/Types/ButtonExampleContentAndIcon.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExampleContentAndIcon.tsx
  docs/src/examples/components/Button/Types/ButtonExampleIcon.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExampleIcon.tsx
  docs/src/examples/components/Button/Types/ButtonExampleIconOnly.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExampleIconOnly.tsx
  docs/src/examples/components/Button/Types/ButtonExampleText.shorthand.steps.ts
  docs/src/examples/components/Button/Types/ButtonExampleText.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExampleText.tsx
  docs/src/examples/components/Button/Types/index.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleCircular.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleCircular.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleEmphasisCircular.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleEmphasisCircular.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleText.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleText.tsx
  docs/src/examples/components/Button/Variations/index.tsx
  packages/react/src/themes/teams-dark/components/Button/buttonVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Button/buttonVariables.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
Labels: ready for review

#1700 chore(package): bump lodash
  CHANGELOG.md
  build/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
  package.json
  packages/react-proptypes/package.json
  packages/react/package.json
  yarn.lock
Labels: chore, ready for review

#1657 feat(Toolbar): responsive
  CHANGELOG.md
  build/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
  docs/src/examples/components/Toolbar/Content/ToolbarExampleOverflow.shorthand.tsx
  docs/src/examples/components/Toolbar/Content/index.tsx
  packages/react/package.json
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/themes/base/componentStyles.ts
  packages/react/src/themes/base/components/Toolbar/toolbarRadioGroupStyles.ts
  packages/react/src/themes/base/components/Toolbar/toolbarStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarItemStyles.ts
  packages/react/src/themes/teams/components/Toolbar/toolbarVariables.ts
  yarn.lock
Labels: ready for review

#1758 fix(embed): make component focusable, only show control/placeholder on video
  CHANGELOG.md
  docs/src/examples/components/Embed/Slots/EmbedExampleIframe.shorthand.tsx
  docs/src/examples/components/Embed/Slots/EmbedExampleVideo.shorthand.tsx
  docs/src/examples/components/Embed/Slots/index.tsx
  docs/src/examples/components/Embed/Usage/EmbedExampleYouTube.shorthand.tsx
  docs/src/examples/components/Embed/Usage/index.tsx
  docs/src/examples/components/Embed/index.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/themes/teams/components/Embed/embedStyles.ts
  packages/react/test/specs/components/Embed/Embed-test.tsx
Labels: ready for review

#1795 chore: Export FocusTrapZoneProps and AutoFocusZoneProps from main package
  CHANGELOG.md
  packages/react/src/index.ts
Labels: ready for review

#1797 docs(QuickStart): improve code example
  CHANGELOG.md
  docs/src/views/QuickStart.tsx
Labels: ready for review

#1763 docs(variables): use color picker in theme it
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleColorPicker.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleVariable.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleVariables.tsx
Labels: docs, ready for review

#1738 feat(Dropdown): add checkable and checkableIndicator prop
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExample.shorthand.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownItem.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownItemStyles.ts
Labels: enhancement, ready for review

#1775 chore(customPropTypes): remove customPropTypes.as
  .github/document-a-feature.md
  package.json
  packages/docs-components/package.json
  packages/react-component-event-listener/package.json
  packages/react-component-nesting-registry/package.json
  packages/react-component-ref/package.json
  packages/react-proptypes/package.json
  packages/react-proptypes/src/index.ts
  packages/react/package.json
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/lib/accessibility/FocusZone/AutoFocusZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/src/lib/commonPropTypes.ts
  yarn.lock
Labels: chore, ready for review

#1770 chore(AutoControlledComponent): remove trySetState()
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTree.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/List/List.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/MenuButton/MenuButton.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/Slider/Slider.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/lib/AutoControlledComponent.tsx
  packages/react/test/specs/lib/AutoControlledComponent-test.tsx
Labels: chore, ready for review

#1684 feat(Input): add `inverted` prop to change background color of an input
  CHANGELOG.md
  docs/src/examples/components/Input/Types/InputInvertedExample.shorthand.steps.ts
  docs/src/examples/components/Input/Types/InputInvertedExample.shorthand.tsx
  docs/src/examples/components/Input/Types/index.tsx
  docs/src/examples/components/Input/Variations/InputExampleClearable.shorthand.steps.ts
  packages/react/src/components/Input/Input.tsx
  packages/react/src/themes/base/components/Input/inputStyles.ts
  packages/react/src/themes/base/components/Input/inputVariables.ts
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Input/inputVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Input/inputVariables.ts
  packages/react/src/themes/teams/components/Input/inputVariables.ts
Labels: ready for review

#1794 fix(FocusZone): Bidirectional - U/D Arrow key navigation bug when hitting grid edge
  CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/test/specs/lib/FocusZone-test.tsx
Labels: accessibility, fix, ready for review

#1782 fix(Icon): update `hand` icon in Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/components/Icon/svg/ProcessedIcons/icons-hand.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/hand.tsx
Labels: fix, ready for review

#1810 fix(Provider): use `target` in context
  CHANGELOG.md
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Portal/PortalInner.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/lib/mergeProviderContexts.ts
  packages/react/src/types.ts
  packages/react/test/specs/components/PortalInner/PortalInner-test.tsx
  packages/react/test/utils/withProvider.tsx
Labels: fix, ready for review

#1807 fix(Popup|Dialog): ESC should close opened Popup/Dialog if focus is lost and moved to body
  CHANGELOG.md
  e2e/tests/dialogInDialog-test.ts
  e2e/tests/dialogInPopup-example.tsx
  e2e/tests/dialogInPopup-test.ts
  e2e/tests/popupInPopup-example.tsx
  e2e/tests/popupInPopup-test.ts
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Popup/Popup.tsx
Labels: accessibility, bug, ready for review

#1790 feat(FocusTrapZone): upgrade to the latest version from fabric-ui
  CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx
  packages/react/src/lib/accessibility/FocusZone/focusUtilities.ts
  packages/react/test/specs/lib/FocusTrapZone-test.tsx
Labels: accessibility, enhancement, ready for review

#1820 fix(FocusZone|FocusTrapZone): correctly define current document object of the components
  CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
Labels: accessibility, fix, ready for review

#1823 feat(Alert): add actions
  CHANGELOG.md
  docs/src/examples/components/Alert/Slots/AlertExampleActions.shorthand.tsx
  docs/src/examples/components/Alert/Slots/AlertExampleDismissAction.shorthand.tsx
  docs/src/examples/components/Alert/Slots/index.tsx
  docs/src/examples/components/Alert/State/AlertExampleVisible.shorthand.tsx
  docs/src/examples/components/Alert/State/index.tsx
  docs/src/examples/components/Alert/Types/AlertExampleDismissible.shorthand.tsx
  docs/src/examples/components/Alert/Types/index.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleAction.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleOofs.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleOofs.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleUrgent.shorthand.tsx
  docs/src/examples/components/Alert/Variations/AlertExampleUrgent.tsx
  docs/src/examples/components/Alert/Variations/commonScreenerSteps.ts
  docs/src/examples/components/Alert/Variations/index.tsx
  docs/src/examples/components/Alert/index.tsx
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/themes/teams-high-contrast/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
  packages/react/test/specs/commonTests/implementsShorthandProp.tsx
  packages/react/test/specs/components/Alert/Alert-test.tsx
  packages/react/test/specs/components/Attachment/Attachment-test.tsx
  packages/react/test/specs/components/Button/Button-test.tsx
  packages/react/test/specs/components/Input/Input-test.tsx
  packages/react/test/specs/components/Label/Label-test.tsx
Labels: enhancement, ready for review

#1833 chore(renderComponent): do not use renderer if it was not specified
  packages/react/src/lib/renderComponent.tsx
Labels: chore, ready for review

#1832 docs(Alert): add usage example with actions
  docs/src/examples/components/Alert/Usage/AlertExampleDismissActions.shorthand.tsx
  docs/src/examples/components/Alert/Usage/index.tsx
Labels: docs, ready for review

#1838 fix(CHANGELOG.md): typo in v0.36.2
  CHANGELOG.md
Labels: ready for review

#1830 fix(Dropdown): fix switch between `multiple` and `single` modes
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
Labels: fix, ready for review

#1837 fix(renderComponent): do not throw if context is missing
  CHANGELOG.md
  packages/react/src/lib/mergeThemes.ts
  packages/react/src/lib/renderComponent.tsx
Labels: 🚀 ready for review, 🧰 fix

#1825 fix(Tooltip): Fixing incorrect tooltip shadow
  CHANGELOG.md
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Tooltip/tooltipContentVariables.ts
  packages/react/src/themes/teams-dark/siteVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Tooltip/tooltipContentVariables.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentStyles.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentVariables.ts
Labels: 💅 styling issue, 🚀 ready for review

#1836 docs(sidebar): fix background of sidebar search input element
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
Labels: ready for merge, 📚 docs

#1828 fix(Dialog): fix RTL issues
  CHANGELOG.md
  docs/src/examples/components/Dialog/Rtl/DialogExample.rtl.steps.ts
  docs/src/examples/components/Dialog/Rtl/DialogExample.rtl.tsx
  docs/src/examples/components/Dialog/index.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/themes/base/components/Dialog/dialogStyles.ts
Labels: needs author feedback, 🧰 fix

#1839 docs(mixed): fix multiple warnings
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentSourceManager/ComponentSourceManager.ts
  docs/src/examples/components/Slider/Usage/SliderExampleAction.shorthand.tsx
  packages/docs-components/src/CodeSnippet/formatCode.ts
Labels: 🚀 ready for review

#1735 fix(MenuItem): make spacebar not scroll the page, fix submenu not closing
  CHANGELOG.md
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  packages/react/test/specs/components/Menu/Menu-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#1822 test(sliderBehavior): add description and unit tests
  packages/react/src/lib/accessibility/Behaviors/Slider/sliderBehavior.ts
  packages/react/test/specs/behaviors/sliderBehavior-test.ts
  packages/react/test/specs/behaviors/testHelper.tsx
Labels: 🚀 ready for review

#1793 fix(Prototypes): fix invoking suggestion when user type "@" in "At mention"
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/mentions/MentionsDropdown.tsx
  docs/src/prototypes/mentions/MentionsEditor.tsx
Labels: 📚 docs, 🚀 ready for review, 🧰 fix

#1821 feat(alert): add Header and Icon slots
  CHANGELOG.md
  build/gulp/tasks/docs.ts
  docs/src/examples/components/Alert/Slots/AlertExampleHeader.shorthand.tsx
  docs/src/examples/components/Alert/Slots/AlertExampleHeader.tsx
  docs/src/examples/components/Alert/Slots/AlertExampleIcon.shorthand.tsx
  docs/src/examples/components/Alert/Slots/AlertExampleIcon.tsx
  docs/src/examples/components/Alert/Slots/index.tsx
  docs/src/examples/components/Alert/Usage/AlertExampleImportantMessage.shorthand.tsx
  docs/src/examples/components/Alert/Usage/AlertExampleImportantMessage.tsx
  docs/src/examples/components/Alert/Usage/index.tsx
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/lib/accessibility/Behaviors/Alert/alertBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Alert/alertWarningBehavior.ts
  packages/react/src/themes/teams/components/Alert/alertStyles.ts
  packages/react/src/themes/teams/components/Alert/alertVariables.ts
  packages/react/test/specs/behaviors/alertBehavior-test.tsx
  packages/react/test/specs/components/Alert/Alert-test.tsx
Labels: ⚙️ enhancement, 🚀 ready for review

#1847 fix(Video): fix `muted` prop
  CHANGELOG.md
  packages/react/src/components/Video/Video.tsx
Labels: 🚀 ready for review, 🧰 fix

#1842 fix(Provider): should not use felaRenderer explicitly
  CHANGELOG.md
  packages/internal-tooling/eslint/index.js
  packages/react/src/components/Provider/Provider.tsx
  packages/react/test/specs/components/Provider/Provider-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#1845 docs(Form): add usage example with Checkbox
  CHANGELOG.md
  docs/src/examples/components/Form/Types/index.tsx
  docs/src/examples/components/Form/Usage/FormExampleCheckbox.shorthand.tsx
  docs/src/examples/components/Form/Usage/FormExampleCheckbox.tsx
  docs/src/examples/components/Form/Usage/FormExampleDropdown.shorthand.tsx
  docs/src/examples/components/Form/Usage/FormExampleDropdown.tsx
  docs/src/examples/components/Form/Usage/FormExampleSlider.shorthand.tsx
  docs/src/examples/components/Form/Usage/FormExampleSlider.tsx
  docs/src/examples/components/Form/Usage/index.tsx
Labels: 📚 docs, 🚀 ready for review

#1841 docs(prototypes): add prototype for threaded chat messages
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/ScreenReaderHeaderText.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/ThreadReplies.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/ThreadReplyEditor.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/ThreadedMessage.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/classNames.ts
  docs/src/prototypes/chatMessages/ThreadedMessages/index.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/mockData.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/repliesButtonBehavior.ts
  docs/src/prototypes/chatMessages/ThreadedMessages/theme.tsx
  docs/src/prototypes/chatMessages/ThreadedMessages/threadChatBehavior.ts
  docs/src/prototypes/chatMessages/ThreadedMessages/threadedMessageBehavior.ts
  docs/src/prototypes/chatMessages/index.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: prototype, 🚀 ready for review

#1853 docs(CodeSandbox): fix styles
  CHANGELOG.md
  packages/code-sandbox/src/SandboxApp.tsx
Labels: needs author changes, 🧰 fix

#1859 chore: fix broken screener tests
  build/screener/screener.states.ts
  build/screener/screener.steps.ts
Labels: 🗑️ chore, 🚀 ready for review

#1840 docs(components): adding accessibility tab content
  CHANGELOG.md
  docs/src/components/ComponentDoc/BehaviorCard.tsx
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/types.ts
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Slider/Slider.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
Labels: 📚 docs, 🚀 ready for review

#1858 fix(SelectableList): set tabindex -1 to List container to make it work correctly with screen readers
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/List/selectableListBehavior.ts
  packages/react/src/lib/accessibility/FocusZone/FocusZone.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
Labels: accessibility, ⚙️ enhancement, 🚀 ready for review

#1779 feat: flat Tree component
  CHANGELOG.md
  docs/src/examples/components/Tree/Types/TreeExample.shorthand.tsx
  docs/src/examples/components/Tree/Types/TreeExclusiveExample.shorthand.tsx
  docs/src/examples/components/Tree/Types/TreeInitiallyOpenExample.shorthand.tsx
  docs/src/examples/components/Tree/Types/TreeTitleCustomizationExample.shorthand.tsx
  docs/src/examples/components/Tree/Types/index.tsx
  docs/src/examples/components/Tree/Usage/index.tsx
  docs/src/examples/components/Tree/index.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTree.tsx
  packages/react/src/components/HierarchicalTree/HierarchicalTreeItem.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/components/Tree/lib/index.ts
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeItemBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Tree/treeTitleBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Tree/treeItemStyles.ts
  packages/react/src/themes/teams/components/Tree/treeStyles.ts
  packages/react/src/themes/teams/components/Tree/treeTitleStyles.ts
  packages/react/src/themes/teams/components/Tree/treeTitleVariables.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
  packages/react/test/specs/behaviors/testDefinitions.ts
  packages/react/test/specs/components/Tree/Tree-test.tsx
Labels: help wanted, ⚙️ enhancement, 🚀 ready for review

#1857 fix(Checkbox): Checkbox should be vertically aligned with content
  CHANGELOG.md
  docs/src/examples/components/Checkbox/Types/CheckboxExample.shorthand.tsx
  packages/react/src/themes/teams/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/teams/components/Checkbox/checkboxVariables.ts
Labels: 💅 styling issue
