Repository microsoft/fluent-ui-react, pull requests merged in 2019-02, with the labels that each got.

#817 chore: add TS support and remove hardcoded values from visual tests config
  docs/src/examples/components/Dropdown/Types/DropdownExampleSingleSelection.shorthand.steps.js
  docs/src/examples/components/Dropdown/Types/DropdownExampleSingleSelection.shorthand.steps.ts
  screener.config.js
Labels: ready for review

#820 chore: update imports
  docs/src/app.tsx
  docs/src/components/ColorVariants.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/examples/components/RadioGroup/Item/index.tsx
  docs/src/examples/components/RadioGroup/Types/index.tsx
  docs/src/prototypes/chatPane/composeMessage.tsx
  docs/src/prototypes/chatPane/index.tsx
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  docs/src/views/ShorthandProps.tsx
  docs/src/views/ThemingExamples.tsx
  src/lib/getKeyDownHandlers.ts
  src/themes/teams/components/Chat/chatStyles.ts
Labels: ready for review

#822 feat(Accessibility): Accessibility for menu divider
  CHANGELOG.md
  src/components/Menu/MenuDivider.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Menu/menuDividerBehavior.ts
  src/lib/accessibility/index.ts
  test/specs/behaviors/behavior-test.tsx
Labels: ready for review

#833 chore(package): remove "leven" from dependencies
  package.json
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/lib/index.ts
Labels: ready for review

#816 fix(Dropdown): rename `combobox` to `root` in `dropdownSearchInputStyles`
  CHANGELOG.md
  packages/react/src/components/Dropdown/DropdownSearchInput.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownSearchInputStyles.ts
Labels: fix, ready for review

#824 fix(dropdown): fixed dropdown style regression
  CHANGELOG.md
  packages/react/src/components/Input/Input.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownSearchInputStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams/components/Input/inputStyles.ts
  packages/react/src/themes/teams/components/Input/inputVariables.ts
Labels: ready for review

#827 feat(theming): exporting slot's classNames form components
  CHANGELOG.md
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/ItemLayout/ItemLayout.tsx
  packages/react/src/components/Layout/Layout.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/index.ts
Labels: ready for merge, ready for review

#823 feat(ChatMessage): add badge and badgePosition props
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatMessageExampleBadge.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  docs/src/examples/components/Chat/Types/index.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: ready for merge, ready for review

#828 fix(Avatar): alignment of status icon on size changes
  CHANGELOG.md
  docs/src/examples/components/Avatar/Variations/AvatarExampleSize.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleStatusCustomization.shorthand.tsx
  docs/src/prototypes/employeeCard/EmployeeCard.tsx
  packages/react/src/components/Avatar/Avatar.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/components/Status/Status.tsx
  packages/react/src/components/Text/Text.tsx
  packages/react/src/index.ts
  packages/react/src/lib/commonPropInterfaces.ts
  packages/react/src/lib/customPropTypes.tsx
  packages/react/src/themes/base/components/Loader/loaderVariables.ts
  packages/react/src/themes/teams/components/Avatar/avatarStyles.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Status/statusStyles.ts
Labels: fix, ready for merge, ready for review

#836 fix(Provider|Ref): add `displayName` property
  CHANGELOG.md
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/Provider/ProviderConsumer.tsx
  packages/react/src/components/Ref/Ref.tsx
  packages/react/src/components/Ref/RefFindNode.tsx
  packages/react/src/components/Ref/RefForward.tsx
Labels: fix, ready for merge

#841 feat(ChatMessage): add hasMention and isImportant variables in Teams theme
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleBadge.shorthand.tsx
  docs/src/prototypes/ImportantAndMentionMessages/index.tsx
  docs/src/routes.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: ready for review

#832 chore(tsconfig): use correct paths
  build/tsconfig.common.json
  build/tsconfig.commonjs.json
  build/tsconfig.docs.json
  build/tsconfig.perf.json
  build/tsconfig.test.json
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/commonTests/isExportedAtTopLevel.tsx
  tsconfig.json
Labels: ready for merge, ready for review

#811 feat(Chat): add `actionMenu` prop for `ChatMessage`
  CHANGELOG.md
  docs/src/examples/components/Chat/Content/ChatExampleActions.shorthand.tsx
  docs/src/examples/components/Chat/Content/index.tsx
  docs/src/examples/components/Chat/index.tsx
  docs/src/prototypes/chatMessageWithPopover/ChatMessageWithPopover.tsx
  docs/src/prototypes/chatMessageWithPopover/ChatWithPopover.tsx
  docs/src/prototypes/chatMessageWithPopover/Popover.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: enhancement, ready for review

#837 chore(package): get working `paths` option for ts-node
  docs/src/examples/components/Dropdown/Types/DropdownExampleSingleSelection.shorthand.steps.ts
  gulpfile.ts
  package.json
  screener.config.js
  yarn.lock
Labels: ready for merge

#851 feat(Icon): add rtl in the `SvgIconFuncArg` for defining different svg in rtl mode
  CHANGELOG.md
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/themes/teams/components/Icon/svg/icons/numberList.tsx
  packages/react/src/themes/types.ts
  packages/react/test/specs/themes/teams/components/Icon/Icon-test.tsx
Labels: ready for review

#839 feat(dropdown): single search
  CHANGELOG.md
  docs/src/examples/components/Dropdown/State/DropdownExampleLoading.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExample.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExample.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearch.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExampleSingleSelection.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleSingleSelection.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/index.tsx
  docs/src/examples/components/Dropdown/Usage/DropdownExampleRender.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchFluid.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchFrenchLanguage.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchImageAndContent.shorthand.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
Labels: ready for review

#845 feat(dropdown): multiple selection
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExample.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultiple.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultiple.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/index.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
Labels: ready for merge

#857 chore(docs): use minified versions of Babel
  docs/src/components/Playground/renderConfig.ts
  docs/src/index.ejs
  package.json
  webpack.config.ts
  yarn.lock
Labels: ready for review

#855 feat(Label): added black and white colors for the color prop
  CHANGELOG.md
  packages/react/src/components/Label/Label.tsx
  packages/react/src/lib/commonPropInterfaces.ts
  packages/react/src/themes/teams/colors.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: ready for review

#802 feat: Flex component
  CHANGELOG.md
  docs/src/examples/components/Flex/Types/FlexExampleColumns.shorthand.tsx
  docs/src/examples/components/Flex/Types/FlexExampleInput.shorthand.tsx
  docs/src/examples/components/Flex/Types/FlexExampleItemsAlignment.shorthand.tsx
  docs/src/examples/components/Flex/Types/FlexExampleMediaCard.shorthand.tsx
  docs/src/examples/components/Flex/Types/FlexExampleMixedAlignment.shorthand.tsx
  docs/src/examples/components/Flex/Types/FlexExampleNavMenu.shorthand.tsx
  docs/src/examples/components/Flex/Types/index.tsx
  docs/src/examples/components/Flex/index.tsx
  packages/react/src/components/Flex/Flex.tsx
  packages/react/src/components/Flex/FlexGap.tsx
  packages/react/src/components/Flex/FlexItem.tsx
  packages/react/src/index.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Flex/flexItemStyles.ts
  packages/react/src/themes/teams/components/Flex/flexItemVariables.ts
  packages/react/src/themes/teams/components/Flex/flexStyles.ts
  packages/react/src/themes/teams/components/Flex/flexVariables.ts
  packages/react/src/themes/teams/components/Flex/utils.ts
Labels: ready for review

#861 fix(Popup): Focus the last focused element outside Popup on ESC
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
Labels: fix, ready for review

#856 docs(screener-io): added documentation on how to write tests with steps
  .github/test-a-feature.md
  CHANGELOG.md
Labels: docs, ready for review

#821 chore: Save package statistics to DB
  .circleci/config.yml
  build/gulp/tasks/stats.ts
  package.json
Labels: ready for merge

#863 feat(dropdown): inline prop
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExampleInline.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/index.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownSearchInput.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownItemStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownSearchInputStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
Labels: question, ready for review

#847 chore: Run perf tests in CI
  .circleci/config.yml
  build/gulp/tasks/perf.ts
Labels: ready for merge

#844 fix(gridBehavior): changing the focus zone to embed
  CHANGELOG.md
  docs/src/prototypes/popups/stickerPicker.tsx
  packages/react/src/lib/accessibility/Behaviors/Grid/gridBehavior.ts
Labels: ready for review

#842 feat(Dropdown): arrow navigation between selected items
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearch.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearchMultiple.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleSearchMultiple.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/index.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleSearchMultipleFluid.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleSearchMultipleFrenchLanguage.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleSearchMultipleImageAndContent.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/index.tsx
  package.json
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/Label/Label.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownSelectedItemStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
  packages/react/test/specs/components/Label/Label-test.tsx
Labels: ready for review

#867 fix(FocusZone): get rid of `const enum`
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusZone.types.ts
Labels: fix, ready for review

#864 chore(build): use cache in `build:docs:toc`
  build/gulp/plugins/gulp-doctoc.ts
  build/gulp/tasks/docs.ts
Labels: ready for review

#868 chore(package): add polyfills to correctly work in IE11
  CHANGELOG.md
  docs/src/components/Playground/renderConfig.ts
  docs/src/index.ejs
  package.json
  packages/react/src/lib/index.ts
  yarn.lock
Labels: fix, ready for review

#693 docs(behaviorTests): Adding documentation regarding behavior unit tests
  .github/test-a-feature.md
Labels: ready for review

#874 chore: Document release process
  .github/CONTRIBUTING.md
  .github/release-a-package.md
Labels: ready for review

#879 chore: Save perf stats to external DB
  .circleci/config.yml
  .gitignore
  build/gulp/tasks/stats.ts
Labels: ready for review

#890 fix(Flex): handle cases of falsy values provided as children
  CHANGELOG.md
  packages/react/src/components/Flex/Flex.tsx
  packages/react/src/components/Flex/FlexItem.tsx
Labels: ready for review

#884 fix(color palette): Move Color Palette sidebar link
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
Labels: ready for merge

#893 fix(chore): use '--typescript' flag in create-react-app project tests
  build/gulp/tasks/test-projects.tsx
Labels: fix

#876 feat(FocusZone): Export Focus Zone utilities
  CHANGELOG.md
  packages/react/src/index.ts
Labels: enhancement, ready for merge

#883 fix(pxToRem): update rem size on static styles render
  CHANGELOG.md
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/lib/fontSizeUtility.ts
  packages/react/src/lib/index.ts
Labels: fix, ready for merge

#887 fix(build): handle exceptions in `build:docs:example-sources`
  build/gulp/plugins/gulp-example-source.ts
Labels: ready for merge

#894 chore(package): update fela
  CHANGELOG.md
  package.json
  packages/react/src/lib/felaRenderer.tsx
  yarn.lock
Labels: fix, ready for review

#885 feat(Dropdown): add `clearable` prop
  .github/test-a-feature.md
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExampleClearable.shorthand.steps.ts
  docs/src/examples/components/Dropdown/Types/DropdownExampleClearable.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/index.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
Labels: enhancement, ready for review

#838 chore: Setup Lerna
  .circleci/config.yml
  build/gulp/tasks/bundle.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/stats.ts
  build/gulp/tasks/test-projects.tsx
  build/gulp/tasks/test-unit.ts
  build/jest/jest.config.common.js
  build/jest/jest.config.strict.js
  build/jest/setup.common.ts
  build/jest/setup.strict.ts
  build/webpack.config.perf.ts
  build/webpack.config.stats.ts
  build/webpack.config.umd.ts
  config.ts
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/views/Introduction.tsx
  gulpfile.ts
  jest.config.js
  lerna.json
  package.json
  packages/react/package.json
  packages/react/src/lib/leven.ts
  webpack.config.ts
  yarn.lock
Labels: ready for review

#897 fix(Dropdown): inserting char at a cursor position will the cursor to end
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: fix, ready for review

#878 fix(teams-theme): replace margins with padding in chatItemStyles (Teams theme)
  CHANGELOG.md
  packages/react/src/themes/teams/components/Chat/chatItemStyles.ts
Labels: fix, ready for review

#858 feat(teams-theme): clearing duplicate colors from siteVariables
  CHANGELOG.md
  docs/src/examples/components/Button/Usage/ButtonUsageExample.shorthand.tsx
  docs/src/prototypes/ImportantAndMentionMessages/index.tsx
  docs/src/prototypes/chatMessageWithPopover/ChatWithPopover.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/chatPane/composeMessage.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsHeader.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsLink.tsx
  docs/src/prototypes/meetingOptions/components/MSTeamsLogo.tsx
  packages/react/src/themes/teams-dark/components/Button/buttonVariables.ts
  packages/react/src/themes/teams-dark/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams-dark/components/Header/headerVariables.ts
  packages/react/src/themes/teams-dark/components/Menu/menuVariables.ts
  packages/react/src/themes/teams-dark/components/Tree/treeTitleVariables.ts
  packages/react/src/themes/teams-dark/siteVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams-high-contrast/siteVariables.ts
  packages/react/src/themes/teams/colors.ts
  packages/react/src/themes/teams/components/Attachment/attachmentVariables.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
  packages/react/src/themes/teams/components/Header/headerVariables.ts
  packages/react/src/themes/teams/components/Icon/iconVariables.ts
  packages/react/src/themes/teams/components/List/listItemVariables.ts
  packages/react/src/themes/teams/components/Menu/menuVariables.ts
  packages/react/src/themes/teams/components/Popup/popupContentVariables.ts
  packages/react/src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
  packages/react/src/themes/teams/components/Segment/segmentVariables.ts
  packages/react/src/themes/teams/components/Text/textVariables.ts
  packages/react/src/themes/teams/components/Tree/treeTitleVariables.ts
  packages/react/src/themes/teams/siteVariables.ts
Labels: ready for review

#891 fix(types): shorthand default props
  packages/react/src/components/Indicator/Indicator.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/factories.ts
  packages/react/src/types.ts
  packages/react/test/specs/lib/factories-test.tsx
Labels: fix, ready for review

#905 fix(docs): usages of brand color
  docs/src/views/IntegrateCustomComponents.tsx
  docs/src/views/Theming.tsx
  packages/react/src/themes/teams/components/List/listItemVariables.ts
  packages/react/src/themes/types.ts
Labels: ready for review

#911 fix(docs): new theme from switcher not applied when the page is changed
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
Labels: ready for review

#889 fix(stats): Store git tag for production builds to DB
  .circleci/config.yml
  build/gulp/tasks/stats.ts
Labels: ready for review

#913 feat(Popup): Expose Popup's content Ref
  CHANGELOG.md
  packages/react/src/components/Popup/Popup.tsx
Labels: enhancement, ready for review

#899 fix(Avatar): display correctly images in portrait mode
  CHANGELOG.md
  docs/src/examples/components/Avatar/Variations/AvatarExampleImage.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleImageCustomization.shorthand.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleSize.shorthand.tsx
  docs/src/public/images/avatar/large/jerry.png
  packages/react/src/themes/teams/components/Avatar/avatarStyles.ts
Labels: fix, ready for review

#679 docs: Removing Semantic UI from Stardust- DocSite
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentButton.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox/ComponentControlsCodeSandbox.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCopyLink.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsMaximize.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsRtl.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowCode.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowTransparent.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowVariables.tsx
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentDocAccessibility.tsx
  docs/src/components/ComponentDoc/ComponentDocLinks.tsx
  docs/src/components/ComponentDoc/ComponentDocSee.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExampleTitle.tsx
  docs/src/components/ComponentDoc/ComponentExamples.tsx
  docs/src/components/ComponentDoc/ComponentProp/ComponentPropHeader.tsx
  docs/src/components/ComponentDoc/ComponentProp/ComponentPropName.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentProps.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentPropsComponents.tsx
  docs/src/components/ComponentDoc/ComponentProps/ComponentPropsDescription.tsx
  docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.tsx
  docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebarSection.tsx
  docs/src/components/ComponentDoc/ComponentTable/ComponentTable.tsx
  docs/src/components/ComponentDoc/ComponentTable/ComponentTableHeader.tsx
  docs/src/components/ComponentDoc/ComponentTable/ComponentTableRow.tsx
  docs/src/components/ComponentDoc/ContributionPrompt.tsx
  docs/src/components/ComponentDoc/ExampleSection.tsx
  docs/src/components/DocPage/DocPage.tsx
  docs/src/components/DocsBehaviorRoot.tsx
  docs/src/components/DocsLayout.tsx
  docs/src/components/Logo/Logo.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/context/ThemeContext.tsx
  docs/src/examples/components/Icon/Usage/IconSetExample.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleSize.shorthand.tsx
  docs/src/examples/components/Image/Variations/ImageExampleFluid.tsx
  docs/src/examples/components/RadioGroup/Item/index.tsx
  docs/src/examples/components/RadioGroup/Types/index.tsx
  docs/src/index.ejs
  docs/src/prototypes/IconViewer/index.tsx
  docs/src/prototypes/chatPane/chatPaneLayout.tsx
  docs/src/views/Accessibility.tsx
  docs/src/views/ColorPalette.tsx
  docs/src/views/IntegrateCustomComponents.tsx
  docs/src/views/Introduction.tsx
  docs/src/views/PageNotFound.tsx
  docs/src/views/QuickStart.tsx
  docs/src/views/ShorthandProps.tsx
  docs/src/views/Theming.tsx
  docs/src/views/ThemingExamples.tsx
  package.json
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams/components/Icon/fontAwesomeIconStyles.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/List/listItemVariables.ts
  webpack.config.ts
  yarn.lock
Labels: ready for review

#829 fix(button): Update button to use semibold weight
  CHANGELOG.md
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
Labels: ready for review

#918 chore(dangerjs): add check for a changelog entry
  CHANGELOG.md
  dangerfile.ts
Labels: ready for review

#871 feat(animation): added animations for Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams/animations/fade.ts
  packages/react/src/themes/teams/animations/index.ts
  packages/react/src/themes/teams/animations/scale.ts
  packages/react/src/themes/teams/animations/slide.ts
  packages/react/src/themes/teams/animations/timingFunctions.ts
  packages/react/src/themes/teams/index.ts
Labels: ready for merge

#917 fix(FocusTrapZone): Do not hide aria-live regions from accessibility tree
  packages/react/src/lib/accessibility/FocusZone/CHANGELOG.md
  packages/react/src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  packages/react/test/specs/lib/FocusTrapZone-test.tsx
Labels: fix, ready for review

#880 feat(status): Add status behavior
  CHANGELOG.md
  docs/src/components/DocsBehaviorRoot.tsx
  docs/src/examples/components/Status/Types/StatusExample.shorthand.tsx
  docs/src/examples/components/Status/Types/StatusTypeExample.shorthand.tsx
  docs/src/examples/components/Status/Variations/StatusColorExample.shorthand.tsx
  docs/src/examples/components/Status/Variations/StatusIconExample.shorthand.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Status/Status.tsx
  packages/react/src/index.ts
  packages/react/src/lib/accessibility/Behaviors/Status/statusBehavior.ts
  packages/react/src/lib/accessibility/index.ts
  packages/react/test/specs/behaviors/behavior-test.tsx
Labels: ready for merge

#932 chore(dangerjs): check dependency changes
  dangerfile.ts
Labels: ready for review

#900 feat(dropdown): autocontrolled mode for open state
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Usage/DropdownExampleControlled.shorthand.tsx
  docs/src/examples/components/Dropdown/Usage/index.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
Labels: blocked, ready for review

#927 feat(mixed): add `accessibility` prop to all components
  CHANGELOG.md
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/Attachment/Attachment.tsx
  packages/react/src/components/Avatar/Avatar.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Button/ButtonGroup.tsx
  packages/react/src/components/Chat/Chat.tsx
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Divider/Divider.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownItem.tsx
  packages/react/src/components/Dropdown/DropdownSearchInput.tsx
  packages/react/src/components/Dropdown/DropdownSelectedItem.tsx
  packages/react/src/components/Flex/Flex.tsx
  packages/react/src/components/Flex/FlexItem.tsx
  packages/react/src/components/Form/Form.tsx
  packages/react/src/components/Form/FormField.tsx
  packages/react/src/components/Grid/Grid.tsx
  packages/react/src/components/Header/Header.tsx
  packages/react/src/components/Header/HeaderDescription.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Image/Image.tsx
  packages/react/src/components/Indicator/Indicator.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/components/ItemLayout/ItemLayout.tsx
  packages/react/src/components/Label/Label.tsx
  packages/react/src/components/Layout/Layout.tsx
  packages/react/src/components/List/List.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Menu/MenuDivider.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Popup/PopupContent.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Portal/PortalInner.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/components/Segment/Segment.tsx
  packages/react/src/components/Status/Status.tsx
  packages/react/src/components/Text/Text.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/components/Tree/TreeTitle.tsx
  packages/react/src/lib/accessibility/Behaviors/Grid/gridBehavior.ts
  packages/react/src/lib/commonPropTypes.ts
  packages/react/src/lib/customPropTypes.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Animation/Animation-test.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/specs/components/ItemLayout/ItemLayout-test.ts
  packages/react/test/specs/components/Layout/Layout-test.ts
Labels: enhancement, ready for review

#926 fix(docs): generate docs for components produced by createComponent() func
  build/gulp/plugins/util/docgen.ts
  build/gulp/plugins/util/getComponentInfo.ts
  package.json
  yarn.lock
Labels: ready for review

#907 fix(Icon): bordered and circular props not working as expected
  CHANGELOG.md
  docs/src/examples/components/Animation/Types/AnimationExample.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleDelay.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleDirection.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleDuration.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleFillMode.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleIterationCount.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleKeyframeParams.tsx
  docs/src/examples/components/Animation/Types/AnimationExamplePlayState.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleTimingFunction.tsx
  docs/src/examples/components/Avatar/Variations/AvatarExampleImageCustomization.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleCircular.shorthand.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
Labels: ready for review

#928 docs(ComponentExample): remove useless components and cleanups
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsMaximize.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsRtl.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowCode.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowTransparent.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsShowVariables.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/hoc/updateForKeys.tsx
  package.json
  yarn.lock
Labels: ready for review

#941 feat(perf): add 'filter' flag to perf tests
  build/gulp/tasks/perf.ts
  perf/src/index.tsx
  perf/types.tsx
Labels: ready for review

#943 feat(FocusZone): Export FocusZone types
  CHANGELOG.md
  packages/react/src/index.ts
Labels: enhancement, ready for review

#931 feat(prototypes): mention scenario with dropdown
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/AsyncDropdownSearch/index.ts
  docs/src/prototypes/Prototypes.tsx
  docs/src/prototypes/dropdowns/AsyncDropdownSearch.tsx
  docs/src/prototypes/dropdowns/MentionsWithDropdown.tsx
  docs/src/prototypes/dropdowns/PortalAtCursorPosition.ts
  docs/src/prototypes/dropdowns/dataMocks.ts
  docs/src/prototypes/dropdowns/index.tsx
  docs/src/prototypes/dropdowns/utils.ts
  docs/src/routes.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Dropdown/DropdownSearchInput.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownSearchInputStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownStyles.ts
Labels: ready for review

#951 fix(docs): fix conflict Fela and FontAwesome
  CHANGELOG.md
  dangerfile.ts
  packages/react/src/lib/felaRenderer.tsx
Labels: fix, ready for review

#956 fix(Dropdown|Input): call callback on clear
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Input/Input.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/specs/components/Input/Input-test.tsx
Labels: fix, ready for review

#962 fix(ChatMessage): styles
  CHANGELOG.md
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: fix, ready for review, redlines

#961 fix(Status): fix order of applied props
  CHANGELOG.md
  packages/react/src/components/Status/Status.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
Labels: fix, ready for review

#945 fix(styles): removed redundant margins from components and examples
  CHANGELOG.md
  docs/src/examples/components/Accordion/Usage/AccordionPanelCustomContentExample.shorthand.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleKeyframeParams.tsx
  docs/src/examples/components/Button/Rtl/ButtonExample.rtl.tsx
  docs/src/examples/components/Button/States/ButtonExampleDisabled.shorthand.tsx
  docs/src/examples/components/Button/States/ButtonExampleDisabled.tsx
  docs/src/examples/components/Button/Types/ButtonExample.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExample.tsx
  docs/src/examples/components/Button/Types/ButtonExampleContentAndIcon.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExampleContentAndIcon.tsx
  docs/src/examples/components/Button/Types/ButtonExampleEmphasis.shorthand.tsx
  docs/src/examples/components/Button/Types/ButtonExampleEmphasis.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleCircular.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleCircular.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleEmphasisCircular.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleEmphasisCircular.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleText.shorthand.tsx
  docs/src/examples/components/Button/Variations/ButtonExampleText.tsx
  docs/src/examples/components/Icon/Types/IconExample.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleBordered.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleCircular.shorthand.tsx
  docs/src/examples/components/Icon/Variations/IconExampleColor.shorthand.tsx
  docs/src/examples/components/Indicator/Types/IndicatorExampleDirection.shorthand.tsx
  docs/src/examples/components/Indicator/Types/IndicatorExampleIcon.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupContentWrapperExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupContentWrapperExample.tsx
  docs/src/examples/components/Popup/Types/PopupFocusTrapExample.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOn.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOnMultiple.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOnWithFocusTrap.shorthand.tsx
  docs/src/examples/components/Ref/Types/RefExample.tsx
  packages/react/src/components/Button/ButtonGroup.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Flex/Flex.tsx
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Attachment/attachmentVariables.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Flex/flexVariables.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Icon/iconVariables.ts
  packages/react/src/themes/teams/components/Input/inputVariables.ts
Labels: ready for review

#953 fix(ChatMessage): prevent hover over invisible actions area
  CHANGELOG.md
  docs/src/examples/components/Portal/Types/PortalExample.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExample.tsx
  docs/src/examples/components/Portal/Types/PortalExampleControlled.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExampleControlled.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: fix, ready for merge

#967 fix(Dropdown): export variables for the components that are part of the Dropdown
  CHANGELOG.md
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownItemVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownSearchInputVariables.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownSelectedItemVariables.ts
Labels: ready for merge

#954 fix(docs): createComponent typings and documentation
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentControls/ComponentButton.tsx
  docs/src/views/IntegrateCustomComponents.tsx
  packages/react/src/lib/createComponent.tsx
  packages/react/src/lib/createStardustComponent.tsx
Labels: docs, fix, ready for merge

#973 fix(button group): revert margin update
  CHANGELOG.md
  packages/react/src/components/Button/ButtonGroup.tsx
  packages/react/src/themes/teams/components/Button/buttonGroupStyles.ts
Labels: ready for review

#940 fix(Text): apply display: inline-block only if the animation prop is provided while the Text is rendered as span
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  packages/react/src/themes/base/components/Text/textStyles.ts
Labels: ready for review

#975 fix(doc): Update release steps after migration to lerna
  .github/release-a-package.md
Labels: ready for review

#910 perf: Add `List` performance example
  docs/src/examples/components/List/Performance/List.perf.tsx
  docs/src/examples/components/List/Performance/index.tsx
  docs/src/examples/components/List/index.tsx
Labels: ready for review

#969 feat(Loader): add `delay` prop
  CHANGELOG.md
  docs/src/examples/components/Loader/Usage/LoaderExampleDelay.knobs.tsx
  docs/src/examples/components/Loader/Usage/LoaderExampleDelay.tsx
  docs/src/examples/components/Loader/Usage/index.tsx
  docs/src/examples/components/Loader/index.tsx
  packages/react/src/components/Loader/Loader.tsx
  packages/react/test/specs/components/Loader/Loader-test.tsx
Labels: enhancement, ready for review

#886 feat(ListItem): refactor it to use the Flex component
  CHANGELOG.md
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/themes/teams/components/List/listItemStyles.ts
  packages/react/src/themes/teams/components/List/listItemVariables.ts
Labels: ready for review

#976 fix(avatar): sizing issues
  CHANGELOG.md
  packages/react/src/themes/teams/components/Avatar/avatarStyles.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Image/imageStyles.ts
Labels: ready for review

#981 feat(lib): export `getNextElement`, `getPreviousElement` and `focusAsync`
  CHANGELOG.md
  packages/react/src/index.ts
Labels: ready for review

#947 feat(Prototypes): add MenuButton
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/MenuButton/MenuButton.tsx
  docs/src/prototypes/MenuButton/focusUtils.ts
  docs/src/prototypes/MenuButton/index.tsx
  docs/src/prototypes/MenuButton/menuButtonBehavior.ts
  docs/src/routes.tsx
Labels: ready for review

#960 fix(RTL): apply static styles using the top-most Fela renderer
  CHANGELOG.md
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/lib/felaRenderer.tsx
Labels: ready for review

#995 feat(Popup): Set aria-modal for both Dialog and Popup with focus trap
  CHANGELOG.md
  packages/react/src/lib/accessibility/Behaviors/Dialog/dialogBehavior.ts
  packages/react/src/lib/accessibility/Behaviors/Popup/popupFocusTrapBehavior.ts
Labels: enhancement, ready for merge
