Repository microsoft/fluent-ui-react, pull requests merged in 2019-01, with the labels that each got.

#644 docs(Examples): use sources to render dedicated examples, separate contexts
  docs/src/components/ComponentDoc/ComponentExample/SourceCodeManager.ts
  docs/src/components/ComponentDoc/ComponentExamples.tsx
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/utils/exampleContext.ts
  docs/src/utils/exampleContexts.ts
  docs/src/utils/exampleKebabNameToFilename.ts
  docs/src/utils/exampleKebabNameToSourceFilename.ts
  docs/src/utils/index.tsx
Labels: ready for review

#672 chore(Text): remove unnecessary variable overrides in Teams theme
  src/themes/teams/components/Text/textVariables.ts
Labels: ready for review

#677 fix(MenuItem): "onFocus" is not handled as prop
  CHANGELOG.md
  src/components/Menu/MenuItem.tsx
Labels: fix, ready for review

#375 feat(accessibility): Adding attachment behavior to handle space/enter key
  CHANGELOG.md
  build/tsconfig.docs.json
  docs/src/prototypes/chatPane/services/messageFactoryMock.tsx
  src/components/Attachment/Attachment.tsx
  src/lib/accessibility/Behaviors/Attachment/attachmentBehavior.ts
  src/lib/accessibility/index.ts
  src/themes/teams/components/Attachment/attachmentStyles.ts
  src/themes/teams/components/Attachment/attachmentVariables.ts
  test/specs/behaviors/behavior-test.tsx
  test/specs/components/Attachment/Attachment-test.tsx
Labels: ready for review, vsts

#673 fix(Accordion, Menu): consilidating unicode arrow characters across the components
  CHANGELOG.md
  src/components/Accordion/AccordionTitle.tsx
  src/themes/teams/components/Accordion/accordionTitleStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuVariables.ts
  src/themes/teams/siteVariables.ts
Labels: ready for review

#622 feat(Popup): added `on` prop for triggering the popup on click, hover or focus
  CHANGELOG.md
  docs/src/examples/components/Popup/Usage/PopupExampleOn.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOnMultiple.shorthand.tsx
  docs/src/examples/components/Popup/Usage/PopupExampleOnWithFocusTrap.shorthand.tsx
  docs/src/examples/components/Popup/Usage/index.tsx
  docs/src/examples/components/Popup/index.tsx
  src/components/Popup/Popup.tsx
  src/components/Popup/PopupContent.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
Labels: ready for review, vsts

#690 fix(unicode-chars): Unicode characters used as arrows in the components are not RTL aware
  CHANGELOG.md
  src/themes/teams/components/Accordion/accordionTitleStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/siteVariables.ts
  src/themes/teams/utils/index.ts
Labels: ready for review

#661 refactor(gulp): refactor and optimize tasks with `gulp-cache`
  build/gulp/plugins/gulp-example-source.ts
  build/gulp/plugins/gulp-react-docgen.ts
  build/gulp/plugins/util/checksumUtils.ts
  build/gulp/plugins/util/getComponentInfo.ts
  build/gulp/plugins/util/index.ts
  build/gulp/tasks/docs.ts
  package.json
  yarn.lock
Labels: ready for review

#678 fix(Popup): update positions after each render
  CHANGELOG.md
  package.json
  src/components/Popup/Popup.tsx
  yarn.lock
Labels: fix, ready for review

#675 fix(Accordion|Dropdown): fix default props in auto controlled mode
  CHANGELOG.md
  docs/src/examples/components/Accordion/Types/AccordionExample.shorthand.tsx
  docs/src/examples/components/Accordion/Variations/AccordionExampleList.shorthand.tsx
  src/components/Accordion/Accordion.tsx
  src/components/Dropdown/Dropdown.tsx
Labels: fix, ready for review

#682 feat(Menu): adding kind prop for the items and MenuDivider component
  CHANGELOG.md
  docs/src/examples/components/Menu/Content/MenuExampleDivider.shorthand.tsx
  docs/src/examples/components/Menu/Content/index.tsx
  docs/src/examples/components/Menu/index.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuDivider.tsx
  src/index.ts
  src/lib/customPropTypes.tsx
  src/lib/factories.ts
  src/lib/getKindProp.ts
  src/lib/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/components/Menu/menuDividerStyles.ts
  test/specs/components/Menu/MenuDivider-test.ts
  types/utils.d.ts
Labels: ready for review

#642 refactor(Label): cleanup docs and simplify render
  CHANGELOG.md
  src/components/Label/Label.tsx
  test/specs/commonTests/implementsShorthandProp.tsx
Labels: ready for merge

#700 fix(px-to-rem): temporary remove recent changes
  CHANGELOG.md
  src/lib/fontSizeUtility.ts
  src/lib/index.ts
  src/themes/teams-high-contrast/components/Input/inputVariables.ts
  src/themes/teams/components/Attachment/attachmentStyles.ts
  src/themes/teams/components/Avatar/avatarStyles.ts
  src/themes/teams/components/Button/buttonStyles.ts
  src/themes/teams/components/Button/buttonVariables.ts
  src/themes/teams/components/Chat/chatItemVariables.ts
  src/themes/teams/components/Chat/chatMessageVariables.ts
  src/themes/teams/components/Chat/chatStyles.ts
  src/themes/teams/components/Divider/dividerStyles.ts
  src/themes/teams/components/Divider/dividerVariables.ts
  src/themes/teams/components/Dropdown/dropdownStyles.ts
  src/themes/teams/components/Dropdown/dropdownVariables.ts
  src/themes/teams/components/Form/formFieldStyles.ts
  src/themes/teams/components/Form/formStyles.ts
  src/themes/teams/components/Header/headerDescriptionStyles.ts
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/iconVariables.ts
  src/themes/teams/components/Image/imageStyles.ts
  src/themes/teams/components/Image/imageVariables.ts
  src/themes/teams/components/Input/inputVariables.ts
  src/themes/teams/components/ItemLayout/itemLayoutVariables.ts
  src/themes/teams/components/Label/labelStyles.ts
  src/themes/teams/components/Label/labelVariables.ts
  src/themes/teams/components/List/listItemStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
  src/themes/teams/components/Menu/menuVariables.ts
  src/themes/teams/components/Popup/popupContentStyles.ts
  src/themes/teams/components/Popup/popupContentVariables.ts
  src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
  src/themes/teams/components/Status/statusStyles.ts
  src/themes/teams/components/Tree/treeItemStyles.ts
  src/themes/teams/components/Tree/treeStyles.ts
  src/themes/teams/components/Tree/treeTitleStyles.ts
  src/themes/teams/siteVariables.ts
  src/themes/teams/utils/index.ts
  test/specs/lib/fontSizeUtility-test.ts
Labels: fix

#685 feat(Loader): add component
  CHANGELOG.md
  docs/src/examples/components/Loader/Types/LoaderExample.tsx
  docs/src/examples/components/Loader/Types/LoaderExampleLabel.shorthand.tsx
  docs/src/examples/components/Loader/Types/index.tsx
  docs/src/examples/components/Loader/Variations/LoaderExampleInline.tsx
  docs/src/examples/components/Loader/Variations/LoaderExampleLabelPosition.shorthand.tsx
  docs/src/examples/components/Loader/Variations/LoaderExampleSize.tsx
  docs/src/examples/components/Loader/Variations/index.tsx
  docs/src/examples/components/Loader/index.tsx
  src/components/Loader/Loader.tsx
  src/index.ts
  src/lib/accessibility/Behaviors/Loader/loaderBehavior.ts
  src/lib/accessibility/index.ts
  src/themes/base/componentStyles.ts
  src/themes/base/componentVariables.ts
  src/themes/base/components/Loader/loaderStyles.ts
  src/themes/base/components/Loader/loaderVariables.ts
  test/specs/behaviors/behavior-test.tsx
  test/specs/components/Loader/Loader-test.tsx
Labels: ready for review

#627 fix(FocusTrapZone): Do not focus trigger on outside click
  docs/src/examples/components/Portal/Types/PortalExampleFocusTrapped.shorthand.tsx
  docs/src/examples/components/Portal/Types/PortalExampleFocusTrapped.tsx
  src/lib/accessibility/FocusZone/CHANGELOG.md
  src/lib/accessibility/FocusZone/FocusTrapZone.tsx
  src/lib/accessibility/FocusZone/FocusTrapZone.types.tsx
Labels: fix, ready for review, vsts

#689 fix(ChatMessage): focus outline visible only during keyboard navigation
  CHANGELOG.md
  src/components/Attachment/Attachment.tsx
  src/components/Chat/ChatMessage.tsx
  src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: fix, ready for review

#702 fix(Provider): correctly handle change of renderer
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  src/components/Provider/Provider.tsx
Labels: fix, ready for merge

#647 feat(Label): add `color` prop
  CHANGELOG.md
  docs/src/examples/components/Label/Variations/LabelExampleColor.shorthand.tsx
  docs/src/examples/components/Label/Variations/index.tsx
  src/components/Label/Label.tsx
  src/lib/colorUtils.ts
  src/lib/commonPropInterfaces.ts
  src/lib/commonPropTypes.ts
  src/lib/index.ts
  src/lib/renderComponent.tsx
  src/themes/base/colors.ts
  src/themes/base/siteVariables.ts
  src/themes/teams/colors.ts
  src/themes/teams/components/Label/labelStyles.ts
  src/themes/teams/components/Label/labelVariables.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/siteVariables.ts
  src/themes/types.ts
Labels: RFC, ready for review, vsts

#705 fix(Popup): opened popup causes infinite rendering loop
  CHANGELOG.md
  docs/src/examples/components/Popup/Usage/PopupExampleAsync.shorthand.tsx
  docs/src/examples/components/Popup/Usage/index.tsx
  src/components/Popup/Popup.tsx
Labels: fix, ready for review

#714 feat(createComponent): add styles and accessibility props
  CHANGELOG.md
  docs/src/views/IntegrateCustomComponents.tsx
  src/lib/createStardustComponent.tsx
Labels: ready for review

#695 fix(Menu): Menu docs refactor
  CHANGELOG.md
  docs/src/examples/components/Menu/Slots/MenuExample.shorthand.tsx
  docs/src/examples/components/Menu/Slots/MenuExampleDivider.shorthand.tsx
  docs/src/examples/components/Menu/Slots/MenuExampleIconOnly.shorthand.tsx
  docs/src/examples/components/Menu/Slots/MenuExampleWithIcons.shorthand.tsx
  docs/src/examples/components/Menu/Slots/index.tsx
  docs/src/examples/components/Menu/States/MenuItemExampleDisabled.shorthand.tsx
  docs/src/examples/components/Menu/States/index.tsx
  docs/src/examples/components/Menu/Types/MenuExamplePointing.shorthand.tsx
  docs/src/examples/components/Menu/Types/MenuExampleUnderlined.shorthand.tsx
  docs/src/examples/components/Menu/Types/MenuExampleVerticalWithSubmenu.shorthand.tsx
  docs/src/examples/components/Menu/Types/index.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleTabList.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  docs/src/examples/components/Menu/Usages/MenuExampleWithSubmenu.shorthand.tsx
  docs/src/examples/components/Menu/Usages/index.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleFluid.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyPrimaryInverted.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleIconOnlyVerticalPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePillsVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointing.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingStart.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePointingStartPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExamplePrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleUnderlinedPrimary.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVerticalFluid.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleVerticalPointingEnd.shorthand.tsx
  docs/src/examples/components/Menu/Variations/MenuExampleWithIconsVertical.shorthand.tsx
  docs/src/examples/components/Menu/Variations/index.tsx
  docs/src/examples/components/Menu/index.tsx
Labels: ready for review

#720 fix(ComponentExample|ComponentSourceManager): fix initial state of knobs, fix undeletable code
  CHANGELOG.md
  docs/src/app.tsx
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ComponentDoc/ComponentSourceManager/ComponentSourceManager.ts
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/context/ExampleContext.ts
  docs/src/context/ThemeContext.tsx
Labels: fix, ready for review

#723 fix(chore): fix test:projects task
  build/gulp/tasks/test-projects.tsx
Labels: fix, ready for review

#725 refactor(Dropdown): rename DropdownLabel to DropdownSelectedItem
  CHANGELOG.md
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownSelectedItem.tsx
  src/index.ts
  src/themes/teams/componentStyles.ts
  src/themes/teams/components/Dropdown/dropdownSelectedItemStyles.ts
  src/themes/teams/components/Dropdown/dropdownStyles.ts
Labels: ready for review

#686 feat(Menu): Behaviors for submenu - toolbar and menu
  CHANGELOG.md
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  src/components/Menu/MenuItem.tsx
  src/lib/accessibility/Behaviors/Attachment/attachmentBehavior.ts
  src/lib/accessibility/Behaviors/List/selectableListItemBehavior.ts
  src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  src/lib/accessibility/Behaviors/Radio/radioGroupBehavior.ts
  src/lib/accessibility/Behaviors/Tab/tabBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/toolbarButtonBehavior.ts
  test/specs/behaviors/testDefinitions.ts
  test/specs/commonTests/handlesAccessibility.tsx
Labels: ready for review

#733 feat(docs): updated scope of the readme doc
  README.md
Labels: docs, ready for review

#735 fix(factories): remove `render` from default options
  CHANGELOG.md
  src/lib/factories.ts
  test/specs/lib/factories-test.tsx
Labels: fix, ready for review

#734 chore(tests): fix behavior test regex
  test/specs/behaviors/testDefinitions.ts
Labels: ready for merge

#728 fix(ComponentSidebar): remove empty item in docs sidebar
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebar.tsx
Labels: fix, ready for review

#740 fix(typings): synthetic event
  CHANGELOG.md
  types/utils.d.ts
Labels: fix, ready for review

#727 fix(List): focus outline visible only during keyboard navigation
  CHANGELOG.md
  src/components/List/ListItem.tsx
  src/themes/teams/components/List/listItemStyles.ts
  src/themes/teams/components/List/listItemVariables.ts
Labels: fix, ready for review

#745 fix(docs): avatar size example
  CHANGELOG.md
  docs/src/examples/components/Avatar/Variations/AvatarExampleSize.shorthand.tsx
Labels: fix, ready for merge

#713 feat(slot): rename Slot to Box and export
  CHANGELOG.md
  build/gulp/tasks/docs.ts
  src/components/Attachment/Attachment.tsx
  src/components/Box/Box.tsx
  src/components/Button/Button.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Form/FormField.tsx
  src/components/Input/Input.tsx
  src/components/Loader/Loader.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Segment/Segment.tsx
  src/index.ts
  test/specs/commonTests/implementsWrapperProp.tsx
  test/specs/components/Box/Box-test.ts
  test/specs/components/Chat/ChatItem-test.tsx
  test/specs/components/Chat/ChatMessage-test.tsx
  test/specs/components/Form/FormField-test.tsx
  test/specs/components/Input/Input-test.tsx
  test/specs/components/Slot/Slot-test.ts
Labels: ready for review

#718 fix(core): replace lodash/fp with lodash
  .circleci/config.yml
  CHANGELOG.md
  build/gulp/tasks/test-unit.ts
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/utils/examplePathToHash.ts
  src/lib/customPropTypes.tsx
Labels: fix, ready for review

#743 chore(perf): create scaffold config
  build/gulp/plugins/gulp-example-menu.ts
  build/gulp/tasks/docs.ts
  build/tsconfig.perf.json
  build/webpack.config.perf.ts
  config.ts
  docs/src/components/ComponentDoc/ComponentSidebar/ComponentSidebarSection.tsx
  docs/src/components/ComponentDoc/ExampleSection.tsx
  docs/src/components/ComponentDoc/PerformanceSection.tsx
  docs/src/examples/components/Button/Performance/Button.perf.tsx
  docs/src/examples/components/Button/Performance/index.tsx
  docs/src/examples/components/Button/index.tsx
  docs/src/utils/exampleKebabNameToSourceFilename.ts
  package.json
  perf/src/index.html
  perf/src/index.tsx
Labels: ready for review

#750 fix(Popup): Do not stop propagation when pressing Esc on trigger element
  CHANGELOG.md
  src/components/Popup/Popup.tsx
Labels: fix, ready for review

#721 feat(MenuItem|AccordionTitle): add ability for removing and customizing the (active|submenu) indicator
  CHANGELOG.md
  docs/src/examples/components/Indicator/Types/IndicatorExample.shorthand.tsx
  docs/src/examples/components/Indicator/Types/IndicatorExampleDirection.shorthand.tsx
  docs/src/examples/components/Indicator/Types/IndicatorExampleIcon.shorthand.tsx
  docs/src/examples/components/Indicator/Types/index.tsx
  docs/src/examples/components/Indicator/index.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Icon/Icon.tsx
  src/components/Indicator/Indicator.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/index.ts
  src/themes/teams/components/Accordion/accordionTitleStyles.ts
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/siteVariables.ts
  src/themes/teams/utils/index.ts
  test/specs/components/Indicator/Indicator-test.ts
Labels: ready for review

#747 fix(teams-theme): fix styles for the Status and Chat Message components
  CHANGELOG.md
  src/themes/teams/components/Chat/chatMessageVariables.ts
  src/themes/teams/components/Status/statusStyles.ts
Labels: ready for review

#737 docs(Prototype): Replace Popup with Submenu in Popover prototype
  docs/src/examples/components/Menu/Usages/MenuExampleToolbar.shorthand.tsx
  docs/src/prototypes/chatMessageWithPopover/ChatWithPopover.tsx
  docs/src/prototypes/chatMessageWithPopover/Popover.tsx
Labels: enhancement, ready for review

#752 fix(Layout): 'start' and 'main' areas content alignment
  CHANGELOG.md
  src/themes/teams/components/Layout/layoutStyles.ts
Labels: fix, ready for review

#751 docs: improve docs for shorthand props
  CHANGELOG.md
  docs/src/components/CodeSnippet.tsx
  docs/src/views/ShorthandProps.tsx
Labels: ready for review

#704 feat(rtl): add span element with dir: 'auto' for the strings used in the Stardust components
  CHANGELOG.md
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/AccordionContent.tsx
  src/components/Accordion/AccordionTitle.tsx
  src/components/Box/Box.tsx
  src/components/Button/Button.tsx
  src/components/Button/ButtonGroup.tsx
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Divider/Divider.tsx
  src/components/Form/Form.tsx
  src/components/Grid/Grid.tsx
  src/components/Header/Header.tsx
  src/components/Header/HeaderDescription.tsx
  src/components/ItemLayout/ItemLayout.tsx
  src/components/Label/Label.tsx
  src/components/Layout/Layout.tsx
  src/components/List/List.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Popup/PopupContent.tsx
  src/components/Portal/Portal.tsx
  src/components/RadioGroup/RadioGroup.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/components/Segment/Segment.tsx
  src/components/Text/Text.tsx
  src/components/Tree/Tree.tsx
  src/components/Tree/TreeItem.tsx
  src/components/Tree/TreeTitle.tsx
  src/lib/index.ts
  src/lib/rtlTextContainer.tsx
Labels: ready for review

#674 fix(Prototype): Chat pane prototype accessibility improvements
  docs/src/prototypes/chatPane/chatPaneContent.tsx
  docs/src/prototypes/chatPane/chatPaneHeader.tsx
  docs/src/prototypes/chatPane/chatProtoStyle.ts
  docs/src/prototypes/chatPane/composeMessage.tsx
Labels: ready for review

#141 chore: Component performance tests
  build/gulp/plugins/gulp-webpack.ts
  build/gulp/tasks/docs.ts
  build/gulp/tasks/perf.ts
  config.ts
  docs/src/examples/components/Attachment/Performance/Attachment.perf.tsx
  docs/src/examples/components/Attachment/Performance/index.tsx
  docs/src/examples/components/Attachment/index.tsx
  docs/src/examples/components/Button/Performance/Button.perf.tsx
  docs/src/examples/components/Divider/Performance/Divider.perf.tsx
  docs/src/examples/components/Divider/Performance/index.tsx
  docs/src/examples/components/Divider/index.tsx
  docs/src/examples/components/Header/Performance/Header.perf.tsx
  docs/src/examples/components/Header/Performance/HeaderDescription.perf.tsx
  docs/src/examples/components/Header/Performance/index.tsx
  docs/src/examples/components/Header/index.tsx
  docs/src/examples/components/Icon/Performance/Icon.perf.tsx
  docs/src/examples/components/Icon/Performance/index.tsx
  docs/src/examples/components/Icon/index.tsx
  docs/src/examples/components/Loader/Performance/Loader.perf.tsx
  docs/src/examples/components/Loader/Performance/index.tsx
  docs/src/examples/components/Loader/index.tsx
  gulpfile.ts
  package.json
  perf/src/index.tsx
  perf/types.tsx
  tsconfig.json
  yarn.lock
Labels: ready for review

#759 fix(factories): reverted changed for not passing props to elements in the factories
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  docs/src/prototypes/chatPane/index.tsx
  docs/src/views/ShorthandProps.tsx
  src/lib/factories.ts
  test/specs/lib/factories-test.tsx
Labels: ready for review

#619 fix(Popup): call onOpenChange on all user actions
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupControlledExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupControlledExample.tsx
  src/components/Popup/Popup.tsx
  src/lib/AutoControlledComponent.tsx
  test/specs/components/Popup/Popup-test.tsx
Labels: ready for merge, ready for review, vsts

#761 fix(ChatMessage): Author element should always be rendered
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Dropdown/Dropdown.tsx
  src/lib/accessibility/Styles/accessibilityStyles.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
Labels: fix, ready for review

#762 fix(Text): refactor variables to match `size` prop
  CHANGELOG.md
  docs/src/examples/components/Text/Variations/TextExampleColor.shorthand.tsx
  docs/src/examples/components/Text/Variations/TextExampleColor.tsx
  src/themes/base/components/Text/textStyles.ts
  src/themes/base/components/Text/textVariables.ts
  src/themes/base/siteVariables.ts
  src/themes/teams/components/Menu/menuVariables.ts
  src/themes/teams/siteVariables.ts
Labels: fix, ready for review

#770 feat: remove props from variables function
  CHANGELOG.md
  docs/src/examples/components/RadioGroup/Types/RadioGroupColorPickerExample.shorthand.tsx
  src/components/RadioGroup/RadioGroupItem.tsx
  src/lib/renderComponent.tsx
  src/themes/teams/components/RadioGroup/radioGroupItemStyles.ts
  src/themes/teams/components/RadioGroup/radioGroupItemVariables.ts
Labels: ready for review

#768 chore(package): update Fela to latest
  CHANGELOG.md
  build/webpack.config.perf.ts
  package.json
  src/components/Provider/Provider.tsx
  src/components/Provider/ProviderConsumer.tsx
  src/lib/renderComponent.tsx
  types/react-fela/index.d.ts
  yarn.lock
Labels: ready for review

#711 feat(chore): run visual tests in parallel
  .circleci/config.yml
Labels: ready for review

#772 fix(List): make `headerMedia` visible for screen readers
  CHANGELOG.md
  src/themes/teams/components/List/listItemStyles.ts
Labels: fix, ready for review

#767 feat(ChatItem): add attached prop, renamed gutterPosition to contentPosition
  CHANGELOG.md
  docs/src/examples/components/Chat/Types/ChatExample.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatExampleContentPosition.shorthand.tsx
  docs/src/examples/components/Chat/Types/ChatMessageExampleStyled.shorthand.tsx
  docs/src/examples/components/Chat/Types/index.tsx
  docs/src/prototypes/chatPane/chatPaneContent.tsx
  src/components/Chat/ChatItem.tsx
  src/components/Chat/ChatMessage.tsx
  src/index.ts
  src/themes/teams/components/Chat/chatItemStyles.ts
  src/themes/teams/components/Chat/chatMessageStyles.ts
  src/themes/teams/components/Chat/chatMessageVariables.ts
Labels: ready for review

#780 fix(Accordion): panel title layout
  CHANGELOG.md
  docs/src/examples/components/Accordion/Usage/AccordionPanelCustomContentExample.shorthand.tsx
  docs/src/examples/components/Accordion/Usage/AccordionPanelCustomTitleExample.shorthand.tsx
  docs/src/examples/components/Accordion/Usage/index.tsx
  docs/src/examples/components/Accordion/Variations/index.tsx
  docs/src/examples/components/Accordion/index.tsx
  src/components/Accordion/AccordionTitle.tsx
Labels: fix, ready for review

#771 fix(a11y): removed redundant a11y code from Dropdown
  CHANGELOG.md
  docs/src/examples/components/Dropdown/Types/DropdownExampleMultipleSearch.shorthand.tsx
  docs/src/examples/components/Dropdown/Types/DropdownExampleSingleSelection.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchFluid.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchFrenchLanguage.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/DropdownExampleMultipleSearchImageAndContent.shorthand.tsx
  docs/src/examples/components/Dropdown/Variations/index.tsx
  src/components/Dropdown/Dropdown.tsx
  src/index.ts
Labels: ready for review

#787 refactor(Portal): allow to use createRef() API in triggerRef
  CHANGELOG.md
  src/components/Dropdown/DropdownSearchInput.tsx
  src/components/Input/Input.tsx
  src/components/Portal/Portal.tsx
  src/components/Ref/Ref.tsx
  src/components/Ref/RefFindNode.tsx
  src/components/Ref/RefForward.tsx
  src/lib/customPropTypes.tsx
Labels: ready for review

#726 fix(Dropdown): Highlights selected option in single selection
  CHANGELOG.md
  package.json
  src/components/Dropdown/Dropdown.tsx
  yarn.lock
Labels: ready for review

#779 fix(List): handle onClick and onFocus on items correctly
  CHANGELOG.md
  src/components/List/List.tsx
  src/components/List/ListItem.tsx
  test/specs/components/List/List-test.tsx
Labels: fix, ready for review

#792 chore: add RTL examples for visual testing
  CHANGELOG.md
  build/gulp/plugins/gulp-example-menu.ts
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsMaximize.tsx
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/components/ExternalExampleLayout.tsx
  docs/src/examples/components/Button/Rtl/ButtonExample.rtl.tsx
  docs/src/examples/components/Button/Rtl/index.tsx
  docs/src/examples/components/Button/index.tsx
  docs/src/examples/components/Divider/Rtl/DividerExample.rtl.tsx
  docs/src/examples/components/Divider/Rtl/index.tsx
  docs/src/examples/components/Divider/index.tsx
  docs/src/routes.tsx
  docs/src/utils/exampleKebabNameToSourceFilename.ts
  screener.config.js
Labels: ready for merge

#788 feat(Icon): mark icons that should be rotated in rtl for teams theme
  CHANGELOG.md
  docs/src/examples/components/Icon/Variations/IconExampleSpace.shorthand.tsx
  src/themes/teams/components/Icon/iconStyles.ts
  src/themes/teams/components/Icon/svg/icons/bullets.tsx
  src/themes/teams/components/Icon/svg/icons/indent.tsx
  src/themes/teams/components/Icon/svg/icons/leave.tsx
  src/themes/teams/components/Icon/svg/icons/outdent.tsx
  src/themes/teams/components/Icon/svg/icons/redo.tsx
  src/themes/teams/components/Icon/svg/icons/send.tsx
  src/themes/teams/components/Icon/svg/icons/triangleRight.tsx
  src/themes/teams/components/Icon/svg/icons/undo.tsx
Labels: ready for review

#789 feat(pxToRem): remove global overrides for document styles
  CHANGELOG.md
  src/lib/fontSizeUtility.ts
  src/lib/index.ts
  test/specs/lib/fontSizeUtility-test.ts
Labels: ready for merge, ready for review

#786 fix(dropdown): style improvements
  CHANGELOG.md
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownSearchInput.tsx
  src/themes/teams/components/Dropdown/dropdownSearchInputStyles.ts
  src/themes/teams/components/Dropdown/dropdownStyles.ts
  src/themes/teams/components/Dropdown/dropdownVariables.ts
  src/themes/teams/components/Input/inputStyles.ts
  src/themes/teams/components/Input/inputVariables.ts
Labels: ready for review

#806 fix(acc): Remove popup trigger button role
  CHANGELOG.md
  src/lib/accessibility/Behaviors/Popup/popupBehavior.ts
Labels: fix, ready for review

#805 feat(accessibility): remove handledProps from behaviors
  CHANGELOG.md
  src/lib/accessibility/Behaviors/Menu/menuItemBehavior.ts
  src/lib/accessibility/Behaviors/Tab/tabBehavior.ts
  src/lib/accessibility/Behaviors/Toolbar/toolbarButtonBehavior.ts
  src/lib/accessibility/types.ts
  src/lib/renderComponent.tsx
Labels: ready for review

#809 feat(Header): add create() factory
  CHANGELOG.md
  src/components/Header/Header.tsx
Labels: enhancement, ready for review

#794 feat(Animation): support keyframes as functions and add keyframeParams prop
  CHANGELOG.md
  docs/src/examples/components/Animation/Types/AnimationExampleKeyframeParams.tsx
  docs/src/examples/components/Animation/Types/index.tsx
  src/components/Animation/Animation.tsx
  src/lib/createAnimationStyles.tsx
  src/themes/types.ts
Labels: ready for review

#808 feat(menu): Padding variables for horizontal menu
  CHANGELOG.md
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuVariables.ts
Labels: ready for review

#790 feat(Dialog): add component
  CHANGELOG.md
  docs/src/examples/components/Dialog/Content/DialogExampleContent.shorthand.tsx
  docs/src/examples/components/Dialog/Content/index.tsx
  docs/src/examples/components/Dialog/Types/DialogExample.shorthand.tsx
  docs/src/examples/components/Dialog/Types/index.tsx
  docs/src/examples/components/Dialog/Usage/DialogExampleCallbacks.shorthand.tsx
  docs/src/examples/components/Dialog/Usage/index.tsx
  docs/src/examples/components/Dialog/index.tsx
  src/components/Dialog/Dialog.tsx
  src/index.ts
  src/themes/base/componentStyles.ts
  src/themes/base/componentVariables.ts
  src/themes/base/components/Dialog/dialogStyles.ts
  src/themes/base/components/Dialog/dialogVariables.ts
Labels: enhancement, ready for review

#795 fix(Avatar): add white border around avatar in contrast theme
  CHANGELOG.md
  docs/src/examples/components/Avatar/Variations/AvatarExampleImageCustomization.shorthand.tsx
  src/themes/teams-high-contrast/components/Avatar/avatarVariables.ts
  src/themes/teams/components/Avatar/avatarStyles.ts
  src/themes/teams/components/Avatar/avatarVariables.ts
Labels: ready for review

#814 fix(MenuItem | MenuDivider): export Menu's Variables as MenuItem and MenuDivider's variables in Teams theme
  CHANGELOG.md
  src/themes/teams/componentVariables.ts
  src/themes/teams/components/Menu/menuDividerVariables.ts
  src/themes/teams/components/Menu/menuItemVariables.ts
Labels: ready for merge

#813 fix(MenuDivider): not shown when used on horizontal menus
  CHANGELOG.md
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuDivider.tsx
  src/themes/teams/components/Menu/menuDividerStyles.ts
  src/themes/teams/components/Menu/menuItemStyles.ts
  src/themes/teams/components/Menu/menuStyles.ts
Labels: ready for review
