Repository microsoft/fluent-ui-react, pull requests merged in 2020-01, with the labels that each got.

#2201 chore: revert "feat/base-theme"
  docs/src/app.tsx
  docs/src/components/DocsLayout.tsx
  docs/src/components/ExternalExampleLayout.tsx
  packages/react/src/index.ts
  packages/react/src/themes/base/index.ts
  packages/react/src/themes/index.ts
Labels: 🗑️ chore, 🚀 ready for review

#2202 fix(Popup): fix click outside when trigger is not defined
  CHANGELOG.md
  e2e/tests/popupWithoutTrigger-example.tsx
  e2e/tests/popupWithoutTrigger-test.ts
  packages/react/src/components/Popup/Popup.tsx
Labels: 🚀 ready for review, 🧰 fix

#2199 docs: accessibility fix for component toolbar
  docs/src/components/ComponentDoc/ComponentControls/ComponentControls.tsx
  docs/src/components/ComponentDoc/ComponentControls/ComponentControlsCodeSandbox/ComponentControlsCodeSandbox.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
Labels: 📚 docs, 🚀 ready for review, 🧰 fix

#2183 feat(Table): Support clickable cells, add prototype for table with sorting
  CHANGELOG.md
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/examples/components/Table/BestPractices/TableBestPractices.tsx
  docs/src/prototypes/table/AdvancedTable.tsx
  docs/src/prototypes/table/index.tsx
  docs/src/routes.tsx
  packages/accessibility/src/behaviors/Table/gridHeaderCellBehavior.ts
  packages/react/src/components/Table/Table.tsx
  packages/react/src/components/Table/TableCell.tsx
Labels: 🚀 ready for review

#2108 fix(SplitButton): Updating splitButton component to match Teams redlines
  CHANGELOG.md
  docs/src/examples/components/SplitButton/Slots/SplitButtonToggleButtonExample.shorthand.tsx
  docs/src/examples/components/SplitButton/Types/SplitButtonExampleSmall.shorthand.tsx
  docs/src/examples/components/SplitButton/Types/index.tsx
  packages/react/src/components/SplitButton/SplitButton.tsx
  packages/react/src/themes/teams/components/SplitButton/splitButtonStyles.ts
  packages/react/src/themes/teams/components/SplitButton/splitButtonVariables.ts
Labels: redlines, teams theme, 💅 styling issue, 🚀 ready for review

#1980 feat(bindings): add useAccessibility hook
  packages/accessibility/src/types.ts
  packages/react-bindings/README.md
  packages/react-bindings/src/accessibility/getAccessibility.ts
  packages/react-bindings/src/accessibility/getKeyDownHandlers.ts
  packages/react-bindings/src/accessibility/shouldHandleOnKeys.ts
  packages/react-bindings/src/accessibility/types.ts
  packages/react-bindings/src/hooks/useAccessibility.ts
  packages/react-bindings/src/index.ts
  packages/react-bindings/test/accesibility/getKeyDownHandlers-test.ts
  packages/react-bindings/test/accesibility/shouldHandleOnKeys-test.ts
  packages/react-bindings/test/hooks/useAccessibility-test.tsx
  packages/react/src/components/Carousel/CarouselNavigation.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Table/Table.tsx
  packages/react/src/components/Table/TableRow.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/src/components/Tree/TreeItem.tsx
  packages/react/src/utils/UIComponent.tsx
  packages/react/src/utils/applyAccessibilityKeyHandlers.ts
  packages/react/src/utils/createComponent.tsx
  packages/react/src/utils/createComponentInternal.ts
  packages/react/src/utils/getKeyDownHandlers.ts
  packages/react/src/utils/renderComponent.tsx
Labels: ⚙️ enhancement, 🚀 ready for review

#2213 docs: update CodeSandbox for issues
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: 📚 docs, 🚀 ready for review

#1387 chore(package): use Project References in TS
  build/gulp/tasks/bundle.ts
  package.json
  packages/ability-attributes/tsconfig.json
  packages/accessibility/test/behaviors/popupBehavior-test.tsx
  packages/accessibility/tsconfig.json
  packages/code-sandbox/tsconfig.json
  packages/docs-components/tsconfig.json
  packages/internal-tooling/package.json
  packages/react-bindings/package.json
  packages/react-bindings/src/FocusZone/FocusTrapZone.tsx
  packages/react-bindings/src/FocusZone/FocusZone.tsx
  packages/react-bindings/test/FocusZone/AutoFocusZone-test.tsx
  packages/react-bindings/test/FocusZone/FocusTrapZone-test.tsx
  packages/react-bindings/test/FocusZone/FocusZone-test.tsx
  packages/react-bindings/test/accesibility/getKeyDownHandlers-test.ts
  packages/react-bindings/tsconfig.json
  packages/react-component-event-listener/test/EventListener-test.tsx
  packages/react-component-event-listener/tsconfig.json
  packages/react-component-nesting-registry/src/NestingChild.tsx
  packages/react-component-nesting-registry/src/NestingRoot.tsx
  packages/react-component-nesting-registry/src/hooks/useNestingChild.ts
  packages/react-component-nesting-registry/src/hooks/useNestingRoot.ts
  packages/react-component-nesting-registry/tsconfig.json
  packages/react-component-ref/src/toRefObject.ts
  packages/react-component-ref/test/Ref-test.tsx
  packages/react-component-ref/test/RefForward-test.tsx
  packages/react-component-ref/tsconfig.json
  packages/react-proptypes/tsconfig.json
  packages/react/src/utils/getClasses.ts
  packages/react/test/specs/commonTests/eventTarget.ts
  packages/react/test/specs/commonTests/hasSubcomponents.ts
  packages/react/test/specs/commonTests/htmlIsAccessibilityCompliant.ts
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Avatar/Avatar-test.tsx
  packages/react/test/specs/components/Button/Button-test.tsx
  packages/react/test/specs/components/Chat/ChatMessage-test.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/specs/components/Form/FormField-test.tsx
  packages/react/test/specs/components/List/List-test.tsx
  packages/react/test/specs/components/Portal/Portal-test.tsx
  packages/react/test/specs/components/Provider/Provider-test.tsx
  packages/react/test/specs/components/Provider/ProviderConsumer-test.tsx
  packages/react/test/specs/components/Tooltip/Tooltip-test.tsx
  packages/react/test/specs/utils/doesNodeContainClick-test.ts
  packages/react/test/specs/utils/factories-test.tsx
  packages/react/test/specs/utils/felaInvokeKeyframesPlugin-test.ts
  packages/react/test/specs/utils/felaRenderer-test.tsx
  packages/react/test/specs/utils/mergeThemes/mergeComponentVariables-test.ts
  packages/react/test/specs/utils/mergeThemes/mergeFontFaces-test.ts
  packages/react/test/specs/utils/mergeThemes/mergeThemes-test.ts
  packages/react/test/tsconfig.json
  packages/react/tsconfig.json
  packages/state/package.json
  packages/state/tsconfig.json
  yarn.lock
Labels: 🗑️ chore, 🚀 ready for review

#2216 chore: use gulp-cache in CI
  .circleci/config.yml
Labels: 🗑️ chore, 🚀 ready for review

#2221 chore(Perf): Add renderComponent times to perf charts
  build/gulp/tasks/perf.ts
  build/gulp/tasks/stats.ts
  perf/src/index.tsx
  perf/types.ts
Labels: 🗑️ chore, 🚀 ready for review

#2217 feat(bindings): useStyles hook
  CHANGELOG.md
  packages/react-bindings/README.md
  packages/react-bindings/package.json
  packages/react-bindings/src/hooks/useStyles.ts
  packages/react-bindings/src/index.ts
  packages/react-bindings/src/styles/createAnimationStyles.tsx
  packages/react-bindings/src/styles/getStyles.ts
  packages/react-bindings/src/styles/resolveStylesAndClasses.tsx
  packages/react-bindings/src/styles/types.ts
  packages/react-bindings/test/hooks/useStyles-test.tsx
  packages/react-bindings/test/styles/createAnimationStyles-test.ts
  packages/react-bindings/test/styles/resolveStylesAndClasses-test.ts
  packages/react/src/components/Carousel/CarouselNavigation.tsx
  packages/react/src/components/Design/Design.tsx
  packages/react/src/components/ItemLayout/ItemLayout.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/themes/teams/components/Animation/animationStyles.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/types.ts
  packages/react/src/types.ts
  packages/react/src/utils/commonPropInterfaces.ts
  packages/react/src/utils/createComponent.tsx
  packages/react/src/utils/felaRenderer.tsx
  packages/react/src/utils/index.ts
  packages/react/src/utils/mergeProviderContexts.ts
  packages/react/src/utils/renderComponent.tsx
  packages/react/test/specs/components/Provider/Provider-test.tsx
  packages/styles/src/mergeThemes.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#2092 feat(List+Dropdown): wrapper for custom scrollbar in list
  CHANGELOG.md
  docs/src/prototypes/customScrollbar/index.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/List/List.tsx
Labels: 🚀 ready for review

#2239 fix(components): remove `animation` prop from all components
  CHANGELOG.md
  docs/src/views/Theming.tsx
  packages/react-bindings/src/styles/getStyles.ts
  packages/react/src/themes/teams/components/Text/textStyles.ts
  packages/react/src/utils/commonPropInterfaces.ts
  packages/react/test/specs/utils/__snapshots__/felaRenderer-test.tsx.snap
  packages/react/test/specs/utils/felaRenderer-test.tsx
Labels: ready for merge, 🧰 fix

#2256 perf: Store perf bundle and results to CI artifacts
  .circleci/config.yml
  build/dangerjs/checkPerfRegressions.ts
Labels: 🚀 ready for review

#2257 feat(react-bindings): added useTelemetry and improved returned value of other hooks
  CHANGELOG.md
  docs/src/prototypes/customToolbar/index.tsx
  packages/react-bindings/README.md
  packages/react-bindings/src/hooks/useStateManager.ts
  packages/react-bindings/src/hooks/useStyles.ts
  packages/react-bindings/src/index.ts
  packages/react-bindings/src/telemetry/types.ts
  packages/react-bindings/src/telemetry/useTelemetry.ts
  packages/react-bindings/test/hooks/useDispatchEffect-test.tsx
  packages/react-bindings/test/hooks/useStateManager-test.tsx
  packages/react-bindings/test/hooks/useStyles-test.tsx
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/MenuButton/MenuButton.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Portal/PortalInner.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/types.ts
  packages/react/src/utils/commonPropTypes.ts
  packages/react/src/utils/index.ts
  packages/react/src/utils/renderComponent.tsx
Labels: ⚙️ enhancement, 🚀 ready for review

#2226 feat(useStyles): avoid creating new instances of mergedStyles if there are no inline overrides
  packages/react-bindings/src/styles/getStyles.ts
Labels: 🚀 ready for review

#2265 chore: remove FocusZoneMode
  CHANGELOG.md
  docs/src/views/AccessibilityBehaviors.tsx
  packages/accessibility/src/behaviors/Chat/chatBehavior.ts
  packages/accessibility/src/behaviors/Chat/chatMessageBehavior.ts
  packages/accessibility/src/behaviors/Grid/gridBehavior.ts
  packages/accessibility/src/behaviors/Grid/gridHorizontalBehavior.ts
  packages/accessibility/src/behaviors/HierarchicalTree/hierarchicalTreeBehavior.ts
  packages/accessibility/src/behaviors/List/navigableListBehavior.ts
  packages/accessibility/src/behaviors/List/selectableListBehavior.ts
  packages/accessibility/src/behaviors/Menu/menuBehavior.ts
  packages/accessibility/src/behaviors/Menu/submenuBehavior.ts
  packages/accessibility/src/behaviors/Tab/tabListBehavior.ts
  packages/accessibility/src/behaviors/Table/gridCellMultipleFocusableBehavior.ts
  packages/accessibility/src/behaviors/Table/gridHeaderRowBehavior.ts
  packages/accessibility/src/behaviors/Table/gridNestedBehavior.ts
  packages/accessibility/src/behaviors/Table/gridRowNestedBehavior.ts
  packages/accessibility/src/behaviors/Toolbar/menuAsToolbarBehavior.ts
  packages/accessibility/src/behaviors/Toolbar/toolbarBehavior.ts
  packages/accessibility/src/behaviors/Toolbar/toolbarMenuBehavior.ts
  packages/accessibility/src/behaviors/Tree/treeBehavior.ts
  packages/accessibility/src/focusZone/types.ts
  packages/accessibility/test/behaviors/testDefinitions.ts
  packages/react-bindings/src/FocusZone/focusUtilities.ts
  packages/react/src/utils/renderComponent.tsx
  packages/react/test/specs/commonTests/handlesAccessibility.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Chat/Chat-test.ts
  packages/react/test/specs/components/Chat/ChatMessage-test.tsx
  packages/react/test/specs/components/Menu/Menu-test.tsx
Labels: 🗑️ chore, 🚀 ready for review

#2238 chore(Box|Button|Image|Avatar): converting components with hooks
  CHANGELOG.md
  packages/accessibility/src/behaviors/Image/imageBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/react-proptypes/src/index.ts
  packages/react/src/components/Avatar/Avatar.tsx
  packages/react/src/components/Box/Box.tsx
  packages/react/src/components/Button/Button.tsx
  packages/react/src/components/Image/Image.tsx
  packages/react/src/themes/teams-high-contrast/components/Avatar/avatarVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Avatar/avatarStyles.ts
  packages/react/src/themes/teams/components/Avatar/avatarVariables.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Image/imageStyles.ts
  packages/react/src/themes/teams/components/Image/imageVariables.ts
  packages/react/src/themes/teams/types.ts
  packages/react/src/types.ts
  packages/react/test/specs/commonTests/handlesAccessibility.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Avatar/Avatar-test.tsx
  packages/react/test/specs/components/Button/Button-test.tsx
  packages/react/test/specs/components/Image/Image-test.tsx
  packages/react/test/utils/withProvider.tsx
Labels: ready for merge, 🗑️ chore

#2268 fix(hooks): minor fixes to useAccessibility & useStyles
  CHANGELOG.md
  packages/react-bindings/src/hooks/useAccessibility.ts
  packages/react-bindings/src/hooks/useStateManager.ts
Labels: 🚀 ready for review, 🧰 fix

#2115 feat(Animation): add logic for mount/remove children
  CHANGELOG.md
  build/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
  docs/src/examples/components/Animation/Performance/AnimationMinimal.perf.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleDirection.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleFillMode.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleIterationCount.tsx
  docs/src/examples/components/Animation/Types/AnimationExampleTimingFunction.tsx
  docs/src/examples/components/Animation/Usage/AnimationExampleVisible.shorthand.tsx
  docs/src/examples/components/Animation/Usage/index.tsx
  docs/src/examples/components/Animation/index.tsx
  packages/code-sandbox/src/createCallbackLogFormatter.ts
  packages/docs-components/src/knobs/useLogKnob.ts
  packages/react/package.json
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/themes/teams/components/Animation/animationStyles.ts
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Animation/Animation-test.tsx
  packages/react/test/specs/utils/__snapshots__/felaRenderer-test.tsx.snap
  packages/react/test/specs/utils/felaRenderer-test.tsx
  yarn.lock
Labels: ⚙️ enhancement, 🚀 ready for review

#2275 feat(useAccessibility): add support for FocusZone
  packages/react-bindings/src/FocusZone/FocusZone.types.ts
  packages/react-bindings/src/hooks/useAccessibility.ts
  packages/react-bindings/test/hooks/useAccessibility-test.tsx
Labels: ⚙️ enhancement, 🚀 ready for review

#2267 chore(List): move to hooks
  CHANGELOG.md
  packages/accessibility/src/behaviors/index.ts
  packages/react/src/components/List/List.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/themes/teams/components/List/listItemStyles.ts
  packages/react/src/themes/teams/components/List/listStyles.ts
  packages/react/src/themes/teams/types.ts
  packages/react/test/specs/components/List/List-test.tsx
  packages/react/test/specs/components/List/ListItem-test.tsx
  packages/state/src/index.ts
  packages/state/src/managers/listManager.ts
Labels: 🗑️ chore, 🚀 ready for review

#2286 chore(Popup|MenuButton): remove `mountDocument` prop
  CHANGELOG.md
  packages/react/src/components/MenuButton/MenuButton.tsx
  packages/react/src/components/Popup/Popup.tsx
Labels: 🗑️ chore, 🚀 ready for review

#2252 chore: Normalize custom types
  build/config.ts
  build/package.json
  build/screener/screener.config.js
  build/screener/screener.steps.ts
  build/tsconfig.common.json
  build/tsconfig.docs.json
  build/tsconfig.e2e.json
  build/tsconfig.json
  build/tsconfig.perf.json
  build/tsconfig.test.json
  build/webpack.config.e2e.ts
  build/webpack.config.perf.ts
  build/webpack.config.stats.ts
  build/webpack.config.ts
  build/webpack.config.umd.ts
  docs/package.json
  docs/src/components/DocsLayout.tsx
  docs/src/global.d.ts
  docs/src/utils/componentInfoContext.ts
  docs/tsconfig.json
  e2e/tsconfig.json
  gulpfile.ts
  package.json
  packages/digest/tsconfig.json
  packages/perf-test/package.json
  packages/perf-test/tsconfig.json
  packages/playground/package.json
  packages/react-bindings/package.json
  packages/react-component-event-listener/package.json
  packages/react/package.json
  packages/react/test/utils/domEvent.ts
  perf/package.json
  perf/tsconfig.json
  scripts/config/typescript/tsconfig.common.json
  types/anchor-js.d.ts
  types/classnames/index.d.ts
  types/screener-runner/index.d.ts
  types/screener.d.ts
  types/simulant.d.ts
  yarn.lock
Labels: ready for merge, 🗑️ chore

#2211 fix(Button): Add new color scheme tokens & update iconOnly button styles for Teams theme
  CHANGELOG.md
  packages/react/src/themes/teams-dark/colors.ts
  packages/react/src/themes/teams-high-contrast/colors.ts
  packages/react/src/themes/teams/colors.ts
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
  packages/react/src/themes/teams/components/Button/buttonStyles.ts
  packages/react/src/themes/teams/components/Button/buttonVariables.ts
Labels: 🚀 ready for review

#2302 fix(Attachment): fix an CSS-in-JS issue in styles
  packages/react/src/themes/teams/components/Attachment/attachmentStyles.ts
Labels: ready for merge, 🧰 fix

#2300 fix(Chat): positiong fixes for actions
  CHANGELOG.md
  docs/src/examples/components/Chat/Content/ChatExampleActions.shorthand.steps.ts
  docs/src/examples/components/Chat/Usage/ChatExampleInScrollable.shorthand.tsx
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/ChatWithPopover.tsx
  docs/src/prototypes/chatMessages/ChatMessageWithPopover/ReactionPopup.tsx
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Popup/popupStyles.ts
  packages/react/src/utils/positioner/Popper.tsx
  packages/react/src/utils/positioner/initialStyles.ts
  packages/react/src/utils/positioner/types.ts
Labels: 🚀 ready for review, 🧰 fix

#2301 chore: fix webpack HMR path
  build/webpack.config.ts
  yarn.lock
Labels: 🗑️ chore, 🚀 ready for review
