Repository microsoft/fluent-ui-react, pull requests merged in 2020-02, with the labels that each got.

#2294 perf: Add regression tests
  .circleci/config.yml
  build/dangerjs/checkPerfRegressions.ts
  dangerfile.ts
  package.json
  packages/perf-test/just.config.ts
  packages/perf-test/package.json
  packages/perf-test/tasks/perf-test.ts
Labels: 🚀 ready for review

#2306 fix(FocusZone): Cleanup DOM element references on unmount
  CHANGELOG.md
  packages/react-bindings/src/FocusZone/FocusZone.tsx
Labels: 🚀 ready for review, 🧰 fix

#2287 chore(Ref): remove `toRefObject()` function
  CHANGELOG.md
  docs/src/prototypes/EditorToolbar/EditorToolbar.tsx
  packages/react-component-event-listener/src/EventListener.ts
  packages/react-component-event-listener/src/types.ts
  packages/react-component-event-listener/src/useEventListener.ts
  packages/react-component-event-listener/test/EventListener-test.tsx
  packages/react-component-ref/src/index.ts
  packages/react-component-ref/src/toRefObject.ts
  packages/react-component-ref/test/toRefObject-test.ts
  packages/react/src/components/Debug/Debug.tsx
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Menu/MenuItem.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/Portal.tsx
  packages/react/src/components/Toolbar/Toolbar.tsx
  packages/react/src/components/Toolbar/ToolbarItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
Labels: 🗑️ chore, 🚀 ready for review, 🧰 fix

#2290 feat(Accordion): disabled accordion title
  CHANGELOG.md
  packages/accessibility/src/behaviors/Accordion/accordionTitleBehavior.ts
  packages/react/src/components/Accordion/AccordionTitle.tsx
  packages/react/src/themes/teams/components/Accordion/accordionTitleStyles.ts
  packages/react/test/specs/components/Accordion/AccordionTitle-test.tsx
Labels: 🚀 ready for review

#2312 feat(styles): typing improvements
  CHANGELOG.md
  packages/react-bindings/src/hooks/useStyles.ts
  packages/react-bindings/src/styles/getStyles.ts
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/utils/createComponent.tsx
  packages/react/src/utils/renderComponent.tsx
  packages/styles/src/types.ts
Labels: ready for merge, 🧰 fix

#2282 chore: Add local-sandbox package
  packages/local-sandbox/.browserslistrc
  packages/local-sandbox/README.md
  packages/local-sandbox/babel.config.js
  packages/local-sandbox/package.json
  packages/local-sandbox/public/index.html
  packages/local-sandbox/server.js
  packages/local-sandbox/src/index.tsx
  packages/local-sandbox/tsconfig.json
  packages/local-sandbox/webpack.config.ts
  yarn.lock
Labels: 🚀 ready for review

#2317 chore: add support for optional chaining and coalescing operator
  build/babel/index.js
  build/package.json
  packages/accessibility/package.json
  packages/docs-components/package.json
  packages/react-bindings/package.json
  packages/react-component-event-listener/package.json
  packages/react-component-nesting-registry/package.json
  packages/react-component-ref/package.json
  packages/react-proptypes/package.json
  packages/react/package.json
  packages/state/package.json
  packages/styles/package.json
  scripts/package.json
  yarn.lock
Labels: 🗑️ chore, 🚀 ready for review

#2323 fix(typings): enable strict mode for projects
  CHANGELOG.md
  build/gulp/tasks/test-projects/typings/tsconfig.json
  packages/react/src/components/Carousel/Carousel.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/types.ts
  packages/react/src/utils/applyAccessibilityKeyHandlers.ts
Labels: 🗑️ chore, 🚀 ready for review, 🧰 fix

#2315 chore(Provider): refactor to function component
  packages/react/src/components/Provider/Provider.tsx
Labels: 🗑️ chore, 🚀 ready for review

#2307 chore: move more components
  CHANGELOG.md
  packages/accessibility/src/behaviors/Checkbox/checkboxBehavior.ts
  packages/accessibility/src/behaviors/Icon/iconBehavior.ts
  packages/accessibility/src/behaviors/Slider/sliderBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/react-proptypes/src/index.ts
  packages/react/src/components/Checkbox/Checkbox.tsx
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/components/Label/Label.tsx
  packages/react/src/components/Slider/Slider.tsx
  packages/react/src/components/Status/Status.tsx
  packages/react/src/components/Text/Text.tsx
  packages/react/src/themes/teams/components/Checkbox/checkboxStyles.ts
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
  packages/react/src/themes/teams/components/Label/labelStyles.ts
  packages/react/src/themes/teams/components/Slider/sliderStyles.ts
  packages/react/src/themes/teams/components/Status/statusStyles.ts
  packages/react/src/themes/teams/components/Text/textStyles.ts
  packages/react/src/themes/teams/types.ts
  packages/react/test/specs/commonTests/handlesAccessibility.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Checkbox/Checkbox-test.tsx
  packages/react/test/specs/components/Icon/Icon-test.tsx
  packages/react/test/specs/components/Label/Label-test.tsx
  packages/react/test/specs/components/Slider/Slider-test.tsx
  packages/react/test/specs/components/Status/Status-test.tsx
  packages/react/test/specs/components/Text/Text-test.tsx
  packages/state/src/index.ts
  packages/state/src/managers/checkboxManager.ts
  packages/state/src/managers/sliderManager.ts
Labels: 🗑️ chore, 🚀 ready for review

#2329 chore(build): Add sourcemaps to commonjs and es packages
  build/gulp/tasks/bundle.ts
  build/package.json
  packages/local-sandbox/package.json
  packages/local-sandbox/webpack.config.ts
  yarn.lock
Labels: 🚀 ready for review

#2330 fix(SSR): fix document usage and add project test
  CHANGELOG.md
  build/gulp/tasks/test-projects.ts
  build/gulp/tasks/test-projects/nextjs/index.js
  packages/react-bindings/src/hooks/useIsomorphicLayoutEffect.ts
  packages/react-bindings/src/index.ts
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/types.ts
  packages/react/src/utils/UIComponent.tsx
  packages/react/src/utils/mergeProviderContexts.ts
  packages/react/src/utils/positioner/Popper.tsx
Labels: 🚀 ready for review, 🧰 fix

#2284 fix(knobs): separate contexts to avoid useless updates
  packages/docs-components/src/knobs/KnobContexts.ts
  packages/docs-components/src/knobs/KnobProvider.tsx
  packages/docs-components/src/knobs/LogInspector.tsx
  packages/docs-components/src/knobs/types.ts
  packages/docs-components/src/knobs/useLogKnob.ts
Labels: 🚀 ready for review, 🧰 fix

#2309 feat(useStyles): add caching when no inline overrides are applied
  CHANGELOG.md
  packages/react-bindings/src/hooks/useStyles.ts
  packages/react-bindings/src/styles/getStyles.ts
  packages/react-bindings/src/styles/resolveStyles.ts
  packages/react-bindings/src/styles/resolveStylesAndClasses.tsx
  packages/react-bindings/src/styles/resolveVariables.ts
  packages/react-bindings/src/styles/types.ts
  packages/react-bindings/test/hooks/useStyles-test.tsx
  packages/react-bindings/test/styles/resolveStyles-test.ts
  packages/react-bindings/test/styles/resolveStylesAndClasses-test.ts
  packages/react-bindings/test/styles/resolveVariables-test.ts
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/types.ts
  packages/react/src/utils/mergeProviderContexts.ts
  packages/react/src/utils/renderComponent.tsx
  packages/react/test/utils/withProvider.tsx
Labels: perf, 🚀 ready for review

#2292 feat(context-selector): add initial implementation
  packages/react-context-selector/.gulp.js
  packages/react-context-selector/README.md
  packages/react-context-selector/babel.config.js
  packages/react-context-selector/gulpfile.ts
  packages/react-context-selector/jest.config.js
  packages/react-context-selector/package.json
  packages/react-context-selector/src/createContext.ts
  packages/react-context-selector/src/index.ts
  packages/react-context-selector/src/types.ts
  packages/react-context-selector/src/useContextSelector.ts
  packages/react-context-selector/src/useContextSelectors.ts
  packages/react-context-selector/src/utils.ts
  packages/react-context-selector/test/createContext-test.tsx
  packages/react-context-selector/test/useContextSelector-test.tsx
  packages/react-context-selector/test/useContextSelectors-test.tsx
  packages/react-context-selector/tsconfig.json
Labels: ⚙️ enhancement, 🚀 ready for review

#2346 fix(Icon): exclude name from stylesProps if svg icon is used
  packages/react/src/components/Icon/Icon.tsx
  packages/react/src/themes/teams/components/Icon/iconStyles.ts
Labels: ready for merge, 🧰 fix

#2258 chore(Animation): move to function component, styles in theme are not required
  CHANGELOG.md
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Animation/animationStyles.ts
  packages/react/src/themes/teams/components/Animation/animationVariables.ts
  packages/react/test/specs/components/Animation/Animation-test.tsx
  packages/react/test/specs/utils/felaRenderer-test.tsx
Labels: 🗑️ chore, 🚀 ready for review

#2347 fix(useStateManager): keep reference to `actions`
  CHANGELOG.md
  packages/react-bindings/src/hooks/useStateManager.ts
  packages/react-bindings/test/hooks/useStateManager-test.tsx
Labels: 🚀 ready for review, 🧰 fix

#2333 chore(Popup|Tooltip): remove styles from parent components
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupCustomTargetExample.shorthand.steps.ts
  docs/src/examples/components/Popup/Types/PopupCustomTargetExample.shorthand.tsx
  docs/src/examples/components/Popup/Types/PopupCustomTargetExample.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
  packages/react/src/themes/teams/components/Popup/popupContentVariables.ts
  packages/react/src/themes/teams/components/Popup/popupStyles.ts
  packages/react/src/themes/teams/components/Popup/popupVariables.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentStyles.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentVariables.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipStyles.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipVariables.ts
  packages/react/src/themes/teams/types.ts
Labels: 🗑️ chore, 🚀 ready for review

#2328 perf(Tree): add components for benchmarking
  docs/src/examples/components/List/Performance/ListWith60ListItems.perf.tsx
  docs/src/examples/components/List/Performance/index.tsx
  docs/src/examples/components/Tree/Performance/TreeWith60ListItems.perf.tsx
  docs/src/examples/components/Tree/Performance/index.tsx
  docs/src/examples/components/Tree/index.tsx
Labels: perf, 🚀 ready for review

#2348 feat(hooks): add useAutoControlled() hook
  packages/react-bindings/README.md
  packages/react-bindings/src/hooks/useAutoControlled.ts
  packages/react-bindings/src/index.ts
  packages/react-bindings/test/hooks/useAutoControlled-test.tsx
Labels: ⚙️ enhancement, 🚀 ready for review

#2345 fix(Animation): not to throw if children is not set
  CHANGELOG.md
  packages/react/src/components/Animation/Animation.tsx
  packages/react/test/specs/components/Animation/Animation-test.tsx
Labels: 🧰 fix

#2207 feat(List): add proper support for children API
  CHANGELOG.md
  docs/src/examples/components/List/Content/ListExampleContent.tsx
  docs/src/examples/components/List/Content/ListExampleContentMedia.tsx
  docs/src/examples/components/List/Content/ListExampleEndMedia.tsx
  docs/src/examples/components/List/Content/ListExampleHeader.tsx
  docs/src/examples/components/List/Content/ListExampleHeaderContent.tsx
  docs/src/examples/components/List/Content/ListExampleHeaderMedia.tsx
  docs/src/examples/components/List/Content/ListExampleMedia.tsx
  docs/src/examples/components/List/Performance/ListNested.perf.tsx
  docs/src/examples/components/List/Performance/ListWith60ListItems.perf.tsx
  docs/src/examples/components/List/Performance/index.tsx
  docs/src/examples/components/List/Types/ListExample.tsx
  docs/src/examples/components/List/Types/ListExampleNavigable.tsx
  docs/src/examples/components/List/Types/ListExampleSelectable.tsx
  docs/src/examples/components/List/Usage/ListExampleMemo.tsx
  docs/src/examples/components/List/Usage/index.tsx
  docs/src/examples/components/List/Variations/ListExampleTruncate.tsx
  docs/src/examples/components/List/index.tsx
  packages/react-context-selector/package.json
  packages/react/package.json
  packages/react/src/components/List/List.tsx
  packages/react/src/components/List/ListItem.tsx
  packages/react/src/components/List/listContext.ts
  packages/react/test/specs/components/List/List-test.tsx
  packages/react/tsconfig.json
  packages/state/src/index.ts
  packages/state/src/managers/listManager.ts
Labels: ⚙️ enhancement, 🚀 ready for review

#2192 fix(Provider): render portals inside styled elements
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  docs/src/examples/components/Dialog/Variations/DialogExampleScroll.shorthand.steps.ts
  docs/src/examples/components/Dialog/Variations/DialogExampleScroll.shorthand.tsx
  docs/src/examples/components/Dialog/index.tsx
  docs/src/examples/components/Provider/Types/ProviderExampleStyles.tsx
  docs/src/examples/components/Provider/Types/index.tsx
  packages/react-bindings/src/index.ts
  packages/react/src/components/Dialog/Dialog.tsx
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Portal/PortalInner.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/components/Provider/ProviderBox.tsx
  packages/react/src/components/Provider/usePortalBox.ts
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/themes/teams-dark/componentVariables.ts
  packages/react/src/themes/teams-dark/components/Provider/providerBoxVariables.ts
  packages/react/src/themes/teams-dark/components/Provider/providerVariables.ts
  packages/react/src/themes/teams-high-contrast/componentVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Provider/providerBoxVariables.ts
  packages/react/src/themes/teams-high-contrast/components/Provider/providerVariables.ts
  packages/react/src/themes/teams/componentStyles.ts
  packages/react/src/themes/teams/componentVariables.ts
  packages/react/src/themes/teams/components/Provider/providerStyles.ts
  packages/react/src/themes/teams/components/Provider/providerVariables.ts
  packages/react/test/specs/components/Provider/Provider-test.tsx
  packages/react/test/specs/utils/__snapshots__/felaRenderer-test.tsx.snap
Labels: 🚀 ready for review, 🧰 fix

#2359 fix(whatInput): setWhatInputSource() should change DOM attribute
  CHANGELOG.md
  docs/src/examples/components/Tooltip/Types/TooltipExamplePointing.shorthand.steps.ts
  packages/react/src/components/Popup/Popup.tsx
  packages/react/src/components/Slider/Slider.tsx
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/utils/whatInput.ts
Labels: 🚀 ready for review, 🧰 fix

#2361 fix(Popper): use `keepTogether` for `arrow` modifier
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupExamplePointerOffset.steps.ts
  docs/src/examples/components/Popup/Types/PopupExamplePointerOffset.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  packages/react/src/utils/positioner/Popper.tsx
Labels: 🚀 ready for review, 🧰 fix

#2357 chore(Tooltip): move to function component
  CHANGELOG.md
  packages/accessibility/src/behaviors/Tooltip/tooltipAsDescriptionBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/react-proptypes/src/index.ts
  packages/react/src/components/Tooltip/Tooltip.tsx
  packages/react/src/components/Tooltip/TooltipContent.tsx
  packages/react/src/themes/teams/components/Tooltip/tooltipContentStyles.ts
  packages/react/test/specs/components/Tooltip/TooltipContent-test.ts
Labels: 🚀 ready for review, 🧰 fix

#2369 fix(PerfTest): test name must match filename
  docs/src/components/ComponentDoc/ComponentPerfExample/ComponentPerfChart.tsx
  docs/src/examples/components/Tree/Performance/TreeWith60ListItems.perf.tsx
Labels: 🚀 ready for review

#2356 fix(Carousel): do not render hidden carousel items
  CHANGELOG.md
  docs/src/examples/components/Animation/Usage/AnimationExampleVisible.shorthand.tsx
  docs/src/examples/components/Carousel/Variations/CarouselExampleWithFocusableElements.tsx
  packages/react-bindings/src/index.ts
  packages/react-bindings/src/styles/calculateAnimationTimeout.ts
  packages/react-bindings/src/styles/convertCssTimeToNumber.ts
  packages/react-bindings/test/styles/convertCssTimeToNumber-test.ts
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/Carousel/Carousel.tsx
  packages/react/src/themes/teams/animations/index.ts
  packages/react/src/themes/teams/animations/slide.ts
  packages/react/src/themes/teams/components/Carousel/carouselItemStyles.ts
  packages/react/src/themes/teams/components/Carousel/carouselStyles.ts
  packages/react/src/themes/teams/components/Carousel/carouselVariables.ts
  packages/react/test/specs/components/Carousel/Carousel-test.tsx
Labels: 🚀 ready for review

#2366 chore(Chat): move to functional component
  CHANGELOG.md
  docs/src/prototypes/chatMessages/ControlMessages/controlMessagesGroupBehavior.ts
  docs/src/prototypes/chatMessages/ThreadedMessages/threadChatBehavior.ts
  docs/src/prototypes/chatMessages/ThreadedMessages/threadedMessageBehavior.ts
  packages/accessibility/src/behaviors/Chat/chatBehavior.ts
  packages/accessibility/src/behaviors/Chat/chatMessageBehavior.ts
  packages/accessibility/src/behaviors/index.ts
  packages/react/src/components/Chat/Chat.tsx
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/themes/teams/components/Chat/chatItemStyles.ts
  packages/react/src/themes/teams/components/Chat/chatMessageStyles.ts
  packages/react/src/themes/teams/components/Chat/chatStyles.ts
  packages/react/src/themes/teams/types.ts
  packages/react/test/specs/components/Chat/Chat-test.ts
  packages/react/test/specs/components/Chat/ChatItem-test.tsx
  packages/react/test/specs/components/Chat/ChatMessage-test.tsx
Labels: 🗑️ chore, 🚀 ready for review

#2349 fix(Dropdown): backspace with text selection will also remove selected element
  CHANGELOG.md
  packages/react/src/components/Dropdown/Dropdown.tsx
Labels: 🚀 ready for review, 🧰 fix

#2331 chore(Chat): remove magic static from ChatItem & ChatMessage
  packages/react/src/components/Chat/ChatItem.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
  packages/react/src/components/Chat/chatItemContext.ts
  packages/react/src/utils/getElementProp.ts
  packages/react/src/utils/index.ts
Labels: 🗑️ chore, 🚀 ready for review

#2321 fix(Toolbar): focus first item each time a focused element is hidden
  CHANGELOG.md
  build/gulp/tasks/test-e2e.ts
  e2e/e2eApi.ts
  e2e/tests/toolbarMenuOverflow-example.tsx
  e2e/tests/toolbarMenuOverflow-test.ts
  e2e/tests/toolbarMenuOverflowWrapped-example.tsx
  e2e/tests/toolbarMenuOverflowWrapped-test.ts
  packages/react/src/components/Toolbar/Toolbar.tsx
Labels: accessibility, 🚀 ready for review, 🧰 fix

#2370 chore: refactor perf flags
  packages/react-bindings/src/hooks/useStyles.ts
  packages/react-bindings/src/styles/resolveStyles.ts
  packages/react-bindings/src/styles/types.ts
  packages/react-bindings/test/hooks/useStyles-test.tsx
  packages/react-bindings/test/styles/resolveStyles-test.ts
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/types.ts
  packages/react/src/utils/mergeProviderContexts.ts
  packages/react/src/utils/renderComponent.tsx
  packages/react/test/specs/utils/mergeProviderContexts/mergeProviderContexts-test.ts
Labels: 🗑️ chore, 🚀 ready for review

#2293 feat: add on change handlers and renamed others for standardisation
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentDoc.tsx
  docs/src/components/ComponentDoc/ComponentPerfExample/ComponentPerfChart.tsx
  docs/src/examples/components/Alert/Types/AlertExampleDismissible.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupColorPickerExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupExample.shorthand.tsx
  docs/src/examples/components/RadioGroup/Types/RadioGroupVerticalExample.shorthand.tsx
  docs/src/prototypes/alerts/BannerAlerts.tsx
  docs/src/prototypes/dropdowns/AsyncDropdownSearch.tsx
  docs/src/views/CategoryColorSchemes.tsx
  docs/src/views/ColorSchemes.tsx
  packages/code-sandbox/src/SandboxApp.tsx
  packages/react/src/components/Accordion/Accordion.tsx
  packages/react/src/components/Alert/Alert.tsx
  packages/react/src/components/Dropdown/Dropdown.tsx
  packages/react/src/components/Embed/Embed.tsx
  packages/react/src/components/Menu/Menu.tsx
  packages/react/src/components/RadioGroup/RadioGroup.tsx
  packages/react/src/components/RadioGroup/RadioGroupItem.tsx
  packages/react/src/components/Toolbar/ToolbarMenuItem.tsx
  packages/react/src/components/Tree/Tree.tsx
  packages/react/test/specs/commonTests/isConformant.tsx
  packages/react/test/specs/components/Accordion/Accordion-test.tsx
  packages/react/test/specs/components/Alert/Alert-test.tsx
  packages/react/test/specs/components/Carousel/Carousel-test.tsx
  packages/react/test/specs/components/Checkbox/Checkbox-test.tsx
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/specs/components/Embed/Embed-test.tsx
  packages/react/test/specs/components/HierarchicalTree/HierarchicalTree-test.tsx
  packages/react/test/specs/components/Input/Input-test.tsx
  packages/react/test/specs/components/Menu/Menu-test.tsx
  packages/react/test/specs/components/Menu/MenuItem-test.tsx
  packages/react/test/specs/components/MenuButton/MenuButton-test.tsx
  packages/react/test/specs/components/RadioGroup/RadioGroup-test.tsx
  packages/react/test/specs/components/RadioGroup/RadioGroupItem-test.ts
  packages/react/test/specs/components/Slider/Slider-test.tsx
  packages/react/test/specs/components/SplitButton/SplitButton-test.tsx
  packages/react/test/specs/components/TextArea/TextArea-test.tsx
  packages/react/test/specs/components/Toolbar/ToolbarMenuItem-test.ts
  packages/react/test/specs/components/Tree/Tree-test.tsx
Labels: ⚙️ enhancement, 🚀 ready for review

#2363 fix(Chat): properly position `actions` with `overflow`
  CHANGELOG.md
  docs/src/examples/components/Chat/Usage/ChatExampleInScrollable.shorthand.steps.ts
  docs/src/examples/components/Chat/Usage/ChatExampleInScrollable.shorthand.tsx
  packages/react/src/components/Chat/ChatMessage.tsx
Labels: 🚀 ready for review, 🧰 fix

#2340 perf: disable "sanitize-css" for production
  CHANGELOG.md
  docs/src/components/ComponentDoc/ComponentExample/ComponentExample.tsx
  packages/react-bindings/src/hooks/useStyles.ts
  packages/react-bindings/src/styles/resolveStyles.ts
  packages/react-bindings/src/styles/types.ts
  packages/react-bindings/test/styles/resolveStyles-test.ts
  packages/react/src/components/Animation/Animation.tsx
  packages/react/src/components/Design/Design.tsx
  packages/react/src/components/Provider/Provider.tsx
  packages/react/src/utils/felaSanitizeCssPlugin.ts
  packages/react/src/utils/mergeProviderContexts.ts
  packages/react/test/specs/utils/felaSanitizeCssPlugin-test.ts
  packages/react/test/utils/withProvider.tsx
Labels: perf, 🚀 ready for review

#2364 fix(Popup|Tooltip): fix wrong positioning of pointing beak on content edges
  CHANGELOG.md
  docs/src/examples/components/Popup/Types/PopupExamplePointerMargin.shorthand.tsx
  docs/src/examples/components/Popup/Types/index.tsx
  packages/react/src/themes/teams/components/Popup/popupContentStyles.ts
  packages/react/src/themes/teams/components/Popup/popupContentVariables.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentStyles.ts
  packages/react/src/themes/teams/components/Tooltip/tooltipContentVariables.ts
  packages/react/src/themes/teams/getPointerStyles.ts
Labels: 🚀 ready for review, 🧰 fix

#2339 Virtualized table prototype
  CHANGELOG.md
  docs/package.json
  docs/src/components/Sidebar/Sidebar.tsx
  docs/src/prototypes/VirtualizedTable/VirtualizedTable.tsx
  docs/src/prototypes/VirtualizedTable/VirtualizedTables.tsx
  docs/src/prototypes/VirtualizedTable/index.tsx
  docs/src/prototypes/VirtualizedTable/itemsGenerator.ts
  docs/src/routes.tsx
  packages/react/src/components/Table/Table.tsx
  packages/react/src/components/Table/TableCell.tsx
  packages/react/src/components/Table/TableRow.tsx
  packages/react/src/components/Tree/Tree.tsx
  yarn.lock
Labels: 🚀 ready for review

#2228 chore(tests): refactor Dropdown tests
  package.json
  packages/react/jest.config.js
  packages/react/test/setup.ts
  packages/react/test/specs/components/Dropdown/Dropdown-test.tsx
  packages/react/test/specs/components/Dropdown/test-utils.tsx
  packages/react/test/utils/withProvider.tsx
  types/jest-dom.d.ts
  yarn.lock
Labels: 🗑️ chore, 🚀 ready for review

#2382 chore(DropdownItem): refactor to functional component with hooks
  CHANGELOG.md
  packages/react/src/components/Dropdown/DropdownItem.tsx
  packages/react/src/themes/teams/components/Dropdown/dropdownItemStyles.ts
  packages/react/src/themes/teams/components/Dropdown/dropdownVariables.ts
  packages/react/test/specs/components/Dropdown/DropdownItem-test.tsx
Labels: ready for merge, 🗑️ chore

#1925 perf: use `inline-style-expand-shorthand` for expanding
  CHANGELOG.md
  build/dangerjs/detectNonApprovedDependencies/approvedPackages.ts
  packages/react/package.json
  packages/react/src/utils/cssExpandShorthand.ts
  packages/react/src/utils/felaExpandCssShorthandsPlugin.ts
  packages/react/src/utils/felaRenderer.tsx
  packages/react/test/specs/utils/felaExpandCssShorthandsPlugin-test.ts
  yarn.lock
Labels: perf, 🚀 ready for review
